gText_AbnormalWeatherEnded_Rain::
	.ifdef ENGLISH
	.string "The massive downpour appears to\n"
	.string "have stopped…$"
	.else
	.ifdef GERMAN
	.string "Die starken Niederschläge haben\n"
	.string "scheinbar nachgelassen…$"
	.endif
	.endif

gText_AbnormalWeatherEnded_Sun::
	.ifdef ENGLISH
	.string "The intense sunshine appears to\n"
	.string "have subsided…$"
	.else
	.ifdef GERMAN
	.string "Die starke Sonneneinwirkung hat\n"
	.string "scheinbar nachgelassen…$"
	.endif
	.endif
