FallarborTown_BattleTentLobby_Text_WelcomeToBattleTent:
	.ifdef ENGLISH
	.string "I welcome you to the BATTLE TENT\n"
	.string "FALLARBOR SITE!\p"
	.string "I am your guide to the Set KO Tourney!$"
	.else
	.ifdef GERMAN
	.string "Willkommen im KAMPFCAMP von\n"
	.string "LAUBWECHSELFELD!\p"
	.string "Ich begleite dich zu dem K.O.-\n"
	.string "Teamturnier.$"
	.endif
	.endif

FallarborTown_BattleTentLobby_Text_TakeChallenge:
	.ifdef ENGLISH
	.string "Now, do you wish to take the challenge\n"
	.string "of a Set KO Tourney?$"
	.else
	.ifdef GERMAN
	.string "Möchtest du dich der Herausforderung\n"
	.string "des K.O.-Kampfturniers stellen?$"
	.endif
	.endif

FallarborTown_BattleTentLobby_Text_AwaitAnotherChallenge:
	.ifdef ENGLISH
	.string "We await your challenge on\n"
	.string "another occasion!$"
	.else
	.ifdef GERMAN
	.string "Wir freuen uns auf deine nächste\n"
	.string "Herausforderung.$"
	.endif
	.endif

FallarborTown_BattleTentLobby_Text_ExplainFallarborTent:
	.ifdef ENGLISH
	.string "In the FALLARBOR BATTLE TENT,\n"
	.string "we undertake the Set KO Tourney.\p"
	.string "All participants enter with a team of\n"
	.string "three POKéMON.\p"
	.string "The three POKéMON must be lined up\n"
	.string "in the order that they are to appear in.\p"
	.string "During battle, the POKéMON will appear\n"
	.string "one at a time in the preset order.\p"
	.string "Once a POKéMON enters battle, it must\n"
	.string "remain out until the match is decided.\p"
	.string "If a match remains undecided in\n"
	.string "three turns, it goes to judging.\p"
	.string "If you wish to interrupt your challenge,\n"
	.string "please save the game.\p"
	.string "If you don't save, you will not be able\n"
	.string "to continue with your challenge.\p"
	.string "If you pull off the feat of beating\n"
	.string "three TRAINERS in succession,\l"
	.string "we will present you with a fine prize.$"
	.else
	.ifdef GERMAN
	.string "Im KAMPFCAMP von LAUBWECHSELFELD\n"
	.string "findet das K.O.-Teamturnier statt.\p"
	.string "Jeder Teilnehmer darf drei POKéMON\n"
	.string "in den Kampf mitnehmen.\p"
	.string "Diese müssen in der Reihenfolge\n"
	.string "angeordnet werden, in der sie kämpfen\l"
	.string "sollen.\p"
	.string "Diese Reihenfolge wird im Kampf strikt\n"
	.string "eingehalten.\p"
	.string "Ein POKéMON bleibt solange im Kampf,\n"
	.string "bis der Kampf entschieden ist.\p"
	.string "Wenn ein Kampf nach drei Runden noch\n"
	.string "nicht entschieden ist, wird der Sieger\l"
	.string "durch ein richterliches Urteil bestimmt.\p"
	.string "Wenn du deine Herausforderung\n"
	.string "unterbrechen möchtest, speichere\l"
	.string "bitte dein Spiel.\p"
	.string "Wenn du ohne Speichern unterbrichst,\n"
	.string "ist die Herausforderung beendet.\p"
	.string "Besiegst du drei TRAINER in Folge,\n"
	.string "gewinnst du einen fantastischen Preis.$"
	.endif
	.endif

FallarborTown_BattleTentLobby_Text_SaveBeforeChallenge:
	.ifdef ENGLISH
	.string "Before showing you to the BATTLE\n"
	.string "TENT, I must save. Is that okay?$"
	.else
	.ifdef GERMAN
	.string "Bevor du das KAMPFCAMP betrittst,\n"
	.string "musst du dein Spiel speichern. Okay?$"
	.endif
	.endif

@ Unused
FallarborTown_BattleTentLobby_Text_WhichLevelMode:
	.ifdef ENGLISH
	.string "We offer two levels of challenge,\n"
	.string "Level 50 and Open Level.\l"
	.string "Which is your choice?$"
	.else
	.ifdef GERMAN
	.string "We offer two levels of challenge,\n"
	.string "Level 50 and Open Level.\l"
	.string "Which is your choice?$"
	.endif
	.endif

FallarborTown_BattleTentLobby_Text_SelectThreeMons:
	.ifdef ENGLISH
	.string "Very well, now select your\n"
	.string "three POKéMON, please.$"
	.else
	.ifdef GERMAN
	.string "Sehr schön! Dann bestimme jetzt bitte\n"
	.string "deine drei POKéMON.$"
	.endif
	.endif

FallarborTown_BattleTentLobby_Text_NotEnoughValidMonsLv50:
	.ifdef ENGLISH
	.string "My dear challenger!\p"
	.string "You do not have the three POKéMON\n"
	.string "required for entry.\p"
	.string "They also must not hold the same\n"
	.string "kinds of items.\p"
	.string "EGGS{STR_VAR_1} ineligible.\p"
	.string "When you have made your preparations,\n"
	.string "please do return.$"
	.else
	.ifdef GERMAN
	.string "Verehrter Herausforderer!\p"
	.string "Leider besitzt du keine drei POKéMON,\n"
	.string "die an dem Kampf teilnehmen können.\p"
	.string "Sie müssen außerdem unterschiedliche\n"
	.string "Items tragen.\p"
	.string "EIer{STR_VAR_1} nicht zugelassen.\p"
	.string "Bitte schließ deine Vorbereitungen ab\n"
	.string "und komm dann wieder.$"
	.endif
	.endif

FallarborTown_BattleTentLobby_Text_NotEnoughValidMonsLvOpen:
	.ifdef ENGLISH
	.string "My dear challenger!\p"
	.string "You do not have the three POKéMON\n"
	.string "required for entry.\p"
	.string "To qualify, you must bring three\n"
	.string "different kinds of POKéMON.\p"
	.string "They also must not hold the same\n"
	.string "kinds of items.\p"
	.string "EGGS{STR_VAR_1} ineligible.\p"
	.string "When you have made your preparations,\n"
	.string "please do return.$"
	.else
	.ifdef GERMAN
	.string "Verehrter Herausforderer!\p"
	.string "Leider besitzt du keine drei POKéMON,\n"
	.string "die an dem Kampf teilnehmen können.\p"
	.string "Du brauchst drei verschiedene POKéMON.\p"
	.string "Sie müssen außerdem unterschiedliche\n"
	.string "Items tragen.\p"
	.string "EIer{STR_VAR_1} nicht zugelassen.\p"
	.string "Bitte schließ deine Vorbereitungen ab\n"
	.string "und komm dann wieder.$"
	.endif
	.endif

FallarborTown_BattleTentLobby_Text_GuideYouToBattleTent:
	.ifdef ENGLISH
	.string "I shall now guide you to\n"
	.string "the BATTLE TENT.$"
	.else
	.ifdef GERMAN
	.string "Ich werde dich nun zum KAMPFCAMP\n"
	.string "begleiten.$"
	.endif
	.endif

FallarborTown_BattleTentLobby_Text_DidntSaveBeforeQuitting:
	.ifdef ENGLISH
	.string "My dear challenger!\p"
	.string "You did not save the game before\n"
	.string "shutting down, did you?\p"
	.string "It is unfortunate, but that has\n"
	.string "resulted in your disqualification\l"
	.string "from your challenge.\p"
	.string "You may, of course, start with a fresh\n"
	.string "challenge.$"
	.else
	.ifdef GERMAN
	.string "Verehrter Herausforderer!\p"
	.string "Du hast, bevor du die Herausforderung\n"
	.string "abgebrochen hast, nicht gespeichert.\p"
	.string "Daher wirst du leider für diese\n"
	.string "Herausforderung disqualifiziert.\l"
	.string "Schade!\p"
	.string "Natürlich kannst du dich einer neuen\n"
	.string "Herausforderung stellen!$"
	.endif
	.endif

FallarborTown_BattleTentLobby_Text_BeatThreeTrainers:
	.ifdef ENGLISH
	.string "How splendid! You have beaten\n"
	.string "three TRAINERS in succession!$"
	.else
	.ifdef GERMAN
	.string "Hervorragend! Du hast drei TRAINER in\n"
	.string "Folge besiegt!$"
	.endif
	.endif

FallarborTown_BattleTentLobby_Text_WaitWhileSaveGame:
	.ifdef ENGLISH
	.string "Please wait while I save the game.$"
	.else
	.ifdef GERMAN
	.string "Dein Erfolg wird gespeichert.\n"
	.string "Bitte warten.$"
	.endif
	.endif

FallarborTown_BattleTentLobby_Text_PresentYouWithPrize:
	.ifdef ENGLISH
	.string "In commemoration of your 3-win streak,\n"
	.string "we present you with this prize.$"
	.else
	.ifdef GERMAN
	.string "In Anerkennung deines dreifachen\n"
	.string "Sieges überreichen wir dir diesen Preis.$"
	.endif
	.endif

FallarborTown_BattleTentLobby_Text_ReceivedPrize:
	.ifdef ENGLISH
	.string "{PLAYER} received the prize\n"
	.string "{STR_VAR_1}.$"
	.else
	.ifdef GERMAN
	.string "{PLAYER} gewinnt\n"
	.string "{STR_VAR_1}.$"
	.endif
	.endif

FallarborTown_BattleTentLobby_Text_BagFullReturnForPrize:
	.ifdef ENGLISH
	.string "Oh?\n"
	.string "Your BAG seems to be full.\p"
	.string "I urge you to clear space and\n"
	.string "return for your prize.$"
	.else
	.ifdef GERMAN
	.string "Oh, dein BEUTEL ist voll.\p"
	.string "Bitte schaffe Platz in deinem BEUTEL\n"
	.string "und komme dann wieder.$"
	.endif
	.endif

FallarborTown_BattleTentLobby_Text_ThankYouWaitWhileSaving:
	.ifdef ENGLISH
	.string "Thank you so much for participating!\p"
	.string "Please wait while I save the game.$"
	.else
	.ifdef GERMAN
	.string "Vielen Dank für die Teilnahme!\p"
	.string "Das Ergebnis wird gespeichert.\n"
	.string "Bitte warten.$"
	.endif
	.endif

FallarborTown_BattleTentLobby_Text_AwaitAnotherChallenge2:
	.ifdef ENGLISH
	.string "We await your challenge on\n"
	.string "another occasion!$"
	.else
	.ifdef GERMAN
	.string "Wir freuen uns auf deine nächste\n"
	.string "Herausforderung.$"
	.endif
	.endif

FallarborTown_BattleTentLobby_Text_LookingForwardToArrival:
	.ifdef ENGLISH
	.string "We have been looking forward to\n"
	.string "your arrival.\p"
	.string "Before I show you to the BATTLE TENT,\n"
	.string "I must save the game. Please wait.$"
	.else
	.ifdef GERMAN
	.string "Wir haben schon auf dich gewartet!\p"
	.string "Bevor du das KAMPFCAMP betrittst,\n"
	.string "wird dein Spiel gespeichert.\l"
	.string "Bitte warten.$"
	.endif
	.endif

VerdanturfTown_BattleTentLobby_Text_WelcomeToBattleTent:
	.ifdef ENGLISH
	.string "I welcome you to the BATTLE TENT\n"
	.string "VERDANTURF SITE!\p"
	.string "Here, the TRAINER's trust toward\n"
	.string "POKéMON is tested.$"
	.else
	.ifdef GERMAN
	.string "Willkommen im KAMPFCAMP von\n"
	.string "WIESENFLUR!\p"
	.string "Hier wird das Vertrauen der TRAINER in\n"
	.string "ihre POKéMON getestet.$"
	.endif
	.endif

VerdanturfTown_BattleTentLobby_Text_TakeChallenge:
	.ifdef ENGLISH
	.string "Do you wish to take the VERDANTURF\n"
	.string "BATTLE TENT challenge?$"
	.else
	.ifdef GERMAN
	.string "Möchtest du dich der Herausforderung\n"
	.string "des WIESENFLUR KAMPFCAMPs stellen?$"
	.endif
	.endif

VerdanturfTown_BattleTentLobby_Text_ExplainVerdanturfTent:
	.ifdef ENGLISH
	.string "In the VERDANTURF BATTLE TENT,\n"
	.string "there is one crucial rule that must\l"
	.string "be obeyed.\p"
	.string "TRAINERS are permitted only to switch\n"
	.string "their POKéMON in and out.\p"
	.string "TRAINERS are otherwise forbidden to\n"
	.string "command their POKéMON.\p"
	.string "The POKéMON are to behave according\n"
	.string "to their nature and battle on their own.\p"
	.string "You must put your trust in your\n"
	.string "POKéMON and watch over them.\p"
	.string "If you achieve the honor of beating\n"
	.string "three TRAINERS in succession,\l"
	.string "we will present you with a prize.\p"
	.string "If you want to interrupt your\n"
	.string "challenge, please save the game.\p"
	.string "If you don't save before interrupting,\n"
	.string "you will be disqualified.$"
	.else
	.ifdef GERMAN
	.string "Im KAMPFCAMP von WIESENFLUR gibt es\n"
	.string "eine entscheidende Regel, die beachtet\l"
	.string "werden muss.\p"
	.string "TRAINER dürfen ihre POKéMON lediglich\n"
	.string "in den Kampf rufen und zurückziehen.\p"
	.string "Ansonsten ist es ihnen nicht erlaubt,\n"
	.string "in den Kampf einzugreifen.\p"
	.string "Die POKéMON sollen sich gemäß ihres\n"
	.string "Wesens verhalten und kämpfen.\p"
	.string "Du musst deinen POKéMON vertrauen und\n"
	.string "sie beobachten.\p"
	.string "Wenn du es schaffst, drei TRAINER in\n"
	.string "Folge zu besiegen, bekommst du einen\l"
	.string "Preis von uns.\p"
	.string "Wenn du deine Herausforderung\n"
	.string "unterbrechen willst, speichere bitte\l"
	.string "dein Spiel.\p"
	.string "Brichst du die Herausforderung ohne zu\n"
	.string "speichern ab, wirst du disqualifiziert.$"
	.endif
	.endif

VerdanturfTown_BattleTentLobby_Text_ReturnFortified:
	.ifdef ENGLISH
	.string "When you have fortified your heart\n"
	.string "and POKéMON, you must return.$"
	.else
	.ifdef GERMAN
	.string "Hast du dein Herz gestärkt und deine\n"
	.string "POKéMON, dann komm wieder.$"
	.endif
	.endif

@ Unused
VerdanturfTown_BattleTentLobby_Text_WhichLevelMode:
	.ifdef ENGLISH
	.string "There are two levels of difficulty,\n"
	.string "Level 50 and Open Level.\l"
	.string "Which is your choice of a challenge?$"
	.else
	.ifdef GERMAN
	.string "There are two levels of difficulty,\n"
	.string "Level 50 and Open Level.\l"
	.string "Which is your choice of a challenge?$"
	.endif
	.endif

VerdanturfTown_BattleTentLobby_Text_NotEnoughValidMonsLv50:
	.ifdef ENGLISH
	.string "Sigh…\p"
	.string "You do not have the three POKéMON\n"
	.string "required for the challenge.\p"
	.string "To enter, you must provide three\n"
	.string "different kinds of POKéMON.\p"
	.string "They also must not be holding\n"
	.string "the same kinds of items.\p"
	.string "EGGS{STR_VAR_1} ineligible.\p"
	.string "Come back when you have made\n"
	.string "your preparations.$"
	.else
	.ifdef GERMAN
	.string "Seufz…\p"
	.string "Leider besitzt du keine drei POKéMON,\n"
	.string "die an dem Kampf teilnehmen können.\p"
	.string "Du brauchst drei verschiedene POKéMON.\p"
	.string "Sie müssen außerdem unterschiedliche\n"
	.string "Items tragen.\p"
	.string "EIer{STR_VAR_1} nicht zugelassen.\p"
	.string "Bitte schließ deine Vorbereitungen ab\n"
	.string "und komm dann wieder.$"
	.endif
	.endif

VerdanturfTown_BattleTentLobby_Text_NotEnoughValidMonsLvOpen:
	.ifdef ENGLISH
	.string "Sigh…\p"
	.string "You do not have the three POKéMON\n"
	.string "required for the challenge.\p"
	.string "To enter, you must provide three\n"
	.string "different kinds of POKéMON.\p"
	.string "They also must not be holding\n"
	.string "the same kinds of items.\p"
	.string "EGGS{STR_VAR_1} ineligible.\p"
	.string "Come back when you have made\n"
	.string "your preparations.$"
	.else
	.ifdef GERMAN
	.string "Seufz…\p"
	.string "Leider besitzt du keine drei POKéMON,\n"
	.string "die an dem Kampf teilnehmen können.\p"
	.string "Du brauchst drei verschiedene POKéMON.\p"
	.string "Sie müssen außerdem unterschiedliche\n"
	.string "Items tragen.\p"
	.string "EIer{STR_VAR_1} nicht zugelassen.\p"
	.string "Bitte schließ deine Vorbereitungen ab\n"
	.string "und komm dann wieder.$"
	.endif
	.endif

VerdanturfTown_BattleTentLobby_Text_SelectThreeMons:
	.ifdef ENGLISH
	.string "Good. Now, you must select your\n"
	.string "three POKéMON.$"
	.else
	.ifdef GERMAN
	.string "Gut. Dann bestimme jetzt deine drei\n"
	.string "POKéMON.$"
	.endif
	.endif

VerdanturfTown_BattleTentLobby_Text_SaveBeforeChallenge:
	.ifdef ENGLISH
	.string "I must save before I show you to\n"
	.string "the BATTLE TENT. Is that okay?$"
	.else
	.ifdef GERMAN
	.string "Bevor du das KAMPFCAMP betrittst,\n"
	.string "musst du dein Spiel speichern. Okay?$"
	.endif
	.endif

VerdanturfTown_BattleTentLobby_Text_NowFollowMe:
	.ifdef ENGLISH
	.string "Good.\n"
	.string "Now, follow me.$"
	.else
	.ifdef GERMAN
	.string "Gut. Dann folge mir bitte.$"
	.endif
	.endif

VerdanturfTown_BattleTentLobby_Text_ResultsWillBeRecorded:
	.ifdef ENGLISH
	.string "I feel privileged for having seen\n"
	.string "your POKéMON's exploits.\p"
	.string "The results will be recorded.\n"
	.string "I must ask you to briefly wait.$"
	.else
	.ifdef GERMAN
	.string "Ich fühle mich geehrt, dass ich deinen\n"
	.string "POKéMON zuschauen durfte.\p"
	.string "Das Ergebnis wird gespeichert.\n"
	.string "Bitte warte einen Moment.$"
	.endif
	.endif

VerdanturfTown_BattleTentLobby_Text_AchievedThreeWinStreak:
	.ifdef ENGLISH
	.string "To achieve a 3-win streak…\p"
	.string "The bonds that bind your heart with\n"
	.string "your POKéMON seem firm and true.$"
	.else
	.ifdef GERMAN
	.string "Drei Siege in Folge…\p"
	.string "Das Band zwischen dir und deinen\n"
	.string "POKéMON ist wirklich stark.$"
	.endif
	.endif

VerdanturfTown_BattleTentLobby_Text_FeatWillBeRecorded:
	.ifdef ENGLISH
	.string "Your feat will be recorded.\n"
	.string "I must ask you to briefly wait.$"
	.else
	.ifdef GERMAN
	.string "Dein Erfolg wird gespeichert.\n"
	.string "Bitte warte einen Moment.$"
	.endif
	.endif

VerdanturfTown_BattleTentLobby_Text_PresentYouWithPrize:
	.ifdef ENGLISH
	.string "For the feat of your 3-win streak,\n"
	.string "we present you with this prize.$"
	.else
	.ifdef GERMAN
	.string "Für deinen dreifachen Sieg bekommst du\n"
	.string "von uns diesen Preis überreicht.$"
	.endif
	.endif

SlateportCity_BattleTentLobby_Text_WelcomeToBattleTent:
	.ifdef ENGLISH
	.string "Welcome to the BATTLE TENT\n"
	.string "SLATEPORT SITE!\p"
	.string "I am your guide to the Battle Swap\n"
	.string "Tournament.$"
	.else
	.ifdef GERMAN
	.string "Willkommen im KAMPFCAMP von\n"
	.string "GRAPHITPORT.\p"
	.string "Ich begleite dich zum Wechselkampf-\n"
	.string "Turnier.$"
	.endif
	.endif

SlateportCity_BattleTentLobby_Text_TakeChallenge:
	.ifdef ENGLISH
	.string "Would you like to take the Battle\n"
	.string "Swap challenge?$"
	.else
	.ifdef GERMAN
	.string "Möchtest du am Wechselkampf\n"
	.string "teilnehmen?$"
	.endif
	.endif

SlateportCity_BattleTentLobby_Text_ExplainSlateportTent:
	.ifdef ENGLISH
	.string "Here at the SLATEPORT BATTLE TENT,\n"
	.string "we hold Battle Swap events\l"
	.string "using rental POKéMON.\p"
	.string "First, you will be loaned three\n"
	.string "POKéMON specifically for this event.\p"
	.string "Using the supplied rental POKéMON,\n"
	.string "you must conduct a SINGLE BATTLE.\p"
	.string "If you win, you are permitted to trade\n"
	.string "one of your rental POKéMON.\p"
	.string "Repeat this cycle of battling and\n"
	.string "trading--if you win three times in\l"
	.string "a row, you will earn a fine prize.\p"
	.string "If you want to interrupt your\n"
	.string "challenge, please save the game.\p"
	.string "If you don't save before interrupting,\n"
	.string "you will be disqualified.$"
	.else
	.ifdef GERMAN
	.string "Hier im KAMPFCAMP von GRAPHITPORT\n"
	.string "halten wir Wechselkampf-Turniere ab,\l"
	.string "die mit Leih-PKMN ausgetragen werden.\p"
	.string "Als Erstes leihst du dir drei POKéMON.\p"
	.string "Mit diesen kannst du an einem\n"
	.string "EINZELKAMPF teilnehmen.\p"
	.string "Gewinnst du, darfst du ein Leih-\n"
	.string "POKéMON tauschen.\p"
	.string "Wiederhole diese Folge von Siegen und\n"
	.string "Tausch. Gewinnst du drei Mal in Folge,\l"
	.string "erhältst du einen Preis.\p"
	.string "Wenn du die Herausforderung abbrechen\n"
	.string "willst, speichere dein Spiel.\p"
	.string "Wenn du ohne zu speichern abbrichst,\n"
	.string "wirst du disqualifiziert.$"
	.endif
	.endif

SlateportCity_BattleTentLobby_Text_LookForwardToNextVisit:
	.ifdef ENGLISH
	.string "We look forward to your next visit.$"
	.else
	.ifdef GERMAN
	.string "Wir freuen uns auf deine nächste\n"
	.string "Herausforderung.$"
	.endif
	.endif

@ Unused
SlateportCity_BattleTentLobby_Text_WhichLevelMode:
	.ifdef ENGLISH
	.string "Which level do you wish to challenge?\n"
	.string "Level 50 or Level 100?$"
	.else
	.ifdef GERMAN
	.string "Which level do you wish to challenge?\n"
	.string "Level 50 or Level 100?$"
	.endif
	.endif

SlateportCity_BattleTentLobby_Text_SaveBeforeChallenge:
	.ifdef ENGLISH
	.string "Before you begin your challenge,\n"
	.string "I need to save data. Is that okay?$"
	.else
	.ifdef GERMAN
	.string "Bevor du dich der Herausforderung\n"
	.string "stellst, speichere ich dein Spiel. Okay?$"
	.endif
	.endif

@ Unused
SlateportCity_BattleTentLobby_Text_HoldMonsForSafekeeping:
	.ifdef ENGLISH
	.string "Okay, I will hold your POKéMON for\n"
	.string "safekeeping while you compete.$"
	.else
	.ifdef GERMAN
	.string "Okay, I will hold your POKéMON for\n"
	.string "safekeeping while you compete.$"
	.endif
	.endif

SlateportCity_BattleTentLobby_Text_StepThisWay:
	.ifdef ENGLISH
	.string "Please step this way.$"
	.else
	.ifdef GERMAN
	.string "Bitte hier entlang.$"
	.endif
	.endif

SlateportCity_BattleTentLobby_Text_ReturnRentalMonsSaveResults:
	.ifdef ENGLISH
	.string "Thank you for participating!\p"
	.string "I will return your POKéMON in exchange\n"
	.string "for our rental POKéMON.\p"
	.string "I must also save your event results.\n"
	.string "Please wait.$"
	.else
	.ifdef GERMAN
	.string "Vielen Dank für deine Teilnahme!\p"
	.string "Ich gebe dir nun deine POKéMON\n"
	.string "zurück.\p"
	.string "Ich werde das Ergebnis speichern.\n"
	.string "Bitte warte einen Moment.$"
	.endif
	.endif

@ Unused
SlateportCity_BattleTentLobby_Text_ReturnMonsExchangeRentals:
	.ifdef ENGLISH
	.string "I will return your POKéMON in exchange\n"
	.string "for our rental POKéMON.$"
	.else
	.ifdef GERMAN
	.string "I will return your POKéMON in exchange\n"
	.string "for our rental POKéMON.$"
	.endif
	.endif

SlateportCity_BattleTentLobby_Text_WonThreeMatchesReturnMons:
	.ifdef ENGLISH
	.string "Congratulations!\n"
	.string "You've won three straight matches!\p"
	.string "I will return your POKéMON in exchange\n"
	.string "for our rental POKéMON.\p"
	.string "I must also save your event results.\n"
	.string "Please wait.$"
	.else
	.ifdef GERMAN
	.string "Herzlichen Glückwunsch!\n"
	.string "Du hast drei Kämpfe in Folge gewonnen!\p"
	.string "Ich gebe dir nun deine POKéMON\n"
	.string "zurück.\p"
	.string "Ich werde deinen Erfolg speichern.\n"
	.string "Bitte warte einen Moment.$"
	.endif
	.endif

SlateportCity_BattleTentLobby_Text_AwardYouThisPrize:
	.ifdef ENGLISH
	.string "In recognition of your 3-win streak,\n"
	.string "we award you this prize.$"
	.else
	.ifdef GERMAN
	.string "Für deinen dreifachen Sieg bekommst du\n"
	.string "von uns diesen Preis überreicht.$"
	.endif
	.endif

SlateportCity_BattleTentLobby_Text_NoRoomInBagMakeRoom:
	.ifdef ENGLISH
	.string "Oh?\n"
	.string "You seem to have no room for this.\p"
	.string "Please make room in your BAG and\n"
	.string "let me know.$"
	.else
	.ifdef GERMAN
	.string "Oh, dein BEUTEL ist voll.\p"
	.string "Bitte schaffe Platz in deinem BEUTEL\n"
	.string "und komme dann wieder.$"
	.endif
	.endif

SlateportCity_BattleTentLobby_Text_BeenWaitingForYou:
	.ifdef ENGLISH
	.string "We've been waiting for you!\p"
	.string "Before we resume your challenge,\n"
	.string "I must save the game.$"
	.else
	.ifdef GERMAN
	.string "Wir haben auf dich gewartet!\p"
	.string "Bevor du die Herausforderung\n"
	.string "fortsetzt, speichere ich dein Spiel.$"
	.endif
	.endif

SlateportCity_BattleTentLobby_Text_DidntSaveBeforeQuitting:
	.ifdef ENGLISH
	.string "I'm sorry to say this, but you didn't\n"
	.string "save before you quit playing last time.\p"
	.string "As a result, you have been disqualified\n"
	.string "from your challenge.$"
	.else
	.ifdef GERMAN
	.string "Entschuldigung!\p"
	.string "Du hast, bevor du die Herausforderung\n"
	.string "abgebrochen hast, nicht gespeichert.\p"
	.string "Daher wirst du für diese Herausforde-\n"
	.string "rung disqualifiziert. Schade!$"
	.endif
	.endif

@ Unused
SlateportCity_BattleTentLobby_Text_ReturnPersonalMons:
	.ifdef ENGLISH
	.string "We'll return your personal POKéMON.$"
	.else
	.ifdef GERMAN
	.string "We’ll return your personal POKéMON.$"
	.endif
	.endif

@ Unused
SlateportCity_BattleTentLobby_Text_ReceivedPrize:
	.ifdef ENGLISH
	.string "{PLAYER} received the prize\n"
	.string "{STR_VAR_1}.$"
	.else
	.ifdef GERMAN
	.string "{PLAYER} received the prize\n"
	.string "{STR_VAR_1}.$"
	.endif
	.endif

@ Unused
SlateportCity_BattleTentLobby_Text_RulesAreListed:
	.ifdef ENGLISH
	.string "The Battle Swap rules are listed.$"
	.else
	.ifdef GERMAN
	.string "The Battle Swap rules are listed.$"
	.endif
	.endif

@ Unused
SlateportCity_BattleTentLobby_Text_ReadWhichHeading:
	.ifdef ENGLISH
	.string "Which heading do you want to read?$"
	.else
	.ifdef GERMAN
	.string "Which heading do you want to read?$"
	.endif
	.endif

SlateportCity_BattleTentLobby_Text_ExplainBasicRules:
	.ifdef ENGLISH
	.string "In a Battle Swap event, you may use\n"
	.string "only three POKéMON.\p"
	.string "Whether you are renting or swapping,\n"
	.string "your team may not have two or more\l"
	.string "of the same POKéMON.$"
	.else
	.ifdef GERMAN
	.string "In einem Wechselkampf darfst du\n"
	.string "nur drei POKéMON einsetzen.\p"
	.string "Egal, ob du sie dir ausleihst oder\n"
	.string "tauschst, du darfst keine zwei gleichen\l"
	.string "POKéMON in deinem Team haben.$"
	.endif
	.endif

SlateportCity_BattleTentLobby_Text_ExplainSwapPartnerRules:
	.ifdef ENGLISH
	.string "You may swap POKéMON only with\n"
	.string "the TRAINER you have just defeated.\p"
	.string "You may swap for only those POKéMON\n"
	.string "used by the beaten TRAINER.$"
	.else
	.ifdef GERMAN
	.string "Du kannst mit dem TRAINER POKéMON\n"
	.string "tauschen, den du besiegt hast.\p"
	.string "Allerdings nur die POKéMON, die dieser\n"
	.string "im Kampf eingesetzt hat. Ein genereller\l"
	.string "Tausch ist nicht möglich.$"
	.endif
	.endif

SlateportCity_BattleTentLobby_Text_ExplainSwapNumberRules:
	.ifdef ENGLISH
	.string "After every battle you win, you may\n"
	.string "swap for one of your defeated\l"
	.string "opponent's POKéMON.\p"
	.string "You will not be able to swap POKéMON\n"
	.string "with the third TRAINER in the event.$"
	.else
	.ifdef GERMAN
	.string "Nach jedem gewonnenen Kampf kannst du\n"
	.string "eines deiner POKéMON gegen das deines\l"
	.string "Gegners tauschen.\p"
	.string "Du kannst mit dem dritten TRAINER\n"
	.string "allerdings keine POKéMON tauschen.$"
	.endif
	.endif

SlateportCity_BattleTentLobby_Text_ExplainSwapNotes:
	.ifdef ENGLISH
	.string "There are two key points to be aware\n"
	.string "of when swapping POKéMON.\p"
	.string "First, when swapping, you can't check\n"
	.string "the stats of the POKéMON you are\l"
	.string "about to receive.\p"
	.string "Second, the POKéMON on your team\n"
	.string "are lined up in sequence, depending on\l"
	.string "the order in which you rented them.\p"
	.string "This sequence remains unchanged\n"
	.string "even when swaps are made.$"
	.else
	.ifdef GERMAN
	.string "Beim POKéMON-Tausch musst du auf zwei\n"
	.string "Dinge achten!\p"
	.string "Du kannst den Status des POKéMON, das\n"
	.string "du haben möchtest, vor dem Tausch\l"
	.string "nicht überprüfen.\p"
	.string "Denk daran, dass deine POKéMON in einer\n"
	.string "bestimmten Reihenfolge angeordnet\l"
	.string "sind.\p"
	.string "Diese bleibt auch nach dem Tausch\n"
	.string "unverändert.$"
	.endif
	.endif

SlateportCity_BattleTentLobby_Text_ExplainMonRules:
	.ifdef ENGLISH
	.string "The POKéMON of the SLATEPORT\n"
	.string "BATTLE TENT are all rentals.\p"
	.string "All rental POKéMON are kept at\n"
	.string "Level 30.$"
	.else
	.ifdef GERMAN
	.string "Die POKéMON im KAMPFCAMP von\n"
	.string "GRAPHITPORT sind alle Leih-POKéMON.\p"
	.string "Diese stehen auf Level 30.$"
	.endif
	.endif

@ Unused
VerdanturfTown_BattleTentLobby_Text_RulesAreListed2:
	.ifdef ENGLISH
	.string "The VERDANTURF BATTLE TENT\n"
	.string "rules are listed.$"
	.else
	.ifdef GERMAN
	.string "The VERDANTURF BATTLE TENT\n"
	.string "rules are listed.$"
	.endif
	.endif

@ Unused
VerdanturfTown_BattleTentLobby_Text_ReadWhichHeading:
	.ifdef ENGLISH
	.string "Which heading do you want to read?$"
	.else
	.ifdef GERMAN
	.string "Which heading do you want to read?$"
	.endif
	.endif

@ Unused
VerdanturfTown_BattleTentLobby_Text_ExplainBasicRules:
	.ifdef ENGLISH
	.string "Here at the VERDANTURF BATTLE TENT,\n"
	.string "POKéMON are required to think and\l"
	.string "battle by themselves.\p"
	.string "Unlike in the wild, POKéMON that live\n"
	.string "with people behave differently\l"
	.string "depending on their nature.$"
	.else
	.ifdef GERMAN
	.string "Here at the VERDANTURF BATTLE TENT,\n"
	.string "POKéMON are required to think and\l"
	.string "battle by themselves.\p"
	.string "Unlike in the wild, POKéMON that live\n"
	.string "with people behave differently\l"
	.string "depending on their nature.$"
	.endif
	.endif

@ Unused
VerdanturfTown_BattleTentLobby_Text_ExplainNatureRules:
	.ifdef ENGLISH
	.string "Depending on its nature, a POKéMON\n"
	.string "may prefer to attack no matter what.\p"
	.string "Another POKéMON may prefer to protect\n"
	.string "itself from any harm.\p"
	.string "Yet another may enjoy vexing or\n"
	.string "confounding its foes.\p"
	.string "Depending on its nature, a POKéMON\n"
	.string "will have favorite moves that it is good\l"
	.string "at using.\p"
	.string "It may also dislike certain moves that\n"
	.string "it has trouble using.$"
	.else
	.ifdef GERMAN
	.string "Depending on its nature, a POKéMON\n"
	.string "may prefer to attack no matter what.\p"
	.string "Another POKéMON may prefer to protect\n"
	.string "itself from any harm.\p"
	.string "Yet another may enjoy vexing or\n"
	.string "confounding its foes.\p"
	.string "Depending on its nature, a POKéMON\n"
	.string "will have favorite moves that it is good\l"
	.string "at using.\p"
	.string "It may also dislike certain moves that\n"
	.string "it has trouble using.$"
	.endif
	.endif

@ Unused
VerdanturfTown_BattleTentLobby_Text_ExplainMoveRules:
	.ifdef ENGLISH
	.string "There are offensive moves that inflict\n"
	.string "direct damage on the foe.\p"
	.string "There are defensive moves that are\n"
	.string "used to prepare for enemy attacks or\l"
	.string "used to heal HP and so on.\p"
	.string "There are also other somewhat-odd\n"
	.string "moves that may enfeeble the foes with\l"
	.string "stat problems including poison and \l"
	.string "paralysis.\p"
	.string "POKéMON will consider using moves in\n"
	.string "these three categories.$"
	.else
	.ifdef GERMAN
	.string "There are offensive moves that inflict\n"
	.string "direct damage on the foe.\p"
	.string "There are defensive moves that are\n"
	.string "used to prepare for enemy attacks or\l"
	.string "used to heal HP and so on.\p"
	.string "There are also other somewhat-odd\n"
	.string "moves that may enfeeble the foes with\l"
	.string "stat problems including poison and \l"
	.string "paralysis.\p"
	.string "POKéMON will consider using moves in\n"
	.string "these three categories.$"
	.endif
	.endif

@ Unused
VerdanturfTown_BattleTentLobby_Text_ExplainUnderpoweredRules:
	.ifdef ENGLISH
	.string "When not under command by its TRAINER,\n"
	.string "a POKéMON may be unable to effectively\l"
	.string "use certain moves.\p"
	.string "A POKéMON is not good at using any\n"
	.string "move that it dislikes.\p"
	.string "If a POKéMON only knows moves that\n"
	.string "do not match its nature, it will often\l"
	.string "be unable to live up to its potential.$"
	.else
	.ifdef GERMAN
	.string "When not under command by its TRAINER,\n"
	.string "a POKéMON may be unable to effectively\l"
	.string "use certain moves.\p"
	.string "A POKéMON is not good at using any\n"
	.string "move that it dislikes.\p"
	.string "If a POKéMON only knows moves that\n"
	.string "do not match its nature, it will often\l"
	.string "be unable to live up to its potential.$"
	.endif
	.endif

@ Unused
VerdanturfTown_BattleTentLobby_Text_ExplainWhenInDangerRules:
	.ifdef ENGLISH
	.string "Depending on its nature, a POKéMON may\n"
	.string "start using moves that don't match its\l"
	.string "nature when it is in trouble.\p"
	.string "If a POKéMON begins behaving oddly\n"
	.string "in a pinch, watch it carefully.$"
	.else
	.ifdef GERMAN
	.string "Depending on its nature, a POKéMON may\n"
	.string "start using moves that don’t match its\l"
	.string "nature when it is in trouble.\p"
	.string "If a POKéMON begins behaving oddly\n"
	.string "in a pinch, watch it carefully.$"
	.endif
	.endif

BattleTentLobby_Text_ExplainLevelRules:
	.ifdef ENGLISH
	.string "At this BATTLE TENT, the levels of\n"
	.string "your opponents will be adjusted to\l"
	.string "match the levels of your POKéMON.\p"
	.string "However, no TRAINER you face will\n"
	.string "have any POKéMON below Level 30.$"
	.else
	.ifdef GERMAN
	.string "In diesem KAMPFCAMP werden die Level\n"
	.string "der gegnerischen POKéMON an die Level\l"
	.string "deiner POKéMON angepasst.\p"
	.string "Trotzdem wird kein TRAINER, auf den du\n"
	.string "triffst, POKéMON unter Level 30 haben.$"
	.endif
	.endif

VerdanturfTown_BattleTentLobby_Text_RulesAreListed:
	.ifdef ENGLISH
	.string "The VERDANTURF BATTLE TENT\n"
	.string "rules are listed.$"
	.else
	.ifdef GERMAN
	.string "Die Regeln des WIESENFLUR KAMPFCAMPs\n"
	.string "hängen öffentlich aus.$"
	.endif
	.endif
