BattleDome_Text_Potential1::
	.ifdef ENGLISH
	.string "The best candidate to be a champ!$"
	.else
	.ifdef GERMAN
	.string "Der Anwärter auf den Titel des Champs!$"
	.endif
	.endif

BattleDome_Text_Potential2::
	.ifdef ENGLISH
	.string "A sure-finalist team.$"
	.else
	.ifdef GERMAN
	.string "Der sichere Finalist.$"
	.endif
	.endif

BattleDome_Text_Potential3::
	.ifdef ENGLISH
	.string "A likely top-three finisher.$"
	.else
	.ifdef GERMAN
	.string "Ein Kandidat für die ersten Drei.$"
	.endif
	.endif

BattleDome_Text_Potential4::
	.ifdef ENGLISH
	.string "A candidate to finish first.$"
	.else
	.ifdef GERMAN
	.string "Ein Kandidat, der Erster werden könnte.$"
	.endif
	.endif

BattleDome_Text_Potential5::
	.ifdef ENGLISH
	.string "A team with top-class potential.$"
	.else
	.ifdef GERMAN
	.string "Ein Team mit riesigem Potenzial.$"
	.endif
	.endif

BattleDome_Text_Potential6::
	.ifdef ENGLISH
	.string "The dark horse team this tournament.$"
	.else
	.ifdef GERMAN
	.string "Die unbekannte Größe dieses Turniers.$"
	.endif
	.endif

BattleDome_Text_Potential7::
	.ifdef ENGLISH
	.string "A better-than-average team.$"
	.else
	.ifdef GERMAN
	.string "Ein Team, besser als der Durchschnitt.$"
	.endif
	.endif

BattleDome_Text_Potential8::
	.ifdef ENGLISH
	.string "This tournament's average team.$"
	.else
	.ifdef GERMAN
	.string "Das durchschnittliche Team.$"
	.endif
	.endif

BattleDome_Text_Potential9::
	.ifdef ENGLISH
	.string "A team with average potential.$"
	.else
	.ifdef GERMAN
	.string "Team mit durchschnittlichem Potenzial.$"
	.endif
	.endif

BattleDome_Text_Potential10::
	.ifdef ENGLISH
	.string "A weaker-than-average team.$"
	.else
	.ifdef GERMAN
	.string "Schwächer als der Durchschnitt.$"
	.endif
	.endif

BattleDome_Text_Potential11::
	.ifdef ENGLISH
	.string "A team looking for its first win.$"
	.else
	.ifdef GERMAN
	.string "Team, das nach dem ersten Sieg strebt.$"
	.endif
	.endif

BattleDome_Text_Potential12::
	.ifdef ENGLISH
	.string "One win will make this team proud.$"
	.else
	.ifdef GERMAN
	.string "Ein Sieg und dieses Team wäre stolz.$"
	.endif
	.endif

BattleDome_Text_Potential13::
	.ifdef ENGLISH
	.string "Overall, a weak team.$"
	.else
	.ifdef GERMAN
	.string "Alles in allem ein schwaches Team.$"
	.endif
	.endif

BattleDome_Text_Potential14::
	.ifdef ENGLISH
	.string "A team with very low potential.$"
	.else
	.ifdef GERMAN
	.string "Team mit schwachem Potenzial.$"
	.endif
	.endif

BattleDome_Text_Potential15::
	.ifdef ENGLISH
	.string "A team unlikely to win the tournament.$"
	.else
	.ifdef GERMAN
	.string "Ein Team, das wohl nicht gewinnen wird.$"
	.endif
	.endif

BattleDome_Text_Potential16::
	.ifdef ENGLISH
	.string "The team most unlikely to win.$"
	.else
	.ifdef GERMAN
	.string "Dieses Team wird nicht gewinnen.$"
	.endif
	.endif

BattleDome_Text_PotentialDomeAceTucker::
	.ifdef ENGLISH
	.string "The perfect, invincible superstar!$"
	.else
	.ifdef GERMAN
	.string "Die perfekten, unschlagbaren Stars.$"
	.endif
	.endif

BattleDome_Text_StyleRiskDisaster::
	.ifdef ENGLISH
	.string "Willing to risk total disaster at times.$"
	.else
	.ifdef GERMAN
	.string "Hat einen Hang zur Katastrophe.$"
	.endif
	.endif

BattleDome_Text_StyleEndureLongBattles::
	.ifdef ENGLISH
	.string "Skilled at enduring long battles.$"
	.else
	.ifdef GERMAN
	.string "Hält lange Kämpfe spielend durch.$"
	.endif
	.endif

BattleDome_Text_StyleVariesTactics::
	.ifdef ENGLISH
	.string "Varies tactics to suit the opponent.$"
	.else
	.ifdef GERMAN
	.string "Passt Taktik an den Gegner an.$"
	.endif
	.endif

BattleDome_Text_StyleToughWinningPattern::
	.ifdef ENGLISH
	.string "Has a tough winning pattern.$"
	.else
	.ifdef GERMAN
	.string "Starke Form eines Gewinners erkennbar.$"
	.endif
	.endif

BattleDome_Text_StyleUsesVeryRareMove::
	.ifdef ENGLISH
	.string "Occasionally uses a very rare move.$"
	.else
	.ifdef GERMAN
	.string "Setzt manchmal seltene Attacken ein.$"
	.endif
	.endif

BattleDome_Text_StyleUsesStartlingMoves::
	.ifdef ENGLISH
	.string "Uses startling and disruptive moves.$"
	.else
	.ifdef GERMAN
	.string "Setzt verwirrende Attacken ein.$"
	.endif
	.endif

BattleDome_Text_StyleConstantlyWatchesHP::
	.ifdef ENGLISH
	.string "Constantly watches HP in battle.$"
	.else
	.ifdef GERMAN
	.string "Behält im Kampf ständig KP im Auge.$"
	.endif
	.endif

BattleDome_Text_StyleStoresAndLoosesPower::
	.ifdef ENGLISH
	.string "Good at storing then loosing power.$"
	.else
	.ifdef GERMAN
	.string "Gut im Bewahren von Kraft.$"
	.endif
	.endif

BattleDome_Text_StyleEnfeeblesFoes::
	.ifdef ENGLISH
	.string "Skilled at enfeebling foes.$"
	.else
	.ifdef GERMAN
	.string "Gut im Schwächen von Gegnern.$"
	.endif
	.endif

BattleDome_Text_StylePrefersLuckTactics::
	.ifdef ENGLISH
	.string "Prefers tactics that rely on luck.$"
	.else
	.ifdef GERMAN
	.string "Verlässt sich auf das Glück.$"
	.endif
	.endif

BattleDome_Text_StyleRegalAtmosphere::
	.ifdef ENGLISH
	.string "Attacks with a regal atmosphere.$"
	.else
	.ifdef GERMAN
	.string "Greift hoheitsvoll an.$"
	.endif
	.endif

BattleDome_Text_StylePowerfulLowPPMoves::
	.ifdef ENGLISH
	.string "Attacks with powerful, low-PP moves.$"
	.else
	.ifdef GERMAN
	.string "Liebt starke, AP-schwache Attacken.$"
	.endif
	.endif

BattleDome_Text_StyleEnfeebleThenAttack::
	.ifdef ENGLISH
	.string "Skilled at enfeebling, then attacking.$"
	.else
	.ifdef GERMAN
	.string "Schwächt und greift dann an.$"
	.endif
	.endif

BattleDome_Text_StyleBattlesWhileEnduring::
	.ifdef ENGLISH
	.string "Battles while enduring all attacks.$"
	.else
	.ifdef GERMAN
	.string "Erträgt kämpfend alle Angriffe.$"
	.endif
	.endif

BattleDome_Text_StyleUpsetsFoesEmotionally::
	.ifdef ENGLISH
	.string "Skilled at upsetting foes emotionally.$"
	.else
	.ifdef GERMAN
	.string "Verwirrt den Gegner emotional.$"
	.endif
	.endif

BattleDome_Text_StyleStrongAndStraightforward::
	.ifdef ENGLISH
	.string "Uses strong and straightforward moves.$"
	.else
	.ifdef GERMAN
	.string "Setzt starke, forsche Attacken ein.$"
	.endif
	.endif

BattleDome_Text_StyleAggressivelyStrongMoves::
	.ifdef ENGLISH
	.string "Aggressively uses strong moves.$"
	.else
	.ifdef GERMAN
	.string "Setzt aggressive, starke Attacken ein.$"
	.endif
	.endif

BattleDome_Text_StyleCleverlyDodgesAttacks::
	.ifdef ENGLISH
	.string "Battles while cleverly dodging attacks.$"
	.else
	.ifdef GERMAN
	.string "Kämpft und duckt sich dabei clever.$"
	.endif
	.endif

BattleDome_Text_StyleUsesUpsettingMoves::
	.ifdef ENGLISH
	.string "Skilled at using upsetting attacks.$"
	.else
	.ifdef GERMAN
	.string "Seine Attacken verärgern den Gegner.$"
	.endif
	.endif

BattleDome_Text_StyleUsesPopularMoves::
	.ifdef ENGLISH
	.string "Uses many popular moves.$"
	.else
	.ifdef GERMAN
	.string "Setzt viele gängige Attacken ein.$"
	.endif
	.endif

BattleDome_Text_StyleHasPowerfulComboMoves::
	.ifdef ENGLISH
	.string "Has moves for powerful combinations.$"
	.else
	.ifdef GERMAN
	.string "Setzt starke Attacken-Combos ein.$"
	.endif
	.endif

BattleDome_Text_StyleUsesHighProbabilityMoves::
	.ifdef ENGLISH
	.string "Uses high-probability attacks.$"
	.else
	.ifdef GERMAN
	.string "Attacken mit hoher Trefferquote.$"
	.endif
	.endif

BattleDome_Text_StyleAggressivelySpectacularMoves::
	.ifdef ENGLISH
	.string "Aggressively uses spectacular moves.$"
	.else
	.ifdef GERMAN
	.string "Setzt kühn spektakuläre Attacken ein.$"
	.endif
	.endif

BattleDome_Text_StyleEmphasizesOffenseOverDefense::
	.ifdef ENGLISH
	.string "Emphasizes offense over defense.$"
	.else
	.ifdef GERMAN
	.string "Setzt auf Offensive statt Defensive.$"
	.endif
	.endif

BattleDome_Text_StyleEmphasizesDefenseOverOffense::
	.ifdef ENGLISH
	.string "Emphasizes defense over offense.$"
	.else
	.ifdef GERMAN
	.string "Setzt auf Defensive statt Offensive.$"
	.endif
	.endif

BattleDome_Text_StyleAttacksQuicklyStrongMoves::
	.ifdef ENGLISH
	.string "Attacks quickly with strong moves.$"
	.else
	.ifdef GERMAN
	.string "Schneller Angriff mit starken Attacken.$"
	.endif
	.endif

BattleDome_Text_StyleUsesAddedEffectMoves::
	.ifdef ENGLISH
	.string "Often uses moves with added effects.$"
	.else
	.ifdef GERMAN
	.string "Attacken mit zusätzlicher Wirkung.$"
	.endif
	.endif

BattleDome_Text_StyleUsesBalancedMixOfMoves::
	.ifdef ENGLISH
	.string "Uses a well-balanced mix of moves.$"
	.else
	.ifdef GERMAN
	.string "Gut ausbalancierter Mix von Attacken.$"
	.endif
	.endif

BattleDome_Text_StyleSampleMessage1::
	.ifdef ENGLISH
	.string "This is sample message 1.$"
	.else
	.ifdef GERMAN
	.string "Dies ist Beispiel 1.$"
	.endif
	.endif

BattleDome_Text_StyleSampleMessage2::
	.ifdef ENGLISH
	.string "This is sample message 2.$"
	.else
	.ifdef GERMAN
	.string "Dies ist Beispiel 2.$"
	.endif
	.endif

BattleDome_Text_StyleSampleMessage3::
	.ifdef ENGLISH
	.string "This is sample message 3.$"
	.else
	.ifdef GERMAN
	.string "Dies ist Beispiel 3.$"
	.endif
	.endif

BattleDome_Text_StyleSampleMessage4::
	.ifdef ENGLISH
	.string "This is sample message 4.$"
	.else
	.ifdef GERMAN
	.string "Dies ist Beispiel 4.$"
	.endif
	.endif

BattleDome_Text_EmphasizesHPAndAtk::
	.ifdef ENGLISH
	.string "Emphasizes HP and ATTACK.$"
	.else
	.ifdef GERMAN
	.string "Legt Wert auf KP und ANGRIFF.$"
	.endif
	.endif

BattleDome_Text_EmphasizesHPAndDef::
	.ifdef ENGLISH
	.string "Emphasizes HP and DEFENSE.$"
	.else
	.ifdef GERMAN
	.string "Legt Wert auf KP und VERTEIDIGUNG.$"
	.endif
	.endif

BattleDome_Text_EmphasizesHPAndSpeed::
	.ifdef ENGLISH
	.string "Emphasizes HP and SPEED.$"
	.else
	.ifdef GERMAN
	.string "Legt Wert auf KP und INITIATIVE.$"
	.endif
	.endif

BattleDome_Text_EmphasizesHPAndSpAtk::
	.ifdef ENGLISH
	.string "Emphasizes HP and SP. ATTACK.$"
	.else
	.ifdef GERMAN
	.string "Legt Wert auf KP und SP. ANGR.$"
	.endif
	.endif

BattleDome_Text_EmphasizesHPAndSpDef::
	.ifdef ENGLISH
	.string "Emphasizes HP and SP. DEFENSE.$"
	.else
	.ifdef GERMAN
	.string "Legt Wert auf KP und SP. VERT.$"
	.endif
	.endif

BattleDome_Text_EmphasizesAtkAndDef::
	.ifdef ENGLISH
	.string "Emphasizes ATTACK and DEFENSE.$"
	.else
	.ifdef GERMAN
	.string "Legt Wert auf ANGRIFF und VERT.$"
	.endif
	.endif

BattleDome_Text_EmphasizesAtkAndSpeed::
	.ifdef ENGLISH
	.string "Emphasizes ATTACK and SPEED.$"
	.else
	.ifdef GERMAN
	.string "Legt Wert auf ANGRIFF und INITIATIVE.$"
	.endif
	.endif

BattleDome_Text_EmphasizesAtkAndSpAtk::
	.ifdef ENGLISH
	.string "Emphasizes ATTACK and SP. ATTACK.$"
	.else
	.ifdef GERMAN
	.string "Legt Wert auf ANGRIFF und SP. ANGR.$"
	.endif
	.endif

BattleDome_Text_EmphasizesAtkAndSpDef::
	.ifdef ENGLISH
	.string "Emphasizes ATTACK and SP. DEFENSE.$"
	.else
	.ifdef GERMAN
	.string "Legt Wert auf ANGRIFF und SP. VERT.$"
	.endif
	.endif

BattleDome_Text_EmphasizesDefAndSpeed::
	.ifdef ENGLISH
	.string "Emphasizes DEFENSE and SPEED.$"
	.else
	.ifdef GERMAN
	.string "Legt Wert auf VERT. und INIT.$"
	.endif
	.endif

BattleDome_Text_EmphasizesDefAndSpAtk::
	.ifdef ENGLISH
	.string "Emphasizes DEFENSE and SP. ATTACK.$"
	.else
	.ifdef GERMAN
	.string "Legt Wert auf VERT. und SP. ANGR.$"
	.endif
	.endif

BattleDome_Text_EmphasizesDefAndSpDef::
	.ifdef ENGLISH
	.string "Emphasizes DEFENSE and SP. DEFENSE.$"
	.else
	.ifdef GERMAN
	.string "Legt Wert auf VERT. und SP. VERT.$"
	.endif
	.endif

BattleDome_Text_EmphasizesSpeedAndSpAtk::
	.ifdef ENGLISH
	.string "Emphasizes SPEED and SP. ATTACK.$"
	.else
	.ifdef GERMAN
	.string "Legt Wert auf INIT. und SP. ANGR.$"
	.endif
	.endif

BattleDome_Text_EmphasizesSpeedAndSpDef::
	.ifdef ENGLISH
	.string "Emphasizes SPEED and SP. DEFENSE.$"
	.else
	.ifdef GERMAN
	.string "Legt Wert auf INIT. und SP. VERT.$"
	.endif
	.endif

BattleDome_Text_EmphasizesSpAtkAndSpDef::
	.ifdef ENGLISH
	.string "Emphasizes SP. ATTACK and SP. DEFENSE.$"
	.else
	.ifdef GERMAN
	.string "Legt Wert auf SP. ANGR. u. SP. VERT.$"
	.endif
	.endif

BattleDome_Text_EmphasizesHP::
	.ifdef ENGLISH
	.string "Emphasizes HP.$"
	.else
	.ifdef GERMAN
	.string "Legt Wert auf KP.$"
	.endif
	.endif

BattleDome_Text_EmphasizesAtk::
	.ifdef ENGLISH
	.string "Emphasizes ATTACK.$"
	.else
	.ifdef GERMAN
	.string "Legt Wert auf ANGRIFF.$"
	.endif
	.endif

BattleDome_Text_EmphasizesDef::
	.ifdef ENGLISH
	.string "Emphasizes DEFENSE.$"
	.else
	.ifdef GERMAN
	.string "Legt Wert auf VERTEIDIGUNG.$"
	.endif
	.endif

BattleDome_Text_EmphasizesSpeed::
	.ifdef ENGLISH
	.string "Emphasizes SPEED.$"
	.else
	.ifdef GERMAN
	.string "Legt Wert auf INITIATIVE.$"
	.endif
	.endif

BattleDome_Text_EmphasizesSpAtk::
	.ifdef ENGLISH
	.string "Emphasizes SP. ATTACK.$"
	.else
	.ifdef GERMAN
	.string "Legt Wert auf SP. ANGRIFF.$"
	.endif
	.endif

BattleDome_Text_EmphasizesSpDef::
	.ifdef ENGLISH
	.string "Emphasizes SP. DEFENSE.$"
	.else
	.ifdef GERMAN
	.string "Legt Wert auf SP. VERTEIDIGUNG.$"
	.endif
	.endif

BattleDome_Text_NeglectsHPAndAtk::
	.ifdef ENGLISH
	.string "Neglects HP and ATTACK.$"
	.else
	.ifdef GERMAN
	.string "Vernachlässigt KP und ANGRIFF.$"
	.endif
	.endif

BattleDome_Text_NeglectsHPAndDef::
	.ifdef ENGLISH
	.string "Neglects HP and DEFENSE.$"
	.else
	.ifdef GERMAN
	.string "Vernachlässigt KP und VERTEIDIGUNG.$"
	.endif
	.endif

BattleDome_Text_NeglectsHPAndSpeed::
	.ifdef ENGLISH
	.string "Neglects HP and SPEED.$"
	.else
	.ifdef GERMAN
	.string "Vernachlässigt KP und INITIATIVE.$"
	.endif
	.endif

BattleDome_Text_NeglectsHPAndSpAtk::
	.ifdef ENGLISH
	.string "Neglects HP and SP. ATTACK.$"
	.else
	.ifdef GERMAN
	.string "Vernachlässigt KP und SP. ANGRIFF.$"
	.endif
	.endif

BattleDome_Text_NeglectsHPAndSpDef::
	.ifdef ENGLISH
	.string "Neglects HP and SP. DEFENSE.$"
	.else
	.ifdef GERMAN
	.string "Vernachlässigt KP und SP. VERT.$"
	.endif
	.endif

BattleDome_Text_NeglectsAtkAndDef::
	.ifdef ENGLISH
	.string "Neglects ATTACK and DEFENSE.$"
	.else
	.ifdef GERMAN
	.string "Vernachlässigt ANGR. und VERT.$"
	.endif
	.endif

BattleDome_Text_NeglectsAtkAndSpeed::
	.ifdef ENGLISH
	.string "Neglects ATTACK and SPEED.$"
	.else
	.ifdef GERMAN
	.string "Vernachlässigt ANGR. und INIT.$"
	.endif
	.endif

BattleDome_Text_NeglectsAtkAndSpAtk::
	.ifdef ENGLISH
	.string "Neglects ATTACK and SP. ATTACK.$"
	.else
	.ifdef GERMAN
	.string "Vernachlässigt ANGR. und SP. ANGR.$"
	.endif
	.endif

BattleDome_Text_NeglectsAtkAndSpDef::
	.ifdef ENGLISH
	.string "Neglects ATTACK and SP. DEFENSE.$"
	.else
	.ifdef GERMAN
	.string "Vernachlässigt ANGR. und SP. VERT.$"
	.endif
	.endif

BattleDome_Text_NeglectsDefAndSpeed::
	.ifdef ENGLISH
	.string "Neglects DEFENSE and SPEED.$"
	.else
	.ifdef GERMAN
	.string "Vernachlässigt VERT. und INIT.$"
	.endif
	.endif

BattleDome_Text_NeglectsDefAndSpAtk::
	.ifdef ENGLISH
	.string "Neglects DEFENSE and SP. ATTACK.$"
	.else
	.ifdef GERMAN
	.string "Vernachlässigt VERT. und SP. ANGR.$"
	.endif
	.endif

BattleDome_Text_NeglectsDefAndSpDef::
	.ifdef ENGLISH
	.string "Neglects DEFENSE and SP. DEFENSE.$"
	.else
	.ifdef GERMAN
	.string "Vernachlässigt VERT. und SP. VERT.$"
	.endif
	.endif

BattleDome_Text_NeglectsSpeedAndSpAtk::
	.ifdef ENGLISH
	.string "Neglects SPEED and SP. ATTACK.$"
	.else
	.ifdef GERMAN
	.string "Vernachlässigt INIT. und SP. ANGR.$"
	.endif
	.endif

BattleDome_Text_NeglectsSpeedAndSpDef::
	.ifdef ENGLISH
	.string "Neglects SPEED and SP. DEFENSE.$"
	.else
	.ifdef GERMAN
	.string "Vernachlässigt INIT. und SP. VERT.$"
	.endif
	.endif

BattleDome_Text_NeglectsSpAtkAndSpDef::
	.ifdef ENGLISH
	.string "Neglects SP. ATTACK and SP. DEFENSE.$"
	.else
	.ifdef GERMAN
	.string "Vernachlässigt SP. ANGR. und SP. VERT.$"
	.endif
	.endif

BattleDome_Text_NeglectsHP::
	.ifdef ENGLISH
	.string "Neglects HP.$"
	.else
	.ifdef GERMAN
	.string "Vernachlässigt KP.$"
	.endif
	.endif

BattleDome_Text_NeglectsAtk::
	.ifdef ENGLISH
	.string "Neglects ATTACK.$"
	.else
	.ifdef GERMAN
	.string "Vernachlässigt ANGRIFF.$"
	.endif
	.endif

BattleDome_Text_NeglectsDef::
	.ifdef ENGLISH
	.string "Neglects DEFENSE.$"
	.else
	.ifdef GERMAN
	.string "Vernachlässigt VERTEIDIGUNG.$"
	.endif
	.endif

BattleDome_Text_NeglectsSpeed::
	.ifdef ENGLISH
	.string "Neglects SPEED.$"
	.else
	.ifdef GERMAN
	.string "Vernachlässigt INITIATIVE.$"
	.endif
	.endif

BattleDome_Text_NeglectsSpAtk::
	.ifdef ENGLISH
	.string "Neglects SP. ATTACK.$"
	.else
	.ifdef GERMAN
	.string "Vernachlässigt SPEZ. ANGRIFF.$"
	.endif
	.endif

BattleDome_Text_NeglectsSpDef::
	.ifdef ENGLISH
	.string "Neglects SP. DEFENSE.$"
	.else
	.ifdef GERMAN
	.string "Vernachlässigt SPEZ. VERTEIDIGUNG.$"
	.endif
	.endif

BattleDome_Text_RaisesMonsWellBalanced::
	.ifdef ENGLISH
	.string "Raises POKéMON in a well-balanced way.$"
	.else
	.ifdef GERMAN
	.string "Zieht POKéMON ausgewogen auf.$"
	.endif
	.endif

BattleDome_Text_LetTheBattleBegin::
	.ifdef ENGLISH
	.string "Let the battle begin!$"
	.else
	.ifdef GERMAN
	.string "Lasst den Kampf beginnen!$"
	.endif
	.endif

BattleDome_Text_TrainerWonUsingMove::
	.ifdef ENGLISH
	.string "{STR_VAR_1} won using {STR_VAR_2}!$"
	.else
	.ifdef GERMAN
	.string "{STR_VAR_1} gewinnt mit {STR_VAR_2}!$"
	.endif
	.endif

BattleDome_Text_TrainerBecameChamp::
	.ifdef ENGLISH
	.string "{STR_VAR_1} became the champ!$"
	.else
	.ifdef GERMAN
	.string "{STR_VAR_1} wird der Champ!$"
	.endif
	.endif

BattleDome_Text_TrainerWonByDefault::
	.ifdef ENGLISH
	.string "{STR_VAR_1} won by default!$"
	.else
	.ifdef GERMAN
	.string "{STR_VAR_1} gewinnt durch Aufgabe!$"
	.endif
	.endif

BattleDome_Text_TrainerWonOutrightByDefault::
	.ifdef ENGLISH
	.string "{STR_VAR_1} won outright by default!$"
	.else
	.ifdef GERMAN
	.string "{STR_VAR_1} gewinnt durch Aufgabe!$"
	.endif
	.endif

BattleDome_Text_TrainerWonNoMoves::
	.ifdef ENGLISH
	.string "{STR_VAR_1} won without using a move!$"
	.else
	.ifdef GERMAN
	.string "{STR_VAR_1} gewinnt ohne anzugreifen!$"
	.endif
	.endif

BattleDome_Text_TrainerWonOutrightNoMoves::
	.ifdef ENGLISH
	.string "{STR_VAR_1} won outright with no moves!$"
	.else
	.ifdef GERMAN
	.string "{STR_VAR_1} gewinnt ohne anzugreifen!$"
	.endif
	.endif

BattleDome_Text_Round1Match1::
	.ifdef ENGLISH
	.string "Round 1, Match 1$"
	.else
	.ifdef GERMAN
	.string "Runde 1, Kampf 1$"
	.endif
	.endif

BattleDome_Text_Round1Match2::
	.ifdef ENGLISH
	.string "Round 1, Match 2$"
	.else
	.ifdef GERMAN
	.string "Runde 1, Kampf 2$"
	.endif
	.endif

BattleDome_Text_Round1Match3::
	.ifdef ENGLISH
	.string "Round 1, Match 3$"
	.else
	.ifdef GERMAN
	.string "Runde 1, Kampf 3$"
	.endif
	.endif

BattleDome_Text_Round1Match4::
	.ifdef ENGLISH
	.string "Round 1, Match 4$"
	.else
	.ifdef GERMAN
	.string "Runde 1, Kampf 4$"
	.endif
	.endif

BattleDome_Text_Round1Match5::
	.ifdef ENGLISH
	.string "Round 1, Match 5$"
	.else
	.ifdef GERMAN
	.string "Runde 1, Kampf 5$"
	.endif
	.endif

BattleDome_Text_Round1Match6::
	.ifdef ENGLISH
	.string "Round 1, Match 6$"
	.else
	.ifdef GERMAN
	.string "Runde 1, Kampf 6$"
	.endif
	.endif

BattleDome_Text_Round1Match7::
	.ifdef ENGLISH
	.string "Round 1, Match 7$"
	.else
	.ifdef GERMAN
	.string "Runde 1, Kampf 7$"
	.endif
	.endif

BattleDome_Text_Round1Match8::
	.ifdef ENGLISH
	.string "Round 1, Match 8$"
	.else
	.ifdef GERMAN
	.string "Runde 1, Kampf 8$"
	.endif
	.endif

BattleDome_Text_Round2Match1::
	.ifdef ENGLISH
	.string "Round 2, Match 1$"
	.else
	.ifdef GERMAN
	.string "Runde 2, Kampf 1$"
	.endif
	.endif

BattleDome_Text_Round2Match2::
	.ifdef ENGLISH
	.string "Round 2, Match 2$"
	.else
	.ifdef GERMAN
	.string "Runde 2, Kampf 2$"
	.endif
	.endif

BattleDome_Text_Round2Match3::
	.ifdef ENGLISH
	.string "Round 2, Match 3$"
	.else
	.ifdef GERMAN
	.string "Runde 2, Kampf 3$"
	.endif
	.endif

BattleDome_Text_Round2Match4::
	.ifdef ENGLISH
	.string "Round 2, Match 4$"
	.else
	.ifdef GERMAN
	.string "Runde 2, Kampf 4$"
	.endif
	.endif

BattleDome_Text_SemifinalMatch1::
	.ifdef ENGLISH
	.string "Semifinal Match 1$"
	.else
	.ifdef GERMAN
	.string "Halbfinale Kampf 1$"
	.endif
	.endif

BattleDome_Text_SemifinalMatch2::
	.ifdef ENGLISH
	.string "Semifinal Match 2$"
	.else
	.ifdef GERMAN
	.string "Halbfinale Kampf 2$"
	.endif
	.endif

BattleDome_Text_FinalMatch::
	.ifdef ENGLISH
	.string "Final Match$"
	.else
	.ifdef GERMAN
	.string "Finale$"
	.endif
	.endif
