PetalburgCity_Gym_Text_GiveEnigmaBerry:
	.ifdef ENGLISH
	.string "DAD: Hi, {PLAYER}!\p"
	.string "I just received a very rare BERRY.\n"
	.string "I'd like you to have it.$"
	.else
	.ifdef GERMAN
	.string "VATER: Hallo, {PLAYER}!\p"
	.string "Ich habe gerade eine sehr seltene\n"
	.string "BEERE erhalten. Die schenke ich dir.$"
	.endif
	.endif

Route104_Text_PlantBerriesInSoilTakeThis:
	.ifdef ENGLISH
	.string "If you see BERRIES growing in loamy\n"
	.string "soil, feel free to take them.\p"
	.string "But make sure you plant a BERRY in the\n"
	.string "same spot. That's common courtesy.\p"
	.string "Here, I'll share this with you.$"
	.else
	.ifdef GERMAN
	.string "Wenn du BEEREn siehst, die im Lehmboden\n"
	.string "wachsen, pflücke sie ruhig.\p"
	.string "Aber pflanze eine neue BEERE an der\n"
	.string "Stelle. Das ist einfache Höflichkeit.\p"
	.string "Hier, das ist für dich.$"
	.endif
	.endif

Route104_Text_TrainersOftenMakeMonHoldBerries:
	.ifdef ENGLISH
	.string "The way you look, you must be a\n"
	.string "TRAINER, no?\p"
	.string "TRAINERS often make POKéMON hold\n"
	.string "BERRIES.\p"
	.string "It's up to you whether to grow BERRIES\n"
	.string "or use them.$"
	.else
	.ifdef GERMAN
	.string "Du siehst aus wie ein TRAINER. Du\n"
	.string "bist auch einer, stimmt’s?\p"
	.string "TRAINER geben ihren POKéMON manchmal\n"
	.string "BEEREn zu tragen.\p"
	.string "Es liegt an dir, ob du BEEREn pflanzt\n"
	.string "oder verwendest.$"
	.endif
	.endif

Route111_Text_WateredPlantsEveryDayTakeBerry:
	.ifdef ENGLISH
	.string "I watered the plants every day.\n"
	.string "They grew lots of flowers.\p"
	.string "And they gave me lots of BERRIES, too.\p"
	.string "Here you go!\n"
	.string "You can have it!$"
	.else
	.ifdef GERMAN
	.string "Ich gieße die Pflanzen jeden Tag.\n"
	.string "Dann bekommen sie viele Blüten.\p"
	.string "Und daraus werden dann viele BEEREn.\p"
	.string "Hier, die ist für dich.\n"
	.string "Du kannst sie haben.$"
	.endif
	.endif

Route111_Text_GoingToTryToMakeDifferentColorBerries:
	.ifdef ENGLISH
	.string "I'm going to try really hard and make\n"
	.string "BERRIES in different colors.\p"
	.string "I hope you try hard, too!$"
	.else
	.ifdef GERMAN
	.string "Ich werde mich anstrengen und einige\n"
	.string "BEEREn in verschiedenen Farben\l"
	.string "züchten!\p"
	.string "Ich hoffe, du strengst dich auch an.$"
	.endif
	.endif

Route111_Text_WhatColorBerriesToLookForToday:
	.ifdef ENGLISH
	.string "I wonder what color BERRIES I'll look\n"
	.string "for today?$"
	.else
	.ifdef GERMAN
	.string "Ich frage mich, welche BEEREn-Farbe ich\n"
	.string "heute wählen soll.$"
	.endif
	.endif

Route114_Text_LoveUsingBerryCrushShareBerry:
	.ifdef ENGLISH
	.string "I love using the BERRY CRUSH machine,\n"
	.string "so I'm collecting BERRIES.\p"
	.string "I'll share one with you, if you'd like.$"
	.else
	.ifdef GERMAN
	.string "Ich liebe die BEERENMÜHLE, daher sammle\n"
	.string "ich alle BEEREn, die ich finde.\p"
	.string "Ich schenk dir eine, wenn du magst.$"
	.endif
	.endif

Route114_Text_TryBerryCrushWithFriends:
	.ifdef ENGLISH
	.string "You should try the BERRY CRUSH\n"
	.string "machine with your friends.$"
	.else
	.ifdef GERMAN
	.string "Du solltest die BEERENMÜHLE unbedingt\n"
	.string "zusammen mit deinen Freunden\l"
	.string "ausprobieren.$"
	.endif
	.endif

Route114_Text_FunToThinkAboutBerries:
	.ifdef ENGLISH
	.string "Which BERRY should be planted?\n"
	.string "Should you use or hoard BERRIES?\p"
	.string "It's fun to think about.$"
	.else
	.ifdef GERMAN
	.string "Welche BEERE sollte man pflanzen?\n"
	.string "Sollte man BEEREn einsetzen oder\l"
	.string "sammeln?\p"
	.string "Es macht Spaß, darüber nachzudenken.$"
	.endif
	.endif

Route120_Text_BerriesExpressionOfLoveIsntIt:
	.ifdef ENGLISH
	.string "BERRIES grow by soaking up sunlight.\p"
	.string "We help the BERRIES grow by watering\n"
	.string "them regularly.\p"
	.string "It's an expression of love, isn't it?$"
	.else
	.ifdef GERMAN
	.string "BEEREn gedeihen im Sonnenlicht, das\n"
	.string "sie aufnehmen.\p"
	.string "Und ich versorge sie regelmäßig mit\n"
	.string "Wasser.\p"
	.string "Es ist ein Ausdruck der Liebe, richtig?$"
	.endif
	.endif

Route120_Text_YesYouUnderstand:
	.ifdef ENGLISH
	.string "Yes, yes.\n"
	.string "You understand what I mean.\p"
	.string "You should take this.$"
	.else
	.ifdef GERMAN
	.string "Ja, ja.\n"
	.string "Du verstehst, was ich meine.\p"
	.string "Das hier ist für dich.$"
	.endif
	.endif

Route120_Text_MakeYourOwnImpressions:
	.ifdef ENGLISH
	.string "Oh… But it is important to make your\n"
	.string "own impressions, I guess…\p"
	.string "You can have this.$"
	.else
	.ifdef GERMAN
	.string "Oh… Aber es ist wichtig, dass man sich\n"
	.string "einen eigenen Eindruck verschafft…\p"
	.string "Hier. Das kannst du haben.$"
	.endif
	.endif

Route120_Text_BerryIsRareRaiseItWithCare:
	.ifdef ENGLISH
	.string "I think that BERRY is rare.\n"
	.string "I hope you raise it with loving care.$"
	.else
	.ifdef GERMAN
	.string "Dies ist eine seltene BEERE. Ich hoffe,\n"
	.string "du gehst sorgfältig mit ihr um.$"
	.endif
	.endif

Route120_Text_IllGetMoreBerriesFromBerryMaster:
	.ifdef ENGLISH
	.string "I'll get more BERRIES from\n"
	.string "the BERRY MASTER.$"
	.else
	.ifdef GERMAN
	.string "Ich habe einige BEEREn vom\n"
	.string "BEERENMEISTER erhalten.$"
	.endif
	.endif

LilycoveCity_Text_BerrySuitsYou:
	.ifdef ENGLISH
	.string "When it gets right down to it…\p"
	.string "The same way suits suit me perfectly,\n"
	.string "a crisp breeze suits the sea.\p"
	.string "And you, a BERRY suits you to a “T”…\p"
	.string "Why should that be so?$"
	.else
	.ifdef GERMAN
	.string "Also, im Grunde ist es so…\p"
	.string "Ein Anzug passt zu mir wie die\n"
	.string "Brise zum Meer - perfekt!\p"
	.string "Und bei dir… Eine BEERE passt zu\n"
	.string "“T”…\p"
	.string "Warum ist das so?$"
	.endif
	.endif

LilycoveCity_Text_BecauseYoureTrainer:
	.ifdef ENGLISH
	.string "When it gets right down to it…\p"
	.string "It's because you're a TRAINER!$"
	.else
	.ifdef GERMAN
	.string "Also, im Grunde ist es so…\p"
	.string "Weil du ein TRAINER bist.$"
	.endif
	.endif

LilycoveCity_Text_PokeblocksSuitPokemon:
	.ifdef ENGLISH
	.string "When it gets right down to it…\p"
	.string "The way dignified simplicity suits me,\n"
	.string "{POKEBLOCK}S perfectly suit POKéMON.$"
	.else
	.ifdef GERMAN
	.string "Grundsätzlich verhält es sich so…\p"
	.string "So, wie die würdevolle Einfachheit mich\n"
	.string "ziert, zieren {POKEBLOCK} POKéMON.$"
	.endif
	.endif

Route123_BerryMastersHouse_Text_YoureDeservingOfBerry:
	.ifdef ENGLISH
	.string "You may call me the BERRY MASTER.\p"
	.string "I dream of filling the world with\n"
	.string "beautiful flowers, so I raise BERRIES\l"
	.string "and hand them out to everyone.\p"
	.string "You're deserving of one!$"
	.else
	.ifdef GERMAN
	.string "Du kannst mich BEERENMEISTER\n"
	.string "nennen.\p"
	.string "Ich träume davon, die Welt mit hübschen\n"
	.string "Blumen zu bereichern, daher züchte ich\l"
	.string "BEEREn und gebe sie an andere weiter.\p"
	.string "Du hast dir auch eine verdient!$"
	.endif
	.endif

Route123_BerryMastersHouse_Text_WhyBeStingyTakeAnother:
	.ifdef ENGLISH
	.string "Why be stingy?\n"
	.string "Take another!$"
	.else
	.ifdef GERMAN
	.string "Sei nicht so schüchtern.\n"
	.string "Nimm dir noch eine!$"
	.endif
	.endif

Route123_BerryMastersHouse_Text_VisitPrettyPetalFlowerShop:
	.ifdef ENGLISH
	.string "Be sure to visit the PRETTY PETAL\n"
	.string "flower shop near RUSTBORO.\p"
	.string "Let flowers fill the world!$"
	.else
	.ifdef GERMAN
	.string "Besuch unbedingt den BLÜTENTRAUM\n"
	.string "BLUMENLADEN bei METAROST CITY.\p"
	.string "Lasst die Welt in Blumen schwelgen.$"
	.endif
	.endif

Route123_BerryMastersHouse_Text_DoneForToday:
	.ifdef ENGLISH
	.string "I'm done for today.\n"
	.string "Come again another day.\p"
	.string "Let flowers fill the world!$"
	.else
	.ifdef GERMAN
	.string "Für heute bin ich fertig.\n"
	.string "Komm ein anderes Mal wieder.\p"
	.string "Lasst die Welt in Blumen schwelgen!$"
	.endif
	.endif

Route123_BerryMastersHouse_Text_HeardAGoodSayingLately:
	.ifdef ENGLISH
	.string "The way my husband grows BERRIES,\n"
	.string "oh, he's the best in the world.\p"
	.string "He makes me proud, that he does.\p"
	.string "Incidentally, child, have you heard\n"
	.string "a good saying lately?$"
	.else
	.ifdef GERMAN
	.string "Mein Mann züchtet BEEREn. Er ist be-\n"
	.string "stimmt der beste Züchter der Welt.\p"
	.string "Er macht mich unglaublich stolz.\p"
	.string "Sag mal, Kind, du kennst nicht zufällig\n"
	.string "einen guten Spruch?$"
	.endif
	.endif

Route123_BerryMastersHouse_Text_InspirationalTakeThis:
	.ifdef ENGLISH
	.string "Ah! What a remarkable saying!\n"
	.string "Inspirational, it is!\p"
	.string "I want you to have this.$"
	.else
	.ifdef GERMAN
	.string "Ah! Was für ein wunderbarer Spruch!\n"
	.string "So inspirierend!\p"
	.string "Das hier möchte ich dir schenken.$"
	.endif
	.endif

Route123_BerryMastersHouse_Text_GoodSayingTakeThis:
	.ifdef ENGLISH
	.string "Oh! A good saying it is.\n"
	.string "You're quite remarkable.\p"
	.string "I want you to have this.$"
	.else
	.ifdef GERMAN
	.string "Oh! Das ist ein guter Spruch!\n"
	.string "Du bist bemerkenswert!\p"
	.string "Das hier möchte ich dir schenken.$"
	.endif
	.endif

Route123_BerryMastersHouse_Text_JoyNeverGoesOutOfMyLife:
	.ifdef ENGLISH
	.string "Our four grandchildren should become\n"
	.string "more accomplished than my husband.\p"
	.string "Joy never goes out of my life!$"
	.else
	.ifdef GERMAN
	.string "Unsere vier Enkelkinder sollen noch\n"
	.string "begabter als mein Mann werden.\p"
	.string "Das Leben erfüllt einen immer wieder mit\n"
	.string "Freude!$"
	.endif
	.endif

Route123_BerryMastersHouse_Text_Ah:
	.ifdef ENGLISH
	.string "Ah…$"
	.else
	.ifdef GERMAN
	.string "Ah…$"
	.endif
	.endif

Route104_PrettyPetalFlowerShop_Text_ThisIsPrettyPetalFlowerShop:
	.ifdef ENGLISH
	.string "Hello!\p"
	.string "This is the PRETTY PETAL flower shop.\n"
	.string "Spreading flowers all over the world!$"
	.else
	.ifdef GERMAN
	.string "Hallo!\p"
	.string "Dies ist der BLÜTENTRAUM BLUMENLADEN.\n"
	.string "Verwandelt die Welt in ein Blumenmeer!$"
	.endif
	.endif

Route104_PrettyPetalFlowerShop_Text_LearnAboutBerries:
	.ifdef ENGLISH
	.string "{PLAYER}{KUN}, would you like to learn about\n"
	.string "BERRIES?$"
	.else
	.ifdef GERMAN
	.string "{PLAYER}{KUN}, möchtest du etwas über\n"
	.string "BEEREn lernen?$"
	.endif
	.endif

Route104_PrettyPetalFlowerShop_Text_IntroLearnAboutBerries:
	.ifdef ENGLISH
	.string "Your name is?\p"
	.string "{PLAYER}{KUN}.\n"
	.string "That's a nice name.\p"
	.string "{PLAYER}{KUN}, would you like to learn about\n"
	.string "BERRIES?$"
	.else
	.ifdef GERMAN
	.string "Wie heißt du?\p"
	.string "{PLAYER}{KUN}.\n"
	.string "Das ist aber ein hübscher Name.\p"
	.string "Möchtest du etwas über BEEREn lernen?$"
	.endif
	.endif

Route104_PrettyPetalFlowerShop_Text_BerriesExplanation:
	.ifdef ENGLISH
	.string "BERRIES grow on trees that thrive\n"
	.string "only in soft, loamy soil.\p"
	.string "If you take some BERRIES, be sure to\n"
	.string "plant one in the loamy soil again.\p"
	.string "A planted BERRY will soon sprout,\n"
	.string "grow into a plant, flower beautifully,\l"
	.string "then grow BERRIES again.\p"
	.string "I want to see the whole wide world\n"
	.string "filled with beautiful flowers.\l"
	.string "That's my dream.\p"
	.string "Please help me, {PLAYER}{KUN}. Plant BERRIES\n"
	.string "and bring more flowers into the world.$"
	.else
	.ifdef GERMAN
	.string "BEEREn wachsen an Bäumen, die nur in\n"
	.string "dunklem Lehmboden gedeihen.\p"
	.string "Wenn du BEEREn pflückst, pflanze\n"
	.string "immer neue in den Boden ein.\p"
	.string "Eine gepflanzte BEERE wird bald an-\n"
	.string "fangen zu sprießen, dann mit einer\p"
	.string "wunderhübschen Blüte erblühen, die\n"
	.string "bald zu einer BEERE wird.\p"
	.string "Ich würde die ganze Welt am liebsten mit\n"
	.string "wunderhübschen Blüten bedeckt sehen.\l"
	.string "Das ist mein Traum.\p"
	.string "Bitte, hilf mir, {PLAYER}{KUN}. Pflanze BEEREn\n"
	.string "und bring so Blüten in die Welt.$"
	.endif
	.endif

Route104_PrettyPetalFlowerShop_Text_FlowersBringHappiness:
	.ifdef ENGLISH
	.string "Flowers bring so much happiness to\n"
	.string "people, don't they?$"
	.else
	.ifdef GERMAN
	.string "Blumen erfreuen jedes Herz, nicht\n"
	.string "wahr?$"
	.endif
	.endif

Route104_PrettyPetalFlowerShop_Text_YouCanHaveThis:
	.ifdef ENGLISH
	.string "Hello!\p"
	.string "The more attention you give to flowers,\n"
	.string "the more beautifully they bloom.\p"
	.string "You'll like tending flowers. I'm sure\n"
	.string "of it. You can have this.$"
	.else
	.ifdef GERMAN
	.string "Hallo!\p"
	.string "Je mehr du dich um die Blumen kümmerst,\n"
	.string "desto schöner werden sie blühen.\p"
	.string "Auch du hast Blumen gerne.\n"
	.string "Das weiß ich genau. Das ist für dich.$"
	.endif
	.endif

Route104_PrettyPetalFlowerShop_Text_WailmerPailExplanation:
	.ifdef ENGLISH
	.string "While BERRY plants are growing,\n"
	.string "water them with the WAILMER PAIL.\p"
	.string "Oh, another thing.\p"
	.string "If you don't pick BERRIES for a while,\n"
	.string "they'll drop off onto the ground.\l"
	.string "But they'll sprout again.\p"
	.string "Isn't that awesome?\n"
	.string "It's like they have the will to live.$"
	.else
	.ifdef GERMAN
	.string "Nachdem du die BEEREn eingepflanzt\n"
	.string "hast, musst du sie mit der\l"
	.string "WAILMERKANNE wässern.\p"
	.string "Oh, und noch etwas!\p"
	.string "Wenn die BEEREn nicht gepflückt\n"
	.string "werden, fallen sie zu Boden. Aber sie\l"
	.string "werden wieder nachwachsen.\p"
	.string "Ist das nicht unglaublich? Es ist, als\n"
	.string "hätten sie den Willen zu leben.$"
	.endif
	.endif

Route104_PrettyPetalFlowerShop_Text_ImGrowingFlowers:
	.ifdef ENGLISH
	.string "I'm trying to be like my big sisters.\n"
	.string "I'm growing flowers, too!\p"
	.string "Here you go!\n"
	.string "It's for you!$"
	.else
	.ifdef GERMAN
	.string "Ich versuche, so zu sein wie meine große\n"
	.string "Schwester. Ich züchte auch Blumen!\p"
	.string "Hier, das ist für dich!$"
	.endif
	.endif

Route104_PrettyPetalFlowerShop_Text_MachineMixesBerries:
	.ifdef ENGLISH
	.string "You can plant a BERRY and grow it big,\n"
	.string "or you can make a POKéMON hold it.\p"
	.string "But now they have a machine that mixes\n"
	.string "up different BERRIES and makes candies\l"
	.string "for POKéMON.\p"
	.string "I want some candy, too.$"
	.else
	.ifdef GERMAN
	.string "Du kannst eine BEERE pflanzen und sie\n"
	.string "wachsen lassen, oder du gibst sie einem\l"
	.string "POKéMON zum Tragen.\p"
	.string "Und neuerdings gibt es eine Maschine,\n"
	.string "mit der kann man die verschiedensten\l"
	.string "BEEREn mixen und Süßigkeiten für die\l"
	.string "POKéMON daraus machen.\p"
	.string "Ich möchte auch Süßigkeiten haben.$"
	.endif
	.endif

SootopolisCity_Text_NameIsKiriHaveOneOfThese:
	.ifdef ENGLISH
	.string "Hi, what's your name?\p"
	.string "… … …  … … …  … … …\n"
	.string "Okay. That's nice!\p"
	.string "My name is KIRI.\p"
	.string "My mommy and daddy named me that so\n"
	.string "I would grow healthy and warmhearted.\l"
	.string "That's what they wished.\p"
	.string "You can have one of these.$"
	.else
	.ifdef GERMAN
	.string "Hi, wie heißt du?\p"
	.string "… … … … … … … … …\n"
	.string "Okay. Netter Name!\p"
	.string "Ich heiße BERTA.\p"
	.string "Meine Eltern haben mich so genannt,\n"
	.string "damit ich gesund und warmherzig werde.\l"
	.string "Das war ihr Wunsch.\p"
	.string "Hier, das schenke ich dir.$"
	.endif
	.endif

SootopolisCity_Text_GiveYouThisBerryToo:
	.ifdef ENGLISH
	.string "KIRI will give you this BERRY, too!\n"
	.string "I really like it lots!$"
	.else
	.ifdef GERMAN
	.string "BERTA will dir auch diese BEERE geben.\n"
	.string "Ich mag sie sehr!$"
	.endif
	.endif

SootopolisCity_Text_WhatKindOfWishInYourName:
	.ifdef ENGLISH
	.string "I wonder what kind of wish is included\n"
	.string "in your name.$"
	.else
	.ifdef GERMAN
	.string "Ich frage mich, welcher Wunsch in\n"
	.string "deinem Namen verborgen ist.$"
	.endif
	.endif

SootopolisCity_Text_LikeSeasonBornIn:
	.ifdef ENGLISH
	.string "Spring, summer, autumn, and winter.\p"
	.string "If you're born in springtime, do you like\n"
	.string "the spring, and if you're born in the\l"
	.string "summer, do you like the summer?$"
	.else
	.ifdef GERMAN
	.string "Frühling, Sommer, Herbst und Winter.\p"
	.string "Wenn du im Frühling geboren bist, magst\n"
	.string "du dann den Frühling? Wenn du im Sommer\l"
	.string "geboren bist, magst du den Sommer?$"
	.endif
	.endif

SootopolisCity_Text_ThenILoveAutumn:
	.ifdef ENGLISH
	.string "Then KIRI was born in the autumn,\n"
	.string "so I love the autumn!\p"
	.string "Which season do you like?$"
	.else
	.ifdef GERMAN
	.string "Dann wurde BERTA im Herbst geboren,\n"
	.string "denn ich liebe den Herbst!\p"
	.string "Welche Jahreszeit hast du am liebsten?$"
	.endif
	.endif

SootopolisCity_Text_OhDoesntMatter:
	.ifdef ENGLISH
	.string "Oh…\n"
	.string "It doesn't matter…\p"
	.string "There's so much that I want to know…$"
	.else
	.ifdef GERMAN
	.string "Oh…\n"
	.string "Das macht nichts…\p"
	.string "Es gibt so viel, was ich wissen möchte…$"
	.endif
	.endif
