gText_Birch_Welcome::
	.ifdef ENGLISH
	.string "Hi! Sorry to keep you waiting!\p"
	.string "Welcome to the world of POKéMON!\p"
	.string "My name is BIRCH.\p"
	.string "But everyone calls me the POKéMON\n"
	.string "PROFESSOR.\p"
	.string "$"
	.else
	.ifdef GERMAN
	.string "Sorry, dass du warten musstest.\p"
	.string "Willkommen in der Welt der POKéMON!\p"
	.string "Mein Name ist BIRK.\p"
	.string "Aber jeder nennt mich nur\n"
	.string "PROFESSOR POKéMON.\p"
	.string "$"
	.endif
	.endif

gText_Birch_Pokemon::
	.ifdef ENGLISH
	.string "This is what we call a “POKéMON.”\p"
	.string "\n"
	.string "$"
	.else
	.ifdef GERMAN
	.string "This is what we call a “POKéMON.”\p"
	.string "\n"
	.string "$"
	.endif
	.endif

gText_Birch_MainSpeech::
	.ifdef ENGLISH
	.string "This world is widely inhabited by\n"
	.string "creatures known as POKéMON.\p"
	.string "We humans live alongside POKéMON,\n"
	.string "at times as friendly playmates, and\l"
	.string "at times as cooperative workmates.\p"
	.string "And sometimes, we band together\n"
	.string "and battle others like us.\p"
	.string "But despite our closeness, we don't\n"
	.string "know everything about POKéMON.\p"
	.string "In fact, there are many, many\n"
	.string "secrets surrounding POKéMON.\p"
	.string "To unravel POKéMON mysteries,\n"
	.string "I've been undertaking research.\l"
	.string "That's what I do.\p"
	.string "$"
	.else
	.ifdef GERMAN
	.string "Auf dieser Welt leben Wesen,\n"
	.string "die uns als POKéMON bekannt sind.\p"
	.string "Wir Menschen leben Seite an Seite\n"
	.string "mit ihnen, als Freunde oder als\l"
	.string "Arbeitskollegen.\p"
	.string "Und manchmal schließen wir uns mit\n"
	.string "ihnen zusammen und tragen Kämpfe\l"
	.string "gegen andere von uns aus.\p"
	.string "Doch obwohl wir den POKéMON so\n"
	.string "nahe stehen, wissen wir noch nicht\l"
	.string "alles über sie.\p"
	.string "Es gibt noch viele, viele Geheim-\n"
	.string "nisse um die POKéMON.\p"
	.string "Um die Mysterien der POKéMON\n"
	.string "aufzudecken, widme ich mich der\l"
	.string "Forschung. Genau das tue ich.\p"
	.string "$"
	.endif
	.endif

gText_Birch_AndYouAre::
	.ifdef ENGLISH
	.string "And you are?$"
	.else
	.ifdef GERMAN
	.string "Und wer bist du?$"
	.endif
	.endif

gText_Birch_BoyOrGirl::
	.ifdef ENGLISH
	.string "Are you a boy?\n"
	.string "Or are you a girl?$"
	.else
	.ifdef GERMAN
	.string "Bist du ein Junge?\n"
	.string "Oder bist du ein Mädchen?$"
	.endif
	.endif

gText_Birch_WhatsYourName::
	.ifdef ENGLISH
	.string "All right.\n"
	.string "What's your name?$"
	.else
	.ifdef GERMAN
	.string "Fein!\n"
	.string "Und wie heißt du?$"
	.endif
	.endif

gText_Birch_SoItsPlayer::
	.ifdef ENGLISH
	.string "So it's {PLAYER}{KUN}?$"
	.else
	.ifdef GERMAN
	.string "Ah, du bist also {PLAYER}{KUN}?$"
	.endif
	.endif

gText_Birch_YourePlayer::
	.ifdef ENGLISH
	.string "Ah, okay!\p"
	.string "You're {PLAYER}{KUN} who's moving to my\n"
	.string "hometown of LITTLEROOT.\l"
	.string "I get it now!\p"
	.string "$"
	.else
	.ifdef GERMAN
	.string "Ah, okay!\p"
	.string "Jetzt habe ich es! Du heißt {PLAYER}{KUN}\n"
	.string "und bist gerade nach WURZELHEIM,\l"
	.string "meinen Heimatort, gezogen!\p"
	.string "$"
	.endif
	.endif

gText_Birch_AreYouReady::
	.ifdef ENGLISH
	.string "All right, are you ready?\p"
	.string "Your very own adventure is about\n"
	.string "to unfold.\p"
	.string "Take courage, and leap into the\n"
	.string "world of POKéMON where dreams,\l"
	.string "adventure, and friendships await!\p"
	.string "Well, I'll be expecting you later.\n"
	.string "Come see me in my POKéMON LAB.\p"
	.string "$"
	.else
	.ifdef GERMAN
	.string "Gut, bist du bereit?\p"
	.string "Dein eigenes Abenteuer wird\n"
	.string "nun beginnen.\p"
	.string "Hab nur Mut und stürze dich in die\n"
	.string "Welt der POKéMON, wo Abenteuer,\l"
	.string "Träume und Freundschaft warten.\p"
	.string "Komm später in mein POKéMON-LABOR,\n"
	.string "ich erwarte dich dort.\p"
	.string "$"
	.endif
	.endif
