BerryBlender_Text_BlendWithTheBlendMaster:
	.ifdef ENGLISH
	.string "BLEND MASTER: Indeed I am!\n"
	.string "The BLEND MASTER am I!\p"
	.string "Blend with me, and you shall witness\n"
	.string "the mastery I bring to blending!$"
	.else
	.ifdef GERMAN
	.string "MIXMEISTER: Genau das bin ich!\n"
	.string "Ich bin der MIXMEISTER!\p"
	.string "Mixe mit mir und du wirst Zeuge meines\n"
	.string "meisterhaften Mixens!$"
	.endif
	.endif

BerryBlender_Text_SeeMyMasteryInAction:
	.ifdef ENGLISH
	.string "BLEND MASTER: Hmmm! So, you wish to\n"
	.string "see my mastery in action?$"
	.else
	.ifdef GERMAN
	.string "MIXMEISTER: Hmm! Du willst mich also\n"
	.string "in Aktion sehen?!?$"
	.endif
	.endif

BerryBlender_Text_TooBusyNowIsee:
	.ifdef ENGLISH
	.string "Hmmm!\p"
	.string "So, you are too busy now, I see!\p"
	.string "But fear not!\n"
	.string "I shall be here all day!\l"
	.string "Hurry back from your errand!$"
	.else
	.ifdef GERMAN
	.string "Hmmm!\p"
	.string "Du bist also im Moment zu beschäftigt.\p"
	.string "Aber keine Angst!\n"
	.string "Ich bin den ganzen Tag hier!\l"
	.string "Beeil dich und komm wieder.$"
	.endif
	.endif

BerryBlender_Text_BlendMasterNoBerries:
	.ifdef ENGLISH
	.string "Hmmm!\p"
	.string "You haven't got a single BERRY!\p"
	.string "I shall be here all day!\n"
	.string "Hurry back with some BERRIES!$"
	.else
	.ifdef GERMAN
	.string "Hmmm!\p"
	.string "Du hast keine einzige BEERE!\p"
	.string "Ich bin den ganzen Tag hier!\n"
	.string "Besorg dir BEEREn und komm wieder.$"
	.endif
	.endif

BerryBlender_Text_BlendMasterKnowHowToMakePokeblocks:
	.ifdef ENGLISH
	.string "Of course!\n"
	.string "Of course!\p"
	.string "Incidentally…\n"
	.string "You do know how to blend {POKEBLOCK}S\l"
	.string "from BERRIES?$"
	.else
	.ifdef GERMAN
	.string "Sicher!\n"
	.string "Sicher!\p"
	.string "Übrigens…\n"
	.string "Weißt du eigentlich, wie man aus BEEREn\l"
	.string "{POKEBLOCK} herstellt?$"
	.endif
	.endif

BerryBlender_Text_BlendMasterExplainBerryBlending:
	.ifdef ENGLISH
	.string "Hmmm!\p"
	.string "Ah, but it is a simple process!\p"
	.string "When the BLENDER's arrow comes to\n"
	.string "your marker, just press the A Button.\p"
	.string "That's all you have to do.\p"
	.string "When you see how precisely I press\n"
	.string "the A Button, you will understand.$"
	.else
	.ifdef GERMAN
	.string "Hmm!\p"
	.string "Das ist so etwas von einfach!\p"
	.string "Wenn der Pfeil des BEERENMIXERs an\n"
	.string "deine Markierung gelangt, musst du den\l"
	.string "A-Knopf drücken.\p"
	.string "Das ist auch schon alles, was du zu tun\n"
	.string "hast.\p"
	.string "Schau dir an, wie präzise ich den\n"
	.string "A-Knopf drücke, dann wird es dir klar.$"
	.endif
	.endif

BerryBlender_Text_BlendMasterLetsBerryBlender:
	.ifdef ENGLISH
	.string "Fine!\p"
	.string "Let's get started, then!\p"
	.string "All together with the BLEND MASTER,\n"
	.string "let's BERRY BLENDER!$"
	.else
	.ifdef GERMAN
	.string "Sehr schön!\p"
	.string "Dann lass uns loslegen!\p"
	.string "Lass uns zusammen mit dem\n"
	.string "MIXMEISTER BEEREn MIXEN!$"
	.endif
	.endif

BerryBlender_Text_BlendMasterNoPokeblockCase:
	.ifdef ENGLISH
	.string "Hmmm!\p"
	.string "You don't appear to have gotten\n"
	.string "the {POKEBLOCK} CASE!\p"
	.string "I shall be here all day!\n"
	.string "Obtain the {POKEBLOCK} CASE and hurry back!$"
	.else
	.ifdef GERMAN
	.string "Hmm!\p"
	.string "Du hast keine {POKEBLOCK}BOX!\p"
	.string "Ich bin den ganzen Tag hier!\n"
	.string "Hol dir die {POKEBLOCK}BOX und komm dann\l"
	.string "wieder.$"
	.endif
	.endif

BerryBlender_Text_BlendMasterPokeblockCaseFull:
	.ifdef ENGLISH
	.string "Hmmm!\p"
	.string "Your {POKEBLOCK} CASE appears to be full!\p"
	.string "I shall be here all day!\n"
	.string "Use some {POKEBLOCK}S and hurry back!$"
	.else
	.ifdef GERMAN
	.string "Hmm!\p"
	.string "Deine {POKEBLOCK}BOX scheint voll zu sein.\p"
	.string "Ich bin den ganzen Tag hier!\n"
	.string "Verwende einige {POKEBLOCK} und komm\l"
	.string "dann wieder.$"
	.endif
	.endif

BerryBlender_Text_WhoaAwesome:
	.ifdef ENGLISH
	.string "Whoa!\n"
	.string "Awesome!$"
	.else
	.ifdef GERMAN
	.string "Whoa!\n"
	.string "Wahnsinn!!!$"
	.endif
	.endif

BerryBlender_Text_WickedlyFast:
	.ifdef ENGLISH
	.string "Wickedly fast!$"
	.else
	.ifdef GERMAN
	.string "Unglaublich schnell!$"
	.endif
	.endif

BerryBlender_Text_WhatAnExpert:
	.ifdef ENGLISH
	.string "What an expert!$"
	.else
	.ifdef GERMAN
	.string "Das ist ein wahrer Experte!$"
	.endif
	.endif

BerryBlender_Text_MadeAmazingPokeblocksWithMaster:
	.ifdef ENGLISH
	.string "When I blended with the MASTER,\n"
	.string "we made amazing {POKEBLOCK}S!$"
	.else
	.ifdef GERMAN
	.string "Als ich mit dem Meister gemixt habe,\n"
	.string "haben wir die besten {POKEBLOCK}\l"
	.string "hergestellt!$"
	.endif
	.endif

BerryBlender_Text_QualitiesOfBlendMaster:
	.ifdef ENGLISH
	.string "Eyes that track the arrow with\n"
	.string "machinelike intensity…\p"
	.string "A hand that taps the A Button\n"
	.string "with clockwork-like precision…\p"
	.string "Possessing these qualities makes\n"
	.string "the BLEND MASTER truly great.$"
	.else
	.ifdef GERMAN
	.string "Augen, die dem Pfeil unermüdlich und\n"
	.string "genau folgen…\p"
	.string "Eine Hand, die den A-Knopf mit der\n"
	.string "Präzision einer Uhr drückt…\p"
	.string "Diese Fähigkeiten machen den MIX-\n"
	.string "MEISTER zu dem Meister schlechthin!$"
	.endif
	.endif

BerryBlender_Text_MasterWorksOnSkillsInMountains:
	.ifdef ENGLISH
	.string "The BLEND MASTER's supposed to work\n"
	.string "on his skills deep in the mountains.\p"
	.string "Sometimes, he comes to LILYCOVE\n"
	.string "to blend BERRIES all day long.$"
	.else
	.ifdef GERMAN
	.string "Der MIXMEISTER arbeitet im Gebirge\n"
	.string "an der Vollendung seiner Fähigkeiten.\p"
	.string "Manchmal kommt er nach SEEGRASULB, um\n"
	.string "den ganzen Tag BEEREn zu mixen.$"
	.endif
	.endif
