Text_PictureBookShelf:
	.ifdef ENGLISH
	.string "There's a set of POKéMON picture books.$"
	.else
	.ifdef GERMAN
	.string "Eine Sammlung von POKéMON-Büchern.$"
	.endif
	.endif

Text_BookShelf:
	.ifdef ENGLISH
	.string "It's filled with all sorts of books.$"
	.else
	.ifdef GERMAN
	.string "Hier stehen jede Menge Bücher.$"
	.endif
	.endif

Text_PokemonCenterBookShelf:
	.ifdef ENGLISH
	.string "POKéMON magazines!\n"
	.string "POKéMON PAL…\p"
	.string "POKéMON HANDBOOK…\n"
	.string "ADORABLE POKéMON…$"
	.else
	.ifdef GERMAN
	.string "POKéMON-Magazine!\n"
	.string "DER POKéMON FREUND…\p"
	.string "POKéMON HANDBUCH…\n"
	.string "GELIEBTE POKéMON…$"
	.endif
	.endif

Text_Vase:
	.ifdef ENGLISH
	.string "This vase looks expensive…\n"
	.string "Peered inside…\p"
	.string "But, it was empty.$"
	.else
	.ifdef GERMAN
	.string "Diese Vase sieht sehr teuer aus…\n"
	.string "Schauen wir mal hinein…\p"
	.string "Och, sie ist leer.$"
	.endif
	.endif

Text_EmptyTrashCan:
	.ifdef ENGLISH
	.string "It's empty.$"
	.else
	.ifdef GERMAN
	.string "Leer…$"
	.endif
	.endif

Text_ShopShelf:
	.ifdef ENGLISH
	.string "The shelves brim with all sorts of\n"
	.string "POKéMON merchandise.$"
	.else
	.ifdef GERMAN
	.string "Die Regale biegen sich unter dem\n"
	.string "Gewicht von POKéMON-Artikeln.$"
	.endif
	.endif

Text_Blueprint:
	.ifdef ENGLISH
	.string "A blueprint of some sort?\n"
	.string "It's too complicated!$"
	.else
	.ifdef GERMAN
	.string "Sind das Blaupausen?\n"
	.string "Die sind zu kompliziert zu lesen.$"
	.endif
	.endif
