gContestHallPaintingCaption::
	.ifdef ENGLISH
	.string "{STR_VAR_1}\n"
	.string "{STR_VAR_2}'s {STR_VAR_3}$"
	.else
	.ifdef GERMAN
	.string "{STR_VAR_1}\n"
	.string "{STR_VAR_3} von {STR_VAR_2}$"
	.endif
	.endif

@ Unused
gContestPaintingContest::
	.ifdef ENGLISH
	.string "CONTEST$"
	.else
	.ifdef GERMAN
	.string "CONTEST$"
	.endif
	.endif

gContestRankNormal::
	.ifdef ENGLISH
	.string "NORMAL RANK$"
	.else
	.ifdef GERMAN
	.string "NORMAL-KLASSE$"
	.endif
	.endif

gContestRankSuper::
	.ifdef ENGLISH
	.string "SUPER RANK$"
	.else
	.ifdef GERMAN
	.string "SUPER-KLASSE$"
	.endif
	.endif

gContestRankHyper::
	.ifdef ENGLISH
	.string "HYPER RANK$"
	.else
	.ifdef GERMAN
	.string "HYPER-KLASSE$"
	.endif
	.endif

gContestRankMaster::
	.ifdef ENGLISH
	.string "MASTER RANK$"
	.else
	.ifdef GERMAN
	.string "MASTER-KLASSE$"
	.endif
	.endif

gContestLink::
	.ifdef ENGLISH
	.string "LINK$"
	.else
	.ifdef GERMAN
	.string "LINK$"
	.endif
	.endif

gContestCoolness::
	.ifdef ENGLISH
	.string "COOLNESS$"
	.else
	.ifdef GERMAN
	.string "COOL.$"
	.endif
	.endif

gContestBeauty::
	.ifdef ENGLISH
	.string "BEAUTY$"
	.else
	.ifdef GERMAN
	.string "SCHÖN.$"
	.endif
	.endif

gContestCuteness::
	.ifdef ENGLISH
	.string "CUTENESS$"
	.else
	.ifdef GERMAN
	.string "ANMUT$"
	.endif
	.endif

gContestSmartness::
	.ifdef ENGLISH
	.string "SMARTNESS$"
	.else
	.ifdef GERMAN
	.string "KLUG.$"
	.endif
	.endif

gContestToughness::
	.ifdef ENGLISH
	.string "TOUGHNESS$"
	.else
	.ifdef GERMAN
	.string "STÄRKE$"
	.endif
	.endif

gContestPaintingCool1::
	.ifdef ENGLISH
	.string "Nonstop supercool--\n"
	.string "the inestimable {STR_VAR_1}$"
	.else
	.ifdef GERMAN
	.string "Super-mega-cool ist\n"
	.string "dieses umwerfende {STR_VAR_1}$"
	.endif
	.endif

gContestPaintingCool2::
	.ifdef ENGLISH
	.string "Hey, there!\n"
	.string "The good-looking POKéMON {STR_VAR_1}$"
	.else
	.ifdef GERMAN
	.string "Das anbetungswürdige\n"
	.string "POKéMON: {STR_VAR_1}$"
	.endif
	.endif

gContestPaintingCool3::
	.ifdef ENGLISH
	.string "The marvelous, wonderful, and\n"
	.string "very great {STR_VAR_1}$"
	.else
	.ifdef GERMAN
	.string "Phantastisch, großartig -\n"
	.string "schlicht brillant: {STR_VAR_1}$"
	.endif
	.endif

gContestPaintingBeauty1::
	.ifdef ENGLISH
	.string "This century's last Venus--\n"
	.string "the beautiful {STR_VAR_1}$"
	.else
	.ifdef GERMAN
	.string "Ein Bild von einem POKéMON!\n"
	.string "Das wunderschöne {STR_VAR_1}$"
	.endif
	.endif

gContestPaintingBeauty2::
	.ifdef ENGLISH
	.string "{STR_VAR_1}'s dazzling,\n"
	.string "glittering smile$"
	.else
	.ifdef GERMAN
	.string "Einfach umwerfend, das strahlende\n"
	.string "Lächeln von {STR_VAR_1}$"
	.endif
	.endif

gContestPaintingBeauty3::
	.ifdef ENGLISH
	.string "POKéMON CENTER's super idol--\n"
	.string "the incomparable {STR_VAR_1}$"
	.else
	.ifdef GERMAN
	.string "Superstar des POKéMON-CENTERs -\n"
	.string "das unvergleichliche {STR_VAR_1}$"
	.endif
	.endif

gContestPaintingCute1::
	.ifdef ENGLISH
	.string "The lovely and sweet {STR_VAR_1}$"
	.else
	.ifdef GERMAN
	.string "Das liebliche, zuckersüße {STR_VAR_1}$"
	.endif
	.endif

gContestPaintingCute2::
	.ifdef ENGLISH
	.string "The pretty {STR_VAR_1}'s\n"
	.string "winning portrait$"
	.else
	.ifdef GERMAN
	.string "Das Gewinner-Portrait\n"
	.string "von dem hübschen {STR_VAR_1}$"
	.endif
	.endif

gContestPaintingCute3::
	.ifdef ENGLISH
	.string "Give us a wink!\n"
	.string "The cutie POKéMON {STR_VAR_1}$"
	.else
	.ifdef GERMAN
	.string "Winke uns zu, du\n"
	.string "goldiges {STR_VAR_1}$"
	.endif
	.endif

gContestPaintingSmart1::
	.ifdef ENGLISH
	.string "The smartness maestro--\n"
	.string "the wise POKéMON {STR_VAR_1}$"
	.else
	.ifdef GERMAN
	.string "Der Gelehrte unter den\n"
	.string "POKéMON! Das weise {STR_VAR_1}$"
	.endif
	.endif

gContestPaintingSmart2::
	.ifdef ENGLISH
	.string "{STR_VAR_1}--the one chosen\n"
	.string "above all POKéMON$"
	.else
	.ifdef GERMAN
	.string "Das auserwählte und\n"
	.string "einzigartige POKéMON: {STR_VAR_1}$"
	.endif
	.endif

gContestPaintingSmart3::
	.ifdef ENGLISH
	.string "The excellent {STR_VAR_1}'s\n"
	.string "moment of elegance$"
	.else
	.ifdef GERMAN
	.string "Das grandiose {STR_VAR_1},\n"
	.string "der Inbegriff von Eleganz und Stil$"
	.endif
	.endif

gContestPaintingTough1::
	.ifdef ENGLISH
	.string "The powerfully muscular\n"
	.string "speedster {STR_VAR_1}$"
	.else
	.ifdef GERMAN
	.string "Der energische, kraftstrotzende\n"
	.string "Überflieger: {STR_VAR_1}$"
	.endif
	.endif

gContestPaintingTough2::
	.ifdef ENGLISH
	.string "The strong, stronger, and\n"
	.string "strongest {STR_VAR_1}$"
	.else
	.ifdef GERMAN
	.string "Stark, stärker, am stärksten -\n"
	.string "das allerstärkste {STR_VAR_1}$"
	.endif
	.endif

gContestPaintingTough3::
	.ifdef ENGLISH
	.string "The mighty tough\n"
	.string "hyper POKéMON {STR_VAR_1}$"
	.else
	.ifdef GERMAN
	.string "Das mächtige, prächtige - das\n"
	.string "stärkste POKéMON: {STR_VAR_1}$"
	.endif
	.endif
