@ Contest move effect descriptions

gText_HighlyAppealingMove::
	.ifdef ENGLISH
	.string "A highly appealing move.$"
	.else
	.ifdef GERMAN
	.string "Eine sehr ansprechende\n"
	.string "Vorführung.$"
	.endif
	.endif

gText_UserMoreEasilyStartled::
	.ifdef ENGLISH
	.string "After this move, the user is\n"
	.string "more easily startled.$"
	.else
	.ifdef GERMAN
	.string "Einsatz der Attacke macht\n"
	.string "PKMN leichter irritierbar.$"
	.endif
	.endif

gText_GreatAppealButNoMoreToEnd::
	.ifdef ENGLISH
	.string "Makes a great appeal, but\n"
	.string "allows no more to the end.$"
	.else
	.ifdef GERMAN
	.string "Großartiger Ausdruck, der\n"
	.string "sich nicht steigern lässt.$"
	.endif
	.endif

gText_UsedRepeatedlyWithoutBoringJudge::
	.ifdef ENGLISH
	.string "Can be repeatedly used\n"
	.string "without boring the JUDGE.$"
	.else
	.ifdef GERMAN
	.string "Langweilt den JUROR auch\n"
	.string "bei Wiederholung nicht.$"
	.endif
	.endif

gText_AvoidStartledByOthersOnce::
	.ifdef ENGLISH
	.string "Can avoid being startled\n"
	.string "by others once.$"
	.else
	.ifdef GERMAN
	.string "Kann Irritation durch\n"
	.string "andere einmal verhindern.$"
	.endif
	.endif

gText_AvoidStartledByOthers::
	.ifdef ENGLISH
	.string "Can avoid being startled\n"
	.string "by others.$"
	.else
	.ifdef GERMAN
	.string "Kann Irritation durch\n"
	.string "andere verhindern.$"
	.endif
	.endif

gText_AvoidStartledByOthersLittle::
	.ifdef ENGLISH
	.string "Can avoid being startled\n"
	.string "by others a little.$"
	.else
	.ifdef GERMAN
	.string "Kann Irritation durch an-\n"
	.string "dere ein wenig eindämmen.$"
	.endif
	.endif

gText_UserLessLikelyStartled::
	.ifdef ENGLISH
	.string "After this move, the user is\n"
	.string "less likely to be startled.$"
	.else
	.ifdef GERMAN
	.string "Einsatz der Attacke dämmt\n"
	.string "danach Irritation ein.$"
	.endif
	.endif

gText_SlightlyStartleFrontMon::
	.ifdef ENGLISH
	.string "Slightly startles the\n"
	.string "POKéMON in front.$"
	.else
	.ifdef GERMAN
	.string "Irritiert das vordere\n"
	.string "POKéMON ein wenig.$"
	.endif
	.endif

gText_SlightlyStartleAppealed::
	.ifdef ENGLISH
	.string "Slightly startles those\n"
	.string "that have made appeals.$"
	.else
	.ifdef GERMAN
	.string "Irritiert die POKéMON ein\n"
	.string "wenig, die schon auftraten.$"
	.endif
	.endif

gText_StartleAppealedBeforeUser::
	.ifdef ENGLISH
	.string "Startles the POKéMON that\n"
	.string "appealed before the user.$"
	.else
	.ifdef GERMAN
	.string "Irritiert das POKéMON, das\n"
	.string "vorher aufgetreten ist.$"
	.endif
	.endif

gText_StartleAllAppealed::
	.ifdef ENGLISH
	.string "Startles all POKéMON that\n"
	.string "have done their appeals.$"
	.else
	.ifdef GERMAN
	.string "Irritiert alle POKéMON,\n"
	.string "die bisher auftraten.$"
	.endif
	.endif

gText_BadlyStartleFrontMon::
	.ifdef ENGLISH
	.string "Badly startles the\n"
	.string "POKéMON in front.$"
	.else
	.ifdef GERMAN
	.string "Irritiert das vordere\n"
	.string "POKéMON sehr stark.$"
	.endif
	.endif

gText_BadlyStartleAppealed::
	.ifdef ENGLISH
	.string "Badly startles those that\n"
	.string "have made appeals.$"
	.else
	.ifdef GERMAN
	.string "Irritiert die POKéMON, die\n"
	.string "schon aufgetreten sind.$"
	.endif
	.endif

gText_StartleAppealedBeforeUser2::
	.ifdef ENGLISH
	.string "Startles the POKéMON that\n"
	.string "appealed before the user.$"
	.else
	.ifdef GERMAN
	.string "Irritiert das POKéMON, das\n"
	.string "vorher aufgetreten ist.$"
	.endif
	.endif

gText_StartleAllAppealed2::
	.ifdef ENGLISH
	.string "Startles all POKéMON that\n"
	.string "have done their appeals.$"
	.else
	.ifdef GERMAN
	.string "Irritiert alle POKéMON, die\n"
	.string "vorher aufgetreten sind.$"
	.endif
	.endif

gText_ShiftJudgesAttentionFromOthers::
	.ifdef ENGLISH
	.string "Shifts the JUDGE's\n"
	.string "attention from others.$"
	.else
	.ifdef GERMAN
	.string "Lenkt den JUROR von den\n"
	.string "anderen POKéMON ab.$"
	.endif
	.endif

gText_StartleMonHasJudgesAttention::
	.ifdef ENGLISH
	.string "Startles the POKéMON that\n"
	.string "has the JUDGE's attention.$"
	.else
	.ifdef GERMAN
	.string "Irritiert PKMN, bes. die,\n"
	.string "auf die der JUROR achtet.$"
	.endif
	.endif

gText_JamOthersMissesTurn::
	.ifdef ENGLISH
	.string "Jams the others, and misses\n"
	.string "one turn of appeals.$"
	.else
	.ifdef GERMAN
	.string "Stört die anderen und An-\n"
	.string "wender setzt 1 Runde aus.$"
	.endif
	.endif

gText_StartleMonsMadeSameTypeAppeal::
	.ifdef ENGLISH
	.string "Startles POKéMON that\n"
	.string "made a same-type appeal.$"
	.else
	.ifdef GERMAN
	.string "Irritiert PKMN, bes. die, die\n"
	.string "Ausdruck gl. Typs zeigten.$"
	.endif
	.endif

gText_BadlyStartleCoolAppeals::
	.ifdef ENGLISH
	.string "Badly startles POKéMON\n"
	.string "that made COOL appeals.$"
	.else
	.ifdef GERMAN
	.string "Irritiert PKMN, die Ausdrck.\n"
	.string "des Typs COOL vorführten.$"
	.endif
	.endif

gText_BadlyStartleBeautyAppeals::
	.ifdef ENGLISH
	.string "Badly startles POKéMON\n"
	.string "that made BEAUTY appeals.$"
	.else
	.ifdef GERMAN
	.string "Irritiert PKMN, die Ausdrck.\n"
	.string "des Typs SCHÖN vorführten.$"
	.endif
	.endif

gText_BadlyStartleCuteAppeals::
	.ifdef ENGLISH
	.string "Badly startles POKéMON\n"
	.string "that made CUTE appeals.$"
	.else
	.ifdef GERMAN
	.string "Irritiert PKMN, die Ausdrck.\n"
	.string "des Typs ANMUT vorführten.$"
	.endif
	.endif

gText_BadlyStartleSmartAppeals::
	.ifdef ENGLISH
	.string "Badly startles POKéMON\n"
	.string "that made SMART appeals.$"
	.else
	.ifdef GERMAN
	.string "Irritiert PKMN, die Ausdrck.\n"
	.string "des Typs KLUG vorführten.$"
	.endif
	.endif

gText_BadlyStartleToughAppeals::
	.ifdef ENGLISH
	.string "Badly startles POKéMON\n"
	.string "that made TOUGH appeals.$"
	.else
	.ifdef GERMAN
	.string "Irritiert PKMN, die Ausdrck.\n"
	.string "des Typs STARK vorführten.$"
	.endif
	.endif

gText_MakeMonAfterUserNervous::
	.ifdef ENGLISH
	.string "Makes one POKéMON after\n"
	.string "the user nervous.$"
	.else
	.ifdef GERMAN
	.string "Macht nachfolgendes\n"
	.string "POKéMON nervös.$"
	.endif
	.endif

gText_MakeAllMonsAfterUserNervous::
	.ifdef ENGLISH
	.string "Makes all POKéMON after\n"
	.string "the user nervous.$"
	.else
	.ifdef GERMAN
	.string "Macht alle nachfolgenden\n"
	.string "POKéMON nervös.$"
	.endif
	.endif

gText_WorsenConditionOfThoseMadeAppeals::
	.ifdef ENGLISH
	.string "Worsens the condition of\n"
	.string "those that made appeals.$"
	.else
	.ifdef GERMAN
	.string "Schwächt Kondition der\n"
	.string "PKMN, die bisher auftraten.$"
	.endif
	.endif

gText_BadlyStartleMonsGoodCondition::
	.ifdef ENGLISH
	.string "Badly startles POKéMON in\n"
	.string "good condition.$"
	.else
	.ifdef GERMAN
	.string "Irritiert POKéMON, die eine\n"
	.string "gute Kondition haben.$"
	.endif
	.endif

gText_AppealGreatIfPerformedFirst::
	.ifdef ENGLISH
	.string "The appeal works great if\n"
	.string "performed first.$"
	.else
	.ifdef GERMAN
	.string "Ausdruck gelingt sehr gut,\n"
	.string "wenn als Erster vorgeführt.$"
	.endif
	.endif

gText_AppealGreatIfPerformedLast::
	.ifdef ENGLISH
	.string "The appeal works great if\n"
	.string "performed last.$"
	.else
	.ifdef GERMAN
	.string "Ausdruck gelingt sehr gut,\n"
	.string "wenn zuletzt vorgeführt.$"
	.endif
	.endif

gText_AppealAsGoodAsThoseBeforeIt::
	.ifdef ENGLISH
	.string "Makes the appeal as good\n"
	.string "as those before it.$"
	.else
	.ifdef GERMAN
	.string "Ausdruck gelingt so gut\n"
	.string "wie die der Vorgänger.$"
	.endif
	.endif

gText_AppealAsGoodAsOneBeforeIt::
	.ifdef ENGLISH
	.string "Makes the appeal as good\n"
	.string "as the one before it.$"
	.else
	.ifdef GERMAN
	.string "Ausdruck gelingt so gut\n"
	.string "wie der des Vorgängers.$"
	.endif
	.endif

gText_AppealBetterLaterItsPerformed::
	.ifdef ENGLISH
	.string "The appeal works better\n"
	.string "the later it is performed.$"
	.else
	.ifdef GERMAN
	.string "Je später der Auftritt,\n"
	.string "desto besser der Ausdruck.$"
	.endif
	.endif

gText_AppealVariesDependingOnTiming::
	.ifdef ENGLISH
	.string "The appeal's quality varies\n"
	.string "depending on its timing.$"
	.else
	.ifdef GERMAN
	.string "Die Qualität des Ausdrucks\n"
	.string "hängt vom Timing ab.$"
	.endif
	.endif

gText_WorksWellIfSameTypeAsBefore::
	.ifdef ENGLISH
	.string "Works well if it's the same\n"
	.string "type as the one before.$"
	.else
	.ifdef GERMAN
	.string "Gelingt gut, wenn vom\n"
	.string "selben Typ wie der vorige.$"
	.endif
	.endif

gText_WorksWellIfDifferentTypeAsBefore::
	.ifdef ENGLISH
	.string "Works well if different in\n"
	.string "type than the one before.$"
	.else
	.ifdef GERMAN
	.string "Gelingt gut, wenn vom\n"
	.string "anderen Typ als der vorige.$"
	.endif
	.endif

gText_AffectedByAppealInFront::
	.ifdef ENGLISH
	.string "Affected by how well the\n"
	.string "appeal in front goes.$"
	.else
	.ifdef GERMAN
	.string "Hängt von Qualität des\n"
	.string "Ausdrucks d. Vorgängers ab.$"
	.endif
	.endif

gText_UpsConditionHelpsPreventNervousness::
	.ifdef ENGLISH
	.string "Ups the user's condition.\n"
	.string "Helps prevent nervousness.$"
	.else
	.ifdef GERMAN
	.string "Verbessert die Kondition\n"
	.string "und verhindert Nervosität.$"
	.endif
	.endif

gText_AppealWorksWellIfConditionGood::
	.ifdef ENGLISH
	.string "The appeal works well if the\n"
	.string "user's condition is good.$"
	.else
	.ifdef GERMAN
	.string "Ausdruck gelingt gut, wenn\n"
	.string "Kondition des PKMN gut ist.$"
	.endif
	.endif

gText_NextAppealMadeEarlier::
	.ifdef ENGLISH
	.string "The next appeal can be\n"
	.string "made earlier next turn.$"
	.else
	.ifdef GERMAN
	.string "Der nächste Ausdruck kann\n"
	.string "früher vorgeführt werden.$"
	.endif
	.endif

gText_NextAppealMadeLater::
	.ifdef ENGLISH
	.string "The next appeal can be\n"
	.string "made later next turn.$"
	.else
	.ifdef GERMAN
	.string "Der nächste Ausdruck kann\n"
	.string "später vorgeführt werden.$"
	.endif
	.endif

gText_TurnOrderMoreEasilyScrambled::
	.ifdef ENGLISH
	.string "Makes the next turn's order\n"
	.string "more easily scrambled.$"
	.else
	.ifdef GERMAN
	.string "Ändert die Reihenfolge der\n"
	.string "nächst. Auftritte leichter.$"
	.endif
	.endif

gText_ScrambleOrderOfNextAppeals::
	.ifdef ENGLISH
	.string "Scrambles the order of\n"
	.string "appeals on the next turn.$"
	.else
	.ifdef GERMAN
	.string "Ändert die Reihenfolge der\n"
	.string "nächsten Auftritte.$"
	.endif
	.endif

gText_AppealExcitesAudienceInAnyContest::
	.ifdef ENGLISH
	.string "An appeal that excites the\n"
	.string "audience in any CONTEST.$"
	.else
	.ifdef GERMAN
	.string "Verzückt das Publikum in \n"
	.string "jedem WETTBEWERB.$"
	.endif
	.endif

gText_BadlyStartlesMonsGoodAppeals::
	.ifdef ENGLISH
	.string "Badly startles all POKéMON\n"
	.string "that made good appeals.$"
	.else
	.ifdef GERMAN
	.string "Irritiert alle POKéMON,\n"
	.string "deren Ausdruck gut war.$"
	.endif
	.endif

gText_AppealBestMoreCrowdExcited::
	.ifdef ENGLISH
	.string "The appeal works best the\n"
	.string "more the crowd is excited.$"
	.else
	.ifdef GERMAN
	.string "Gelingt am besten, wenn\n"
	.string "das Publikum gespannt ist.$"
	.endif
	.endif

gText_TemporarilyStopCrowdExcited::
	.ifdef ENGLISH
	.string "Temporarily stops the\n"
	.string "crowd from growing excited.$"
	.else
	.ifdef GERMAN
	.string "Bremst zeitweise Begeis-\n"
	.string "terung des Publikums.$"
	.endif
	.endif

@ Unused move names

gText_RainDance::
	.ifdef ENGLISH
	.string "RAIN DANCE$"
	.else
	.ifdef GERMAN
	.string "REGENTANZ$"
	.endif
	.endif

gText_Rage::
	.ifdef ENGLISH
	.string "RAGE$"
	.else
	.ifdef GERMAN
	.string "RASEREI$"
	.endif
	.endif

gText_FocusEnergy::
	.ifdef ENGLISH
	.string "FOCUS ENERGY$"
	.else
	.ifdef GERMAN
	.string "ENERGIEFOKUS$"
	.endif
	.endif

gText_Hypnosis::
	.ifdef ENGLISH
	.string "HYPNOSIS$"
	.else
	.ifdef GERMAN
	.string "HYPNOSE$"
	.endif
	.endif

gText_Softboiled::
	.ifdef ENGLISH
	.string "SOFTBOILED$"
	.else
	.ifdef GERMAN
	.string "WEICHEI$"
	.endif
	.endif

gText_HornAttack::
	.ifdef ENGLISH
	.string "HORN ATTACK$"
	.else
	.ifdef GERMAN
	.string "HORNATTACKE$"
	.endif
	.endif

gText_SwordsDance::
	.ifdef ENGLISH
	.string "SWORDS DANCE$"
	.else
	.ifdef GERMAN
	.string "SCHWERTTANZ$"
	.endif
	.endif

gText_Conversion::
	.ifdef ENGLISH
	.string "CONVERSION$"
	.else
	.ifdef GERMAN
	.string "UMWANDLUNG$"
	.endif
	.endif

gText_SunnyDay::
	.ifdef ENGLISH
	.string "SUNNY DAY$"
	.else
	.ifdef GERMAN
	.string "SONNENTAG$"
	.endif
	.endif

gText_Rest2::
	.ifdef ENGLISH
	.string "REST$"
	.else
	.ifdef GERMAN
	.string "ERHOLUNG$"
	.endif
	.endif

gText_Vicegrip::
	.ifdef ENGLISH
	.string "VICEGRIP$"
	.else
	.ifdef GERMAN
	.string "KLAMMER$"
	.endif
	.endif

gText_DefenseCurl::
	.ifdef ENGLISH
	.string "DEFENSE CURL$"
	.else
	.ifdef GERMAN
	.string "EINIGLER$"
	.endif
	.endif

gText_LockOn::
	.ifdef ENGLISH
	.string "LOCK-ON$"
	.else
	.ifdef GERMAN
	.string "ZIELSCHUSS$"
	.endif
	.endif

@ Contest type names

gContestMoveTypeCoolText::
	.ifdef ENGLISH
	.string "COOL$"
	.else
	.ifdef GERMAN
	.string "COOL.$"
	.endif
	.endif

gContestMoveTypeBeautyText::
	.ifdef ENGLISH
	.string "BEAUTY$"
	.else
	.ifdef GERMAN
	.string "SCHÖN.$"
	.endif
	.endif

gContestMoveTypeCuteText::
	.ifdef ENGLISH
	.string "CUTE$"
	.else
	.ifdef GERMAN
	.string "ANMUT$"
	.endif
	.endif

gContestMoveTypeSmartText::
	.ifdef ENGLISH
	.string "SMART$"
	.else
	.ifdef GERMAN
	.string "KLUG.$"
	.endif
	.endif

gContestMoveTypeToughText::
	.ifdef ENGLISH
	.string "TOUGH$"
	.else
	.ifdef GERMAN
	.string "STÄRKE$"
	.endif
	.endif

gText_AppealNumWhichMoveWillBePlayed::
	.ifdef ENGLISH
	.string "Appeal no. {STR_VAR_1}!\n"
	.string "Which move will be played?$"
	.else
	.ifdef GERMAN
	.string "Ausdruck {STR_VAR_1}! Welche\n"
	.string "Attacke wird gezeigt?$"
	.endif
	.endif

gText_AppealNumButItCantParticipate::
	.ifdef ENGLISH
	.string "Appeal no. {STR_VAR_1}!\n"
	.string "But it can't participate!$"
	.else
	.ifdef GERMAN
	.string "Ausdruck {STR_VAR_1}! Aber es\n"
	.string "kann nicht teilnehmen!$"
	.endif
	.endif

gText_MonAppealedWithMove::
	.ifdef ENGLISH
	.string "{STR_VAR_1} appealed with\n"
	.string "{STR_VAR_2}!$"
	.else
	.ifdef GERMAN
	.string "{STR_VAR_1} führt\n"
	.string "{STR_VAR_2} vor!$"
	.endif
	.endif

gText_MonWasWatchingOthers::
	.ifdef ENGLISH
	.string "{STR_VAR_1} was watching\n"
	.string "the others.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"
	.else
	.ifdef GERMAN
	.string "{STR_VAR_1} beobachtet\n"
	.string "die anderen.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"
	.endif
	.endif

gText_AllOutOfAppealTime::
	.ifdef ENGLISH
	.string "We're all out of\n"
	.string "Appeal Time!{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"
	.else
	.ifdef GERMAN
	.string "Soweit zur\n"
	.string "Ausdruckskraft!{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"
	.endif
	.endif

@ Unused appeal result texts

gText_ButAppealWasJammed::
	.ifdef ENGLISH
	.string "But the appeal was\n"
	.string "jammed.$"
	.else
	.ifdef GERMAN
	.string "Der Auftritt\n"
	.string "wurde gestört.$"
	.endif
	.endif

gText_FollowedAnotherMonsLead::
	.ifdef ENGLISH
	.string "It followed another\n"
	.string "POKéMON's lead.$"
	.else
	.ifdef GERMAN
	.string "Es folgte einem\n"
	.string "anderen POKéMON.$"
	.endif
	.endif

gText_ButItMessedUp::
	.ifdef ENGLISH
	.string "But it messed up.$"
	.else
	.ifdef GERMAN
	.string "Es scheiterte.$"
	.endif
	.endif

gText_WentBetterThanUsual::
	.ifdef ENGLISH
	.string "It went better than\n"
	.string "usual.$"
	.else
	.ifdef GERMAN
	.string "Das lief besser\n"
	.string "als sonst.$"
	.endif
	.endif

gText_JudgeLookedAwayForSomeReason::
	.ifdef ENGLISH
	.string "The JUDGE looked away\n"
	.string "for some reason.$"
	.else
	.ifdef GERMAN
	.string "Der JUROR war\n"
	.string "irgendwie abgelenkt.$"
	.endif
	.endif

gText_WorkedHardToBuildOnPastMistakes::
	.ifdef ENGLISH
	.string "It worked hard to build on\n"
	.string "past mistakes.$"
	.else
	.ifdef GERMAN
	.string "Es strengte sich an,\n"
	.string "Fehler auszubügeln.$"
	.endif
	.endif

gText_CantMakeAnyMoreMoves::
	.ifdef ENGLISH
	.string "It can't make any more\n"
	.string "moves.$"
	.else
	.ifdef GERMAN
	.string "Es kann keine Attacken\n"
	.string "mehr ausführen.$"
	.endif
	.endif

gText_WorkedFrighteninglyWell::
	.ifdef ENGLISH
	.string "It worked frighteningly\n"
	.string "well.$"
	.else
	.ifdef GERMAN
	.string "Das lief unheimlich gut.$"
	.endif
	.endif

gText_WorkedHardAsStandoutMon::
	.ifdef ENGLISH
	.string "It worked as hard as the\n"
	.string "standout POKéMON.$"
	.else
	.ifdef GERMAN
	.string "Es strengte sich genauso\n"
	.string "wie das beste POKéMON an.$"
	.endif
	.endif

gText_JudgedLookedOnExpectantly::
	.ifdef ENGLISH
	.string "The JUDGE looked on\n"
	.string "expectantly.$"
	.else
	.ifdef GERMAN
	.string "Der JUROR schaute es\n"
	.string "besonders aufmerksam an.$"
	.endif
	.endif

gText_WorkedRatherWell::
	.ifdef ENGLISH
	.string "It worked rather well.$"
	.else
	.ifdef GERMAN
	.string "Das lief bedeutend\n"
	.string "besser.$"
	.endif
	.endif

gText_WorkedLittleBetterThanUsual::
	.ifdef ENGLISH
	.string "It worked a little better\n"
	.string "than usual.$"
	.else
	.ifdef GERMAN
	.string "Es lief etwas besser\n"
	.string "als sonst.$"
	.endif
	.endif

@ Round result texts

gText_MonFailedToStandOutAtAll::
	.ifdef ENGLISH
	.string "{STR_VAR_1} failed to\n"
	.string "stand out at all…{PAUSE_UNTIL_PRESS}$"
	.else
	.ifdef GERMAN
	.string "{STR_VAR_1} stach\n"
	.string "überhaupt nicht hervor…{PAUSE_UNTIL_PRESS}$"
	.endif
	.endif

gText_MonDidntStandOutVeryMuch::
	.ifdef ENGLISH
	.string "{STR_VAR_1} didn't stand\n"
	.string "out very much…{PAUSE_UNTIL_PRESS}$"
	.else
	.ifdef GERMAN
	.string "{STR_VAR_1} stach nicht\n"
	.string "besonders hervor…{PAUSE_UNTIL_PRESS}$"
	.endif
	.endif

gText_MonCaughtALittleAttention::
	.ifdef ENGLISH
	.string "{STR_VAR_1} caught a\n"
	.string "little attention.{PAUSE_UNTIL_PRESS}$"
	.else
	.ifdef GERMAN
	.string "{STR_VAR_1} erregte ein\n"
	.string "wenig Aufmerksamkeit.{PAUSE_UNTIL_PRESS}$"
	.endif
	.endif

gText_MonAttractedALotOfAttention::
	.ifdef ENGLISH
	.string "{STR_VAR_1} attracted a\n"
	.string "lot of attention.{PAUSE_UNTIL_PRESS}$"
	.else
	.ifdef GERMAN
	.string "{STR_VAR_1} erregte eine\n"
	.string "Menge Aufmerksamkeit.{PAUSE_UNTIL_PRESS}$"
	.endif
	.endif

gText_MonCommandedTotalAttention::
	.ifdef ENGLISH
	.string "{STR_VAR_1} commanded\n"
	.string "total attention.{PAUSE_UNTIL_PRESS}$"
	.else
	.ifdef GERMAN
	.string "{STR_VAR_1} erhielt die\n"
	.string "volle Aufmerksamkeit.{PAUSE_UNTIL_PRESS}$"
	.endif
	.endif

gText_MonHasntMadeItsAppeal::
	.ifdef ENGLISH
	.string "{STR_VAR_1} hasn't made\n"
	.string "its appeal.{PAUSE_UNTIL_PRESS}$"
	.else
	.ifdef GERMAN
	.string "{STR_VAR_1} konnte\n"
	.string "keinen Ausdruck zeigen.{PAUSE_UNTIL_PRESS}$"
	.endif
	.endif

@ Unused
gText_AnticipationSwelledForMonsAppealNext2::
	.string "Anticipation swelled for\n"
	.string "{STR_VAR_1}'s appeal next.$"

gText_EmptyContestString::
	.string "$"

gText_JudgesViewsOnMonHeldFirm::
	.ifdef ENGLISH
	.string "The JUDGE 's views on\n"
	.string "{STR_VAR_1} held firm.$"
	.else
	.ifdef GERMAN
	.string "Der JUROR behält\n"
	.string "{STR_VAR_1} fest im Blick.$"
	.endif
	.endif

gText_MonsXChangedPerceptions::
	.ifdef ENGLISH
	.string "{STR_VAR_1}'s {STR_VAR_3}\n"
	.string "changed perceptions.$"
	.else
	.ifdef GERMAN
	.string "{STR_VAR_3} von {STR_VAR_1}\n"
	.string "ändert die Wahrnehmung.$"
	.endif
	.endif

gText_MonsAppealEffectWoreOff::
	.ifdef ENGLISH
	.string "{STR_VAR_1}'s appeal\n"
	.string "effect wore off.$"
	.else
	.ifdef GERMAN
	.string "Wirkung von {STR_VAR_1}\n"
	.string "lässt nach.$"
	.endif
	.endif

gText_SpecialAppealsEffectWoreOff::
	.ifdef ENGLISH
	.string "The special appeal's\n"
	.string "effect wore off.$"
	.else
	.ifdef GERMAN
	.string "Die besondere Wirkung\n"
	.string "lässt nach.$"
	.endif
	.endif

gText_EveryonesAppealsMadeToLookSame::
	.ifdef ENGLISH
	.string "Everyone's appeals were\n"
	.string "made to look the same.$"
	.else
	.ifdef GERMAN
	.string "Jeder Ausdruck wird sich\n"
	.string "nun gleichen.$"
	.endif
	.endif

gText_CheapenedMonsAppeal::
	.ifdef ENGLISH
	.string "It cheapened\n"
	.string "{STR_VAR_2}'s appeal.$"
	.else
	.ifdef GERMAN
	.string "Ausdruck von {STR_VAR_2}\n"
	.string "wurde abgewertet.$"
	.endif
	.endif

gText_CheapenedAppealOfThoseAhead::
	.ifdef ENGLISH
	.string "It cheapened the appeal\n"
	.string "of those ahead.$"
	.else
	.ifdef GERMAN
	.string "Es wertete die Ausdrücke\n"
	.string "der anderen PKMN ab.$"
	.endif
	.endif

gText_StoleAttentionAwayFromMon::
	.ifdef ENGLISH
	.string "It stole attention away\n"
	.string "from {STR_VAR_2}.$"
	.else
	.ifdef GERMAN
	.string "Es stahl {STR_VAR_2} die\n"
	.string "Aufmerksamkeit.$"
	.endif
	.endif

gText_CheapenedMonsAppeal2::
	.ifdef ENGLISH
	.string "It cheapened\n"
	.string "{STR_VAR_2}'s appeal.$"
	.else
	.ifdef GERMAN
	.string "Ausdruck von {STR_VAR_2}\n"
	.string "wurde abgewertet.$"
	.endif
	.endif

gText_SeverelyCheapenedOtherAppeals::
	.ifdef ENGLISH
	.string "It severely cheapened\n"
	.string "other appeals.$"
	.else
	.ifdef GERMAN
	.string "Es wertete die Ausdrücke\n"
	.string "der anderen stark ab.$"
	.endif
	.endif

gText_AnticipationSwelledForMonsAppealNext::
	.ifdef ENGLISH
	.string "Anticipation swelled for\n"
	.string "{STR_VAR_1}'s appeal next.$"
	.else
	.ifdef GERMAN
	.string "Heiß ersehnt: Der Aus-\n"
	.string "druck von {STR_VAR_1}.$"
	.endif
	.endif

gText_CheapenedAppealOfThoseAhead2::
	.ifdef ENGLISH
	.string "It cheapened the appeal\n"
	.string "of those ahead.$"
	.else
	.ifdef GERMAN
	.string "Es wertete den Ausdruck\n"
	.string "der PKMN vor ihm ab.$"
	.endif
	.endif

gText_CheapenedJudgesFavoriteAppeal::
	.ifdef ENGLISH
	.string "It cheapened the JUDGE's\n"
	.string "favorite appeal.$"
	.else
	.ifdef GERMAN
	.string "Es wertete den Lieblings-\n"
	.string "ausdruck des JURORS ab.$"
	.endif
	.endif

gText_AppealsOfOthersCheapenedByHalf::
	.ifdef ENGLISH
	.string "The appeals of others\n"
	.string "were cheapened by half.$"
	.else
	.ifdef GERMAN
	.string "Der Ausdruckswert der\n"
	.string "anderen wurde halbiert.$"
	.endif
	.endif

gText_StoodOutToMakeUpForBeingJammed::
	.ifdef ENGLISH
	.string "It stood out to make up\n"
	.string "for being jammed.$"
	.else
	.ifdef GERMAN
	.string "Es macht sich bereit, die\n"
	.string "anderen zu beeindrucken.$"
	.endif
	.endif

gText_CantParticipateInAppealsAnyMore::
	.ifdef ENGLISH
	.string "It can't participate in\n"
	.string "appeals any more.$"
	.else
	.ifdef GERMAN
	.string "Es kann an keiner Vor-\n"
	.string "führung mehr teilnehmen.$"
	.endif
	.endif

gText_TouchedJudgeForFantasticAppeal::
	.ifdef ENGLISH
	.string "It touched the JUDGE for\n"
	.string "a fantastic appeal.$"
	.else
	.ifdef GERMAN
	.string "Der fantastische Aus-\n"
	.string "druck berührte den JUROR.$"
	.endif
	.endif

gText_AnticipationRoseForUpcomingAppeals::
	.ifdef ENGLISH
	.string "Anticipation rose for\n"
	.string "upcoming appeals.$"
	.else
	.ifdef GERMAN
	.string "Die Erwartung für die fol-\n"
	.string "genden Ausdrücke steigt.$"
	.endif
	.endif

gText_StoodOutAsMuchAsSpecialAppeals::
	.ifdef ENGLISH
	.string "It stood out as much as\n"
	.string "special appeals.$"
	.else
	.ifdef GERMAN
	.string "Es war so beeindruckend\n"
	.string "wie ein Spezialausdruck.$"
	.endif
	.endif

gText_StoodOutAsMuchAsMon::
	.ifdef ENGLISH
	.string "It stood out as much as\n"
	.string "{STR_VAR_1}.$"
	.else
	.ifdef GERMAN
	.string "Es war so beeindruckend\n"
	.string "wie {STR_VAR_1}.$"
	.endif
	.endif

gText_JammedAppealsMadeEvenLessNoticeable::
	.ifdef ENGLISH
	.string "Jammed appeals were made\n"
	.string "even less noticeable.$"
	.else
	.ifdef GERMAN
	.string "Ein Ausdruck, der gestört\n"
	.string "wurde, ist unauffälliger.$"
	.endif
	.endif

gText_EveryonesAppealsMadeSame::
	.ifdef ENGLISH
	.string "Everyone's appeals were\n"
	.string "made the same.$"
	.else
	.ifdef GERMAN
	.string "Jeder Teilnehmer hat nun\n"
	.string "den gleichen Ausdruck.$"
	.endif
	.endif

@ Appeal result texts

gText_BecameMoreConsciousOfOtherMons::
	.ifdef ENGLISH
	.string "It became more conscious\n"
	.string "of the other POKéMON.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"
	.else
	.ifdef GERMAN
	.string "Es wird sich der anderen\n"
	.string "PKMN mehr bewusst.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"
	.endif
	.endif

gText_MonCantMakeAnAppealAfterThis::
	.ifdef ENGLISH
	.string "{STR_VAR_1} can't make an\n"
	.string "appeal after this.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"
	.else
	.ifdef GERMAN
	.string "{STR_VAR_1} kann danach\n"
	.string "keinen Ausdruck zeigen.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"
	.endif
	.endif

gText_SettledDownJustLittleBit::
	.ifdef ENGLISH
	.string "It settled down just a\n"
	.string "little bit.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"
	.else
	.ifdef GERMAN
	.string "Es kommt ein wenig\n"
	.string "zur Ruhe.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"
	.endif
	.endif

gText_BecameObliviousToOtherMons::
	.ifdef ENGLISH
	.string "It became oblivious to\n"
	.string "the other POKéMON.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"
	.else
	.ifdef GERMAN
	.string "Die anderen PKMN nehmen\n"
	.string "es überhaupt nicht wahr.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"
	.endif
	.endif

gText_BecameLessAwareOfOtherMons::
	.ifdef ENGLISH
	.string "It became less aware of\n"
	.string "the other POKéMON.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"
	.else
	.ifdef GERMAN
	.string "Es ist sich der anderen\n"
	.string "PKMN kaum bewusst.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"
	.endif
	.endif

gText_StoppedCaringAboutOtherMons::
	.ifdef ENGLISH
	.string "It stopped caring about\n"
	.string "other POKéMON much.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"
	.else
	.ifdef GERMAN
	.string "Es kümmert sich nicht\n"
	.string "mehr viel um andere PKMN.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"
	.endif
	.endif

gText_TriedToStartleOtherMons::
	.ifdef ENGLISH
	.string "It tried to startle the\n"
	.string "other POKéMON.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"
	.else
	.ifdef GERMAN
	.string "Es versucht, die anderen\n"
	.string "PKMN zu erschrecken.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"
	.endif
	.endif

gText_TriedToDazzleOthers::
	.ifdef ENGLISH
	.string "It tried to dazzle the\n"
	.string "others.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"
	.else
	.ifdef GERMAN
	.string "Es versucht, die anderen\n"
	.string "PKMN zu blenden.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"
	.endif
	.endif

gText_JudgeLookedAwayFromMon::
	.ifdef ENGLISH
	.string "The JUDGE looked away\n"
	.string "from {STR_VAR_1}.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"
	.else
	.ifdef GERMAN
	.string "Der JUROR schaut\n"
	.string "{STR_VAR_1} nicht mehr an.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"
	.endif
	.endif

gText_TriedToUnnerveNextMon::
	.ifdef ENGLISH
	.string "It tried to unnerve the\n"
	.string "next POKéMON.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"
	.else
	.ifdef GERMAN
	.string "Es versucht, d. folgenden\n"
	.string "PKMN zu entnerven.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"
	.endif
	.endif

gText_MonBecameNervous::
	.ifdef ENGLISH
	.string "{STR_VAR_1} became\n"
	.string "nervous.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"
	.else
	.ifdef GERMAN
	.string "{STR_VAR_1} wird\n"
	.string "nervös.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"
	.endif
	.endif

gText_AppealTriedToUnnerveWaitingMons::
	.ifdef ENGLISH
	.string "The appeal tried to\n"
	.string "unnerve waiting POKéMON.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"
	.else
	.ifdef GERMAN
	.string "Dieser Ausdruck soll die\n"
	.string "anderen PKMN entnerven.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"
	.endif
	.endif

gText_TauntedMonsDoingWell::
	.ifdef ENGLISH
	.string "It taunted POKéMON\n"
	.string "doing well.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"
	.else
	.ifdef GERMAN
	.string "Es verhöhnt die\n"
	.string "besseren PKMN.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"
	.endif
	.endif

gText_MonRegainedItsForm::
	.ifdef ENGLISH
	.string "{STR_VAR_1} regained its\n"
	.string "form.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"
	.else
	.ifdef GERMAN
	.string "{STR_VAR_1} findet zu\n"
	.string "seiner Form zurück.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"
	.endif
	.endif

gText_TriedToJamMonDoingWell::
	.ifdef ENGLISH
	.string "It tried to jam POKéMON\n"
	.string "doing well.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"
	.else
	.ifdef GERMAN
	.string "Es versucht, die besseren\n"
	.string "PKMN zu beeindrucken.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"
	.endif
	.endif

gText_StandoutMonHustledEvenMore::
	.ifdef ENGLISH
	.string "The standout {STR_VAR_1}\n"
	.string "hustled even more.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"
	.else
	.ifdef GERMAN
	.string "{STR_VAR_1} an der Spitze\n"
	.string "engagiert sich noch mehr.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"
	.endif
	.endif

gText_LargelyUnnoticedMonWorkedHard::
	.ifdef ENGLISH
	.string "The largely unnoticed\n"
	.string "{STR_VAR_1} worked hard.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"
	.else
	.ifdef GERMAN
	.string "Das bisher unauffällige\n"
	.string "{STR_VAR_1} gibt alles.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"
	.endif
	.endif

gText_WorkedAsMuchAsMonBefore::
	.ifdef ENGLISH
	.string "It worked as much as\n"
	.string "POKéMON before it.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"
	.else
	.ifdef GERMAN
	.string "Es strengt sich genauso\n"
	.string "an wie die PKMN vor ihm.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"
	.endif
	.endif

gText_MonsAppealDidNotGoWell::
	.ifdef ENGLISH
	.string "{STR_VAR_1}'s appeal did\n"
	.string "not go well.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"
	.else
	.ifdef GERMAN
	.string "Ausdruck von {STR_VAR_1}:\n"
	.string "Kam nicht gut an.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"
	.endif
	.endif

gText_WorkedAsMuchAsPrecedingMon::
	.ifdef ENGLISH
	.string "It worked as much as the\n"
	.string "preceding POKéMON.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"
	.else
	.ifdef GERMAN
	.string "Es strengt sich an wie die\n"
	.string "vorangegangenen PKMN.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"
	.endif
	.endif

gText_MonsAppealDidNotGoWell2::
	.ifdef ENGLISH
	.string "{STR_VAR_1}'s appeal did\n"
	.string "not go well.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"
	.else
	.ifdef GERMAN
	.string "Ausdruck von {STR_VAR_1}:\n"
	.string "Verlief nicht so gut.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"
	.endif
	.endif

gText_MonsAppealDidNotGoWell3::
	.ifdef ENGLISH
	.string "{STR_VAR_1}'s appeal did\n"
	.string "not go well.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"
	.else
	.ifdef GERMAN
	.string "Ausdruck von {STR_VAR_1}:\n"
	.string "Verlief nicht so gut.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"
	.endif
	.endif

gText_MonsAppealWentSlightlyWell::
	.ifdef ENGLISH
	.string "{STR_VAR_1}'s appeal\n"
	.string "went slightly well.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"
	.else
	.ifdef GERMAN
	.string "Ausdruck von {STR_VAR_1}:\n"
	.string "Verlief ganz gut.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"
	.endif
	.endif

gText_MonsAppealWentPrettyWell::
	.ifdef ENGLISH
	.string "{STR_VAR_1}'s appeal\n"
	.string "went pretty well.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"
	.else
	.ifdef GERMAN
	.string "Ausdruck von {STR_VAR_1}:\n"
	.string "Kam ganz gut an.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"
	.endif
	.endif

gText_MonsAppealWentExcellently::
	.ifdef ENGLISH
	.string "{STR_VAR_1}'s appeal\n"
	.string "went excellently.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"
	.else
	.ifdef GERMAN
	.string "{STR_VAR_1} führte seinen\n"
	.string "Ausdruck exzellent vor.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"
	.endif
	.endif

gText_MonsAppealWasDud::
	.ifdef ENGLISH
	.string "{STR_VAR_1}'s appeal was\n"
	.string "a dud.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"
	.else
	.ifdef GERMAN
	.string "Ausdruck von {STR_VAR_1}:\n"
	.string "Er war absolut mies.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"
	.endif
	.endif

gText_MonsAppealDidNotWorkVeryWell::
	.ifdef ENGLISH
	.string "{STR_VAR_1}'s appeal did\n"
	.string "not work very well.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"
	.else
	.ifdef GERMAN
	.string "Ausdruck von {STR_VAR_1}:\n"
	.string "Er war nicht so gut.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"
	.endif
	.endif

gText_MonsAppealWentSlightlyWell2::
	.ifdef ENGLISH
	.string "{STR_VAR_1}'s appeal\n"
	.string "went slightly well.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"
	.else
	.ifdef GERMAN
	.string "Ausdruck von {STR_VAR_1}:\n"
	.string "Verlief ganz gut.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"
	.endif
	.endif

gText_MonsAppealWentPrettyWell2::
	.ifdef ENGLISH
	.string "{STR_VAR_1}'s appeal\n"
	.string "went pretty well.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"
	.else
	.ifdef GERMAN
	.string "Ausdruck von {STR_VAR_1}:\n"
	.string "Kam ganz gut an.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"
	.endif
	.endif

gText_MonsAppealWentVeryWell::
	.ifdef ENGLISH
	.string "{STR_VAR_1}'s appeal\n"
	.string "went very well.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"
	.else
	.ifdef GERMAN
	.string "Ausdruck von {STR_VAR_1}:\n"
	.string "Er war sehr gut.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"
	.endif
	.endif

gText_MonsAppealWentExcellently2::
	.ifdef ENGLISH
	.string "{STR_VAR_1}'s appeal\n"
	.string "went excellently.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"
	.else
	.ifdef GERMAN
	.string "{STR_VAR_1} führte seinen\n"
	.string "Ausdruck exzellent vor.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"
	.endif
	.endif

gText_SameTypeAsOneBeforeGood::
	.ifdef ENGLISH
	.string "It's the same type as the\n"
	.string "POKéMON before--good!{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"
	.else
	.ifdef GERMAN
	.string "Der gleiche Typ wie das\n"
	.string "vorhergehende PKMN. Gut!{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"
	.endif
	.endif

gText_NotSameTypeAsOneBeforeGood::
	.ifdef ENGLISH
	.string "It's not the same type as\n"
	.string "the one before--good!{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"
	.else
	.ifdef GERMAN
	.string "Nicht der gleiche Typ wie\n"
	.string "das vorherige PKMN - gut!{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"
	.endif
	.endif

gText_StoodOutMuchMoreThanMonBefore::
	.ifdef ENGLISH
	.string "It stood out much more\n"
	.string "than the POKéMON before.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"
	.else
	.ifdef GERMAN
	.string "Es ist viel besser als die\n"
	.string "vorhergehenden PKMN.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"
	.endif
	.endif

gText_DidntDoAsWellAsMonBefore::
	.ifdef ENGLISH
	.string "It didn't do as well as the\n"
	.string "POKéMON before.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"
	.else
	.ifdef GERMAN
	.string "Es war nicht so gut wie\n"
	.string "das PKMN vor ihm.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"
	.endif
	.endif

gText_MonsConditionRoseAboveUsual::
	.ifdef ENGLISH
	.string "{STR_VAR_1}'s condition\n"
	.string "rose above usual.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"
	.else
	.ifdef GERMAN
	.string "Die Kondition von\n"
	.string "{STR_VAR_1} stieg.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"
	.endif
	.endif

gText_MonsHotStatusMadeGreatAppeal::
	.ifdef ENGLISH
	.string "{STR_VAR_1}'s hot status\n"
	.string "made it a great appeal!{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"
	.else
	.ifdef GERMAN
	.string "Status von {STR_VAR_1}:\n"
	.string "Bewirkt guten Ausdruck!{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"
	.endif
	.endif

gText_MovedUpInLineForNextAppeal::
	.ifdef ENGLISH
	.string "It moved up in line for\n"
	.string "the next appeal.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"
	.else
	.ifdef GERMAN
	.string "Es steigt in der Reihen-\n"
	.string "folge auf.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"
	.endif
	.endif

gText_MovedBackInLineForNextAppeal::
	.ifdef ENGLISH
	.string "It moved back in line once\n"
	.string "for the next appeal.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"
	.else
	.ifdef GERMAN
	.string "Es fällt in der Reihen-\n"
	.string "folge zurück.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"
	.endif
	.endif

gText_ScrambledUpOrderForNextTurn::
	.ifdef ENGLISH
	.string "It scrambled up the\n"
	.string "order for the next turn.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"
	.else
	.ifdef GERMAN
	.string "Es bringt die Reihenfolge\n"
	.string "durcheinander.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"
	.endif
	.endif

gText_JudgeLookedAtMonExpectantly::
	.ifdef ENGLISH
	.string "The JUDGE looked at\n"
	.string "{STR_VAR_1} expectantly.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"
	.else
	.ifdef GERMAN
	.string "Der JUROR betrachtet\n"
	.string "{STR_VAR_1} interessiert.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"
	.endif
	.endif

gText_AppealComboWentOverWell::
	.ifdef ENGLISH
	.string "The appeal combo went\n"
	.string "over well.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"
	.else
	.ifdef GERMAN
	.string "Die Combo der Ausdrücke\n"
	.string "kam gut an.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"
	.endif
	.endif

gText_AppealComboWentOverVeryWell::
	.ifdef ENGLISH
	.string "The appeal combo went\n"
	.string "over very well.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"
	.else
	.ifdef GERMAN
	.string "Die Combo der Ausdrücke\n"
	.string "kam sehr gut an.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"
	.endif
	.endif

gText_AppealComboWentOverExcellently::
	.ifdef ENGLISH
	.string "The appeal combo went\n"
	.string "over excellently.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"
	.else
	.ifdef GERMAN
	.string "Die Combo der Ausdrücke\n"
	.string "kam exzellent an.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"
	.endif
	.endif

gText_MonManagedToAvertGaze::
	.ifdef ENGLISH
	.string "{STR_VAR_1} managed to\n"
	.string "avert its gaze.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"
	.else
	.ifdef GERMAN
	.string "{STR_VAR_1} gelingt es,\n"
	.string "den Blick abzuwenden.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"
	.endif
	.endif

gText_MonManagedToAvoidSeeingIt::
	.ifdef ENGLISH
	.string "{STR_VAR_1} managed to\n"
	.string "avoid seeing it.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"
	.else
	.ifdef GERMAN
	.string "{STR_VAR_1} wandte den\n"
	.string "Blick erfolgreich ab.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"
	.endif
	.endif

gText_MonIsntFazedByThatSortOfThing::
	.ifdef ENGLISH
	.string "{STR_VAR_1} isn't fazed\n"
	.string "by that sort of thing.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"
	.else
	.ifdef GERMAN
	.string "{STR_VAR_1} lässt sich\n"
	.string "davon nicht ablenken.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"
	.endif
	.endif

gText_MonBecameALittleDistracted::
	.ifdef ENGLISH
	.string "{STR_VAR_1} became a\n"
	.string "little distracted.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"
	.else
	.ifdef GERMAN
	.string "{STR_VAR_1} wurde etwas\n"
	.string "unruhig.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"
	.endif
	.endif

gText_TriedToStartleOtherPokemon::
	.ifdef ENGLISH
	.string "It tried to startle the\n"
	.string "other POKéMON.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"
	.else
	.ifdef GERMAN
	.string "Es versucht, die anderen\n"
	.string "PKMN zu erschrecken.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"
	.endif
	.endif

gText_MonLookedDownOutOfDistraction::
	.ifdef ENGLISH
	.string "{STR_VAR_1} looked down\n"
	.string "out of distraction.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"
	.else
	.ifdef GERMAN
	.string "{STR_VAR_1} blickt\n"
	.string "irritiert zu Boden.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"
	.endif
	.endif

gText_MonTurnedBackOutOfDistraction::
	.ifdef ENGLISH
	.string "{STR_VAR_1} turned back\n"
	.string "out of distraction.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"
	.else
	.ifdef GERMAN
	.string "{STR_VAR_1} dreht sich\n"
	.string "irritiert um.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"
	.endif
	.endif

gText_MonCouldntHelpUtteringCry::
	.ifdef ENGLISH
	.string "{STR_VAR_1} couldn't help\n"
	.string "uttering a cry.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"
	.else
	.ifdef GERMAN
	.string "{STR_VAR_1} kann einen \n"
	.string "Laut nicht unterdrücken.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"
	.endif
	.endif

gText_MonCouldntHelpLeapingUp::
	.ifdef ENGLISH
	.string "{STR_VAR_1} couldn't help\n"
	.string "leaping up.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"
	.else
	.ifdef GERMAN
	.string "{STR_VAR_1} kann nicht\n"
	.string "anders und springt auf.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"
	.endif
	.endif

gText_MonTrippedOutOfDistraction::
	.ifdef ENGLISH
	.string "{STR_VAR_1} tripped over\n"
	.string "out of distraction.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"
	.else
	.ifdef GERMAN
	.string "{STR_VAR_1} ist so irri-\n"
	.string "tiert, dass es stolpert.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"
	.endif
	.endif

gText_MonWasTooNervousToMove::
	.ifdef ENGLISH
	.string "{STR_VAR_1} was too\n"
	.string "nervous to move.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"
	.else
	.ifdef GERMAN
	.string "{STR_VAR_1} ist zu nervös,\n"
	.string "um etwas vorzuführen.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"
	.endif
	.endif

gText_ButItMessedUp2::
	.ifdef ENGLISH
	.string "But it messed up.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"
	.else
	.ifdef GERMAN
	.string "Es hatte keinen Erfolg.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"
	.endif
	.endif

gText_ButItFailedToMakeTargetNervous::
	.ifdef ENGLISH
	.string "But it failed to make\n"
	.string "the target nervous.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"
	.else
	.ifdef GERMAN
	.string "Es konnte keine\n"
	.string "Nervosität erzeugen.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"
	.endif
	.endif

gText_ButItFailedToMakeAnyoneNervous::
	.ifdef ENGLISH
	.string "But it failed to make\n"
	.string "anyone nervous.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"
	.else
	.ifdef GERMAN
	.string "Aber es konnte niemanden\n"
	.string "nervös machen.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"
	.endif
	.endif

gText_ButItWasIgnored::
	.ifdef ENGLISH
	.string "But it was ignored…{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"
	.else
	.ifdef GERMAN
	.string "Es wurde ignoriert…{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"
	.endif
	.endif

gText_CouldntImproveItsCondition::
	.ifdef ENGLISH
	.string "But it couldn't improve\n"
	.string "its condition…{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"
	.else
	.ifdef GERMAN
	.string "Es konnte seinen Aus-\n"
	.string "druck nicht verstärken…{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"
	.endif
	.endif

gText_BadConditionResultedInWeakAppeal::
	.ifdef ENGLISH
	.string "Its bad condition\n"
	.string "resulted in a weak appeal.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"
	.else
	.ifdef GERMAN
	.string "Schwacher Ausdruck we-\n"
	.string "gen schlechter Kondition.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"
	.endif
	.endif

gText_MonWasUnaffected::
	.ifdef ENGLISH
	.string "{STR_VAR_1} was\n"
	.string "unaffected.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"
	.else
	.ifdef GERMAN
	.string "{STR_VAR_1} blieb\n"
	.string "unbeeindruckt.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"
	.endif
	.endif

gText_RepeatedAppeal::
	.ifdef ENGLISH
	.string "{STR_VAR_1} disappointed\n"
	.string "by repeating an appeal.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"
	.else
	.ifdef GERMAN
	.string "{STR_VAR_1} enttäuscht\n"
	.string "durch Wiederholung.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"
	.endif
	.endif

gText_MonsXWentOverGreat::
	.ifdef ENGLISH
	.string "{STR_VAR_1}'s {STR_VAR_3}\n"
	.string "went over great.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"
	.else
	.ifdef GERMAN
	.string "Die {STR_VAR_3} von\n"
	.string "{STR_VAR_1} war sehr gut.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"
	.endif
	.endif

gText_MonsXDidntGoOverWell::
	.ifdef ENGLISH
	.string "{STR_VAR_1}'s {STR_VAR_3}\n"
	.string "didn't go over well here…{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"
	.else
	.ifdef GERMAN
	.string "Die {STR_VAR_3} von\n"
	.string "{STR_VAR_1} war nicht gut.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"
	.endif
	.endif

gText_MonsXGotTheCrowdGoing::
	.ifdef ENGLISH
	.string "{STR_VAR_1}'s {STR_VAR_3}\n"
	.string "got the crowd going.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"
	.else
	.ifdef GERMAN
	.string "{STR_VAR_1} begeistert\n"
	.string "Publikum mit {STR_VAR_3}.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"
	.endif
	.endif

gText_MonCantAppealNextTurn::
	.ifdef ENGLISH
	.string "{STR_VAR_1} can't appeal\n"
	.string "next turn…{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"
	.else
	.ifdef GERMAN
	.string "{STR_VAR_1} setzt in der \n"
	.string "folgenden Runde aus.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"
	.endif
	.endif

gText_AttractedCrowdsAttention::
	.ifdef ENGLISH
	.string "It attracted the crowd's\n"
	.string "attention.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"
	.else
	.ifdef GERMAN
	.string "Die Aufmerksamkeit des\n"
	.string "Publikums liegt auf ihm.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"
	.endif
	.endif

gText_CrowdContinuesToWatchMon::
	.ifdef ENGLISH
	.string "The crowd continues to\n"
	.string "watch {STR_VAR_3}.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"
	.else
	.ifdef GERMAN
	.string "Das Publikum beobachtet\n"
	.string "weiterhin {STR_VAR_3}.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"
	.endif
	.endif

gText_MonsMoveIsIgnored::
	.ifdef ENGLISH
	.string "{STR_VAR_1}'s\n"
	.string "{STR_VAR_2} is ignored.{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}{PAUSE 0x0F}$"
	.else
	.ifdef GERMAN
	.string "{STR_VAR_2} von\n"
	.string "{STR_VAR_1} sah keiner.{PAUSE 15}{PAUSE 15}{PAUSE 15}{PAUSE 15}$"
	.endif
	.endif

gText_Contest_Shyness::
	.ifdef ENGLISH
	.string "shyness$"
	.else
	.ifdef GERMAN
	.string "Scheu$"
	.endif
	.endif

gText_Contest_Anxiety::
	.ifdef ENGLISH
	.string "anxiety$"
	.else
	.ifdef GERMAN
	.string "Besorgnis$"
	.endif
	.endif

gText_Contest_Laziness::
	.ifdef ENGLISH
	.string "laziness$"
	.else
	.ifdef GERMAN
	.string "Faulheit$"
	.endif
	.endif

gText_Contest_Hesitancy::
	.ifdef ENGLISH
	.string "hesitancy$"
	.else
	.ifdef GERMAN
	.string "Zögern$"
	.endif
	.endif

gText_Contest_Fear::
	.ifdef ENGLISH
	.string "fear$"
	.else
	.ifdef GERMAN
	.string "Furcht$"
	.endif
	.endif

gText_Contest_Coolness::
	.ifdef ENGLISH
	.string "coolness$"
	.else
	.ifdef GERMAN
	.string "Coolness$"
	.endif
	.endif

gText_Contest_Beauty::
	.ifdef ENGLISH
	.string "beauty$"
	.else
	.ifdef GERMAN
	.string "Schönheit$"
	.endif
	.endif

gText_Contest_Cuteness::
	.ifdef ENGLISH
	.string "cuteness$"
	.else
	.ifdef GERMAN
	.string "Anmut$"
	.endif
	.endif

gText_Contest_Smartness::
	.ifdef ENGLISH
	.string "smartness$"
	.else
	.ifdef GERMAN
	.string "Klugheit$"
	.endif
	.endif

gText_Contest_Toughness::
	.ifdef ENGLISH
	.string "toughness$"
	.else
	.ifdef GERMAN
	.string "Stärke$"
	.endif
	.endif

@ Unused
gText_Tension::
	.string "TENSION$"

gText_CoolMove::
	.ifdef ENGLISH
	.string "COOL Move$"
	.else
	.ifdef GERMAN
	.string "COOLE Att.$"
	.endif
	.endif

gText_BeautyMove::
	.ifdef ENGLISH
	.string "BEAUTY Move$"
	.else
	.ifdef GERMAN
	.string "SCHÖNE Att.$"
	.endif
	.endif

gText_CuteMove::
	.ifdef ENGLISH
	.string "CUTE Move$"
	.else
	.ifdef GERMAN
	.string "ANMUT-Att.$"
	.endif
	.endif

gText_SmartMove::
	.ifdef ENGLISH
	.string "SMART Move$"
	.else
	.ifdef GERMAN
	.string "KLUGE Att.$"
	.endif
	.endif

gText_ToughMove::
	.ifdef ENGLISH
	.string "TOUGH Move$"
	.else
	.ifdef GERMAN
	.string "STARKE Att.$"
	.endif
	.endif

gText_3QuestionMarks::
	.ifdef ENGLISH
	.string "???$"
	.else
	.ifdef GERMAN
	.string "{STR_VAR_1}$"
	.endif
	.endif
