EventTicket_Text_ShowOldSeaMap:
	.ifdef ENGLISH
	.string "The ferry to SLATEPORT is…\p"
	.string "I beg your pardon?\n"
	.string "Can we sail to this place on the map?\p"
	.string "I know someone who will help you better.\n"
	.string "Please wait.$"
	.else
	.ifdef GERMAN
	.string "Die Fähre nach GRAPHITPORT ist…\p"
	.string "Verzeihung? Ob wir zu diesem Ort, der\n"
	.string "auf der Karte eingezeichnet ist,\l"
	.string "fahren können?\p"
	.string "Ich rufe jemanden, der dir weiterhelfen\n"
	.string "kann. Bitte warte einen Moment.$"
	.endif
	.endif

EventTicket_Text_ThatPass:
	.ifdef ENGLISH
	.string "The ferry to SLATEPORT is…\p"
	.string "Oh?\n"
	.string "That PASS…$"
	.else
	.ifdef GERMAN
	.string "Die Fähre nach GRAPHITPORT CITY ist…\p"
	.string "Oh!\n"
	.string "Der FAHRSCHEIN…$"
	.endif
	.endif

EventTicket_Text_ShowEonTicket:
	.ifdef ENGLISH
	.string "Aye, mate, are you the one who brought\n"
	.string "that mighty odd PASS?\p"
	.string "I'll tell you, you're trying to reach a\n"
	.string "tiny spit of an island far in the south.\p"
	.string "There's no telling what we'll encounter\n"
	.string "once we reach there, aye.\l"
	.string "That shivers my timbers!\p"
	.string "All aboard!$"
	.else
	.ifdef GERMAN
	.string "Aye, Maat, hast du den alten FAHRSCHEIN\n"
	.string "mitgebracht?\p"
	.string "Ich sage dir, du bist auf dem Weg zu\n"
	.string "einer briefmarkengroßen Insel im Süden.\p"
	.string "Niemand kann sagen, was uns dort er-\n"
	.string "warten wird, aye. Und das erschüttert\l"
	.string "meine alten Knochen!\p"
	.string "Alle Mann an Bord!$"
	.endif
	.endif

EventTicket_Text_SouthernIslandSailBack:
	.ifdef ENGLISH
	.string "Aye, mate, there's nothing here to\n"
	.string "see or do on this forgettable island.\p"
	.string "What say we sail back to LILYCOVE?$"
	.else
	.ifdef GERMAN
	.string "Aye, Maat, auf dieser gottverlassenen\n"
	.string "Insel gibt’s nichts zu sehen und zu tun.\p"
	.string "Sollen wir nicht nach SEEGRASULB CITY\n"
	.string "zurücksegeln?$"
	.endif
	.endif

EventTicket_Text_SailHome:
	.ifdef ENGLISH
	.string "Aye, right, then!\n"
	.string "Sail home we will!$"
	.else
	.ifdef GERMAN
	.string "Aye, alles klar!\n"
	.string "Segeln wir nach Hause!$"
	.endif
	.endif

EventTicket_Text_AsYouLike:
	.ifdef ENGLISH
	.string "Aye, right, as you like, then.$"
	.else
	.ifdef GERMAN
	.string "Aye, ganz wie du willst.$"
	.endif
	.endif

SouthernIsland_Interior_Text_Sign:
	.ifdef ENGLISH
	.string "“All dreams are but another reality.\n"
	.string "Never forget…”$"
	.else
	.ifdef GERMAN
	.string "“Alle Träume sind nur eine andere\n"
	.string "Realität. Vergiss das nicht…”$"
	.endif
	.endif

SouthernIsland_Exterior_Text_Sign:
	.ifdef ENGLISH
	.string "“Those whose memories fade seek to\n"
	.string "carve them in their hearts…”$"
	.else
	.ifdef GERMAN
	.string "“Die, denen die Erinnerung verblasst,\n"
	.string "versuchen, sie im Herzen zu halten.”$"
	.endif
	.endif
