@ Battle Tower
gText_AnabelWonSilver::
	.ifdef ENGLISH
	.string "It's very disappointing…$"
	.else
	.ifdef GERMAN
	.string "Das war sehr enttäuschend…$"
	.endif
	.endif

gText_AnabelDefeatSilver::
	.ifdef ENGLISH
	.string "Okay, I understand…$"
	.else
	.ifdef GERMAN
	.string "Ich sehe schon…$"
	.endif
	.endif

gText_AnabelWonGold::
	.ifdef ENGLISH
	.string "I'm terribly sorry…$"
	.else
	.ifdef GERMAN
	.string "Das tut mir sehr Leid…$"
	.endif
	.endif

gText_AnabelDefeatGold::
	.ifdef ENGLISH
	.string "Thank you…$"
	.else
	.ifdef GERMAN
	.string "Vielen Dank…$"
	.endif
	.endif

@ Battle Dome
gText_TuckerWonSilver::
	.ifdef ENGLISH
	.string "Ahahaha! Aren't you embarrassed?\n"
	.string "Everyone's watching!$"
	.else
	.ifdef GERMAN
	.string "Ahahahaha! Ist dir das nicht mehr als\n"
	.string "peinlich? Und das vor den Augen aller!$"
	.endif
	.endif

gText_TuckerDefeatSilver::
	.ifdef ENGLISH
	.string "Grr…\n"
	.string "What the…$"
	.else
	.ifdef GERMAN
	.string "Grrr…\n"
	.string "Was war…$"
	.endif
	.endif

gText_TuckerWonGold::
	.ifdef ENGLISH
	.string "My DOME ACE title isn't just for show!$"
	.else
	.ifdef GERMAN
	.string "Mein STADIONSTAR-Titel ist nicht\n"
	.string "nur Show!$"
	.endif
	.endif

gText_TuckerDefeatGold::
	.ifdef ENGLISH
	.string "Ahahaha!\n"
	.string "You're inspiring!$"
	.else
	.ifdef GERMAN
	.string "Ahahahaha!\n"
	.string "Wie erfrischend und inspirierend!!!$"
	.endif
	.endif

@ Battle Factory
gText_NolandWonSilver::
	.ifdef ENGLISH
	.string "Way to work!\n"
	.string "That was a good lesson, eh?$"
	.else
	.ifdef GERMAN
	.string "Du hast noch viel Arbeit vor dir! Aber\n"
	.string "das war doch eine gute Übung, oder?$"
	.endif
	.endif

gText_NolandDefeatSilver::
	.ifdef ENGLISH
	.string "Good job!\n"
	.string "You know what you're doing!$"
	.else
	.ifdef GERMAN
	.string "Gut gemacht!\n"
	.string "Du weißt genau, was du willst!$"
	.endif
	.endif

gText_NolandWonGold::
	.ifdef ENGLISH
	.string "Hey, hey, hey!\n"
	.string "You're finished already?$"
	.else
	.ifdef GERMAN
	.string "Hey, hey, hey!\n"
	.string "Das war’s schon? Ging ja schnell!$"
	.endif
	.endif

gText_NolandDefeatGold::
	.ifdef ENGLISH
	.string "What happened here?$"
	.else
	.ifdef GERMAN
	.string "Was war das denn?!?$"
	.endif
	.endif

@ Battle Pike
gText_LucyWonSilver::
	.ifdef ENGLISH
	.string "Humph…$"
	.else
	.ifdef GERMAN
	.string "Hmpf…$"
	.endif
	.endif

gText_LucyDefeatSilver::
	.ifdef ENGLISH
	.string "Urk…$"
	.else
	.ifdef GERMAN
	.string "Argh…$"
	.endif
	.endif

gText_LucyWonGold::
	.ifdef ENGLISH
	.string "Hah!$"
	.else
	.ifdef GERMAN
	.string "Hah!$"
	.endif
	.endif

gText_LucyDefeatGold::
	.ifdef ENGLISH
	.string "Darn!$"
	.else
	.ifdef GERMAN
	.string "Mist!$"
	.endif
	.endif

@ Battle Arena
gText_GretaWonSilver::
	.ifdef ENGLISH
	.string "Oh, come on!\n"
	.string "You have to try harder than that!$"
	.else
	.ifdef GERMAN
	.string "Ach, mach schon!\n"
	.string "Streng dich mal ein bisschen an!$"
	.endif
	.endif

gText_GretaDefeatSilver::
	.ifdef ENGLISH
	.string "No way!\n"
	.string "Good job!$"
	.else
	.ifdef GERMAN
	.string "Das gibt’s ja nicht!\n"
	.string "Klasse gemacht!$"
	.endif
	.endif

gText_GretaWonGold::
	.ifdef ENGLISH
	.string "Heheh!\n"
	.string "What did you expect?$"
	.else
	.ifdef GERMAN
	.string "Hähähä!\n"
	.string "Hast du was anderes erwartet?!?$"
	.endif
	.endif

gText_GretaDefeatGold::
	.ifdef ENGLISH
	.string "Huh?\n"
	.string "Are you serious?!$"
	.else
	.ifdef GERMAN
	.string "Was?\n"
	.string "Das ist jetzt nicht dein Ernst, oder?$"
	.endif
	.endif

@ Battle Palace
gText_SpenserWonSilver::
	.ifdef ENGLISH
	.string "Your POKéMON are wimpy because\n"
	.string "you're wimpy as a TRAINER!$"
	.else
	.ifdef GERMAN
	.string "Deine POKéMON passen zu dir! Sie\n"
	.string "sind genauso jämmerlich wie du!$"
	.endif
	.endif

gText_SpenserDefeatSilver::
	.ifdef ENGLISH
	.string "Ah…\n"
	.string "Now this is something else…$"
	.else
	.ifdef GERMAN
	.string "Ah…\n"
	.string "Nun... äh, das war unerwartet…$"
	.endif
	.endif

gText_SpenserWonGold::
	.ifdef ENGLISH
	.string "Gwahahaha!\n"
	.string "My brethren, we have nothing to fear!$"
	.else
	.ifdef GERMAN
	.string "Muahahahaha… Wir haben nichts zu\n"
	.string "befürchten! Uns kann keiner was!$"
	.endif
	.endif

gText_SpenserDefeatGold::
	.ifdef ENGLISH
	.string "Gwah!\n"
	.string "Hahahaha!$"
	.else
	.ifdef GERMAN
	.string "Muahahaha!\n"
	.string "Hahahaha!$"
	.endif
	.endif

@ Battle Pyramid
gText_BrandonWonSilver::
	.ifdef ENGLISH
	.string "Hey! What's wrong with you!\n"
	.string "Let's see some effort! Get up!$"
	.else
	.ifdef GERMAN
	.string "Hey! Was ist los mit dir?\n"
	.string "Zeig, was du kannst! Hopp hopp!$"
	.endif
	.endif

gText_BrandonDefeatSilver::
	.ifdef ENGLISH
	.string "That's it! You've done great!\n"
	.string "You've worked hard for this!$"
	.else
	.ifdef GERMAN
	.string "Das ist wahrer Kampfgeist! Sehr gut!\n"
	.string "Du hast dich wirklich angestrengt!$"
	.endif
	.endif

gText_BrandonWonGold::
	.ifdef ENGLISH
	.string "Hey! Don't you give up now!\n"
	.string "Get up! Don't lose faith in yourself!$"
	.else
	.ifdef GERMAN
	.string "Hey! Du kannst doch nicht einfach\n"
	.string "aufgeben! Du musst an dich glauben!$"
	.endif
	.endif

gText_BrandonDefeatGold::
	.ifdef ENGLISH
	.string "That's it! You've done it!\n"
	.string "You kept working for this!$"
	.else
	.ifdef GERMAN
	.string "Jawohl! Du hast es geschafft!\n"
	.string "Gut, dass du niemals aufgegeben hast!$"
	.endif
	.endif
