@ Only contains the text for the Mauville Man named Giddy. The rest is in scripts/mauville_man.inc
GiddyText_SoPretty::
	.ifdef ENGLISH
	.string " so pretty!$"
	.else
	.ifdef GERMAN
	.string " so hübsch!$"
	.endif
	.endif

GiddyText_SoDarling::
	.ifdef ENGLISH
	.string " so darling!$"
	.else
	.ifdef GERMAN
	.string " so reizend!$"
	.endif
	.endif

GiddyText_SoRelaxed::
	.ifdef ENGLISH
	.string " so relaxed!$"
	.else
	.ifdef GERMAN
	.string " so lässig!$"
	.endif
	.endif

GiddyText_SoSunny::
	.ifdef ENGLISH
	.string " so sunny!$"
	.else
	.ifdef GERMAN
	.string " so überwältigend!$"
	.endif
	.endif

GiddyText_SoDesirable::
	.ifdef ENGLISH
	.string " so desirable!$"
	.else
	.ifdef GERMAN
	.string " so erstrebenswert!$"
	.endif
	.endif

GiddyText_SoExciting::
	.ifdef ENGLISH
	.string " so exciting!$"
	.else
	.ifdef GERMAN
	.string " so aufregend!$"
	.endif
	.endif

GiddyText_SoAmusing::
	.ifdef ENGLISH
	.string " so amusing!$"
	.else
	.ifdef GERMAN
	.string " so amüsant!$"
	.endif
	.endif

GiddyText_SoMagical::
	.ifdef ENGLISH
	.string " so magical!$"
	.else
	.ifdef GERMAN
	.string " so zauberhaft!$"
	.endif
	.endif

GiddyText_Is::
	.ifdef ENGLISH
	.string " is$"
	.else
	.ifdef GERMAN
	.string " klingt$"
	.endif
	.endif

GiddyText_DontYouAgree::
	.ifdef ENGLISH
	.string "\n"
	.string "Don't you agree?$"
	.else
	.ifdef GERMAN
	.string "\n"
	.string "Findest du nicht auch?$"
	.endif
	.endif

GiddyText_ISoWantToGoOnAVacation::
	.ifdef ENGLISH
	.string "I so want to go on a vacation.\n"
	.string "Would you happen to know a nice place?$"
	.else
	.ifdef GERMAN
	.string "Ich will unbedingt verreisen!\n"
	.string "Kennst du ein hübsches Reiseziel?$"
	.endif
	.endif

GiddyText_IBoughtCrayonsWith120Colors::
	.ifdef ENGLISH
	.string "I bought crayons with 120 colors!\n"
	.string "Don't you think that's nice?$"
	.else
	.ifdef GERMAN
	.string "Ich habe 120 verschiedene Farbstifte\n"
	.string "gekauft! Das ist doch toll, oder?$"
	.endif
	.endif

GiddyText_WouldntItBeNiceIfWeCouldFloat::
	.ifdef ENGLISH
	.string "Wouldn't it be nice if we could float\n"
	.string "away on a cloud of bubbles?$"
	.else
	.ifdef GERMAN
	.string "Wäre es nicht herrlich, wir könnten auf\n"
	.string "einer Luftblasenwolke davonschweben?$"
	.endif
	.endif

GiddyText_WhenYouWriteOnASandyBeach::
	.ifdef ENGLISH
	.string "When you write on a sandy beach,\n"
	.string "they wash away. It makes me sad.$"
	.else
	.ifdef GERMAN
	.string "Eine Botschaft in Sand geschrieben\n"
	.string "wird weggespült. Das ist traurig.$"
	.endif
	.endif

GiddyText_WhatsTheBottomOfTheSeaLike::
	.ifdef ENGLISH
	.string "What's the bottom of the sea like?\n"
	.string "Just once I would so love to go!$"
	.else
	.ifdef GERMAN
	.string "Wie der Meeresgrund wohl ist? Ich\n"
	.string "würde ihn so gerne einmal erleben!$"
	.endif
	.endif

GiddyText_WhenYouSeeTheSettingSunDoesIt::
	.ifdef ENGLISH
	.string "When you see the setting sun, does it\n"
	.string "make you want to go home?$"
	.else
	.ifdef GERMAN
	.string "Sehnst du dich beim Anblick der unter-\n"
	.string "gehenden Sonne nach deinem Zuhause?$"
	.endif
	.endif

GiddyText_LyingBackInTheGreenGrass::
	.ifdef ENGLISH
	.string "Lying back in the green grass…\n"
	.string "Oh, it's so, so nice!$"
	.else
	.ifdef GERMAN
	.string "Einfach so im grünen Gras liegen…\n"
	.string "Oh, das ist so was von angenehm!$"
	.endif
	.endif

GiddyText_SecretBasesAreSoWonderful::
	.ifdef ENGLISH
	.string "SECRET BASES are so wonderful!\n"
	.string "Can't you feel the excitement?$"
	.else
	.ifdef GERMAN
	.string "GEHEIMBASen sind superklasse!\n"
	.string "Findest du das nicht auch aufregend?$"
	.endif
	.endif
