MoveTutor_Text_ThisMoveCanOnlyBeLearnedOnce:
	.ifdef ENGLISH
	.string "This move can be learned only\n"
	.string "once. Is that okay?$"
	.else
	.ifdef GERMAN
	.string "Diese Attacke kann nur einmal\n"
	.string "erlernt werden! Ist das in Ordnung?$"
	.endif
	.endif

MoveTutor_Text_SwaggerTeach:
	.ifdef ENGLISH
	.string "Heh! My POKéMON totally rules!\n"
	.string "It's cooler than any POKéMON!\p"
	.string "I was lipping off with a swagger in\n"
	.string "my step like that when the CHAIRMAN\l"
	.string "chewed me out.\p"
	.string "That took the swagger out of my step.\p"
	.string "If you'd like, I'll teach the move\n"
	.string "SWAGGER to a POKéMON of yours.$"
	.else
	.ifdef GERMAN
	.string "Heh! Mein POKéMON ist das Beste!\n"
	.string "Kein anderes ist so cool wie meins!\p"
	.string "Ich bin herumstolziert und habe\n"
	.string "angegeben, bis ein VORSITZENDER mich\l"
	.string "zu Fall brachte.\p"
	.string "Das hat meinen Hochmut abgekühlt.\p"
	.string "Wenn du magst, dann bringe ich einem\n"
	.string "deiner POKéMON ANGEBEREI bei.$"
	.endif
	.endif

MoveTutor_Text_SwaggerDeclined:
	.ifdef ENGLISH
	.string "What, no? Can't you get into\n"
	.string "the spirit of things?$"
	.else
	.ifdef GERMAN
	.string "Echt nicht? Erkennst du denn nicht\n"
	.string "den tieferen Sinn dahinter?$"
	.endif
	.endif

MoveTutor_Text_SwaggerWhichMon:
	.ifdef ENGLISH
	.string "All right, which POKéMON wants to\n"
	.string "learn how to SWAGGER?$"
	.else
	.ifdef GERMAN
	.string "Sehr schön! Und welches POKéMON soll\n"
	.string "es lernen?$"
	.endif
	.endif

MoveTutor_Text_SwaggerTaught:
	.ifdef ENGLISH
	.string "I'll just praise my POKéMON from now\n"
	.string "on without the swagger.$"
	.else
	.ifdef GERMAN
	.string "Ich werde von nun an meine POKéMON\n"
	.string "loben, ohne anzugeben.$"
	.endif
	.endif

MoveTutor_Text_RolloutTeach:
	.ifdef ENGLISH
	.string "Did you know that you can go from\n"
	.string "here a long way in that direction\l"
	.string "without changing direction?\p"
	.string "I might even be able to roll\n"
	.string "that way.\p"
	.string "Do you think your POKéMON will\n"
	.string "want to roll, too?\p"
	.string "I can teach one the move ROLLOUT\n"
	.string "if you'd like.$"
	.else
	.ifdef GERMAN
	.string "Wusstest du, dass du von hier lange\n"
	.string "in diese Richtung dort gehen kannst,\l"
	.string "ohne die Richtung wechseln zu müssen?\p"
	.string "Ich bin sogar in der Lage, den ganzen\n"
	.string "Weg entlang zu walzen.\p"
	.string "Ob eines deiner POKéMON das auch\n"
	.string "gerne tun würde? Was meinst du?\p"
	.string "Ich kann ihm WALZER beibringen, wenn\n"
	.string "du magst.$"
	.endif
	.endif

MoveTutor_Text_RolloutDeclined:
	.ifdef ENGLISH
	.string "You don't need to be shy about it.\n"
	.string "Let's roll!$"
	.else
	.ifdef GERMAN
	.string "Ach, sei doch nicht so schüchtern.\n"
	.string "Walzen macht doch Spaß!$"
	.endif
	.endif

MoveTutor_Text_RolloutWhichMon:
	.ifdef ENGLISH
	.string "Ehehe, sure thing! It'd be great if\n"
	.string "the POKéMON looked like me.$"
	.else
	.ifdef GERMAN
	.string "Hehehe. Wäre doch klasse, wenn das\n"
	.string "POKéMON so aussehen würde wie ich.$"
	.endif
	.endif

MoveTutor_Text_RolloutTaught:
	.ifdef ENGLISH
	.string "Rolling around in the grass makes me\n"
	.string "happy. Come on, let's roll!$"
	.else
	.ifdef GERMAN
	.string "Ich walze total gerne durch Gras.\n"
	.string "Komm, ich lade dich zum Walzen ein.$"
	.endif
	.endif

MoveTutor_Text_FuryCutterTeach:
	.ifdef ENGLISH
	.string "There's a move that gets stronger\n"
	.string "when you keep using it in a row.\p"
	.string "It's a BUG-type move, and it is\n"
	.string "wickedly cool.\p"
	.string "It's called FURY CUTTER.\n"
	.string "Want me to teach it to a POKéMON?$"
	.else
	.ifdef GERMAN
	.string "Es gibt eine Attacke, die stärker wird,\n"
	.string "wenn du sie mehrmals hintereinander\l"
	.string "einsetzt.\p"
	.string "Sie ist vom Typ KÄFER und megacool!\p"
	.string "Sie heißt ZORNKLINGE.\n"
	.string "Soll ich sie einem POKéMON beibringen?$"
	.endif
	.endif

MoveTutor_Text_FuryCutterDeclined:
	.ifdef ENGLISH
	.string "We're not on the same wavelength.$"
	.else
	.ifdef GERMAN
	.string "Wir haben offensichtlich nicht die\n"
	.string "gleiche Wellenlänge.$"
	.endif
	.endif

MoveTutor_Text_FuryCutterWhichMon:
	.ifdef ENGLISH
	.string "Yay!\n"
	.string "Show me which POKéMON I should teach.$"
	.else
	.ifdef GERMAN
	.string "Ja, klasse! Und welches POKéMON soll die\n"
	.string "Attacke lernen?$"
	.endif
	.endif

MoveTutor_Text_FuryCutterTaught:
	.ifdef ENGLISH
	.string "I get a thrill watching to see if\n"
	.string "the move keeps hitting in succession!$"
	.else
	.ifdef GERMAN
	.string "Es ist einfach toll zu sehen, wenn die\n"
	.string "Attacke mehrmals hintereinander\l"
	.string "trifft.$"
	.endif
	.endif

MoveTutor_MimicTeach:
	.ifdef ENGLISH
	.string "Ah, young one!\p"
	.string "I am also a young one, but I mimic\n"
	.string "the styles and speech of the elderly\l"
	.string "folks of this town.\p"
	.string "What do you say, young one?\n"
	.string "Would you agree to it if I were to\l"
	.string "offer to teach the move MIMIC?$"
	.else
	.ifdef GERMAN
	.string "Ah, Jungchen!\p"
	.string "Ich bin auch noch jung, aber ich ahme\n"
	.string "die Sprache der älteren Leute nach, die\l"
	.string "ich in diesem Ort treffe.\p"
	.string "Was meinst du, Kindchen?\n"
	.string "Würde es dich freuen, wenn ich einem\l"
	.string "deiner POKéMON MIMIKRY beibringe?$"
	.endif
	.endif

MoveTutor_MimicDeclined:
	.ifdef ENGLISH
	.string "Oh, boo! I wanted to teach MIMIC\n"
	.string "to your POKéMON!$"
	.else
	.ifdef GERMAN
	.string "Oh, buuuuh! Und ich wollte doch so gerne\n"
	.string "einem POKéMON MIMIKRY beibringen…$"
	.endif
	.endif

MoveTutor_Text_MimicWhichMon:
	.ifdef ENGLISH
	.string "Fwofwo! And so I shall!\n"
	.string "Let me see the POKéMON\l"
	.string "you wish me to teach.$"
	.else
	.ifdef GERMAN
	.string "Hahaha! So soll es sein! Zeig mir das\n"
	.string "POKéMON, welches die Attacke lernen\l"
	.string "soll.$"
	.endif
	.endif

MoveTutor_Text_MimicTaught:
	.ifdef ENGLISH
	.string "MIMIC is a move of great depth.\p"
	.string "Could you execute it to perfection\n"
	.string "as well as me…?$"
	.else
	.ifdef GERMAN
	.string "MIMIKRY ist eine Attacke mit Tiefe.\p"
	.string "Kannst du sie so perfekt anwenden, wie\n"
	.string "ich es kann?$"
	.endif
	.endif

MoveTutor_Text_MetronomeTeach:
	.ifdef ENGLISH
	.string "I want all sorts of things!\n"
	.string "But I used up my allowance…\p"
	.string "Wouldn't it be nice if there were\n"
	.string "a spell that made money appear when\l"
	.string "you waggle a finger?\p"
	.string "If you want, I can teach your POKéMON\n"
	.string "the move METRONOME.\p"
	.string "Money won't appear, but your POKéMON\n"
	.string "will waggle a finger. Yes?$"
	.else
	.ifdef GERMAN
	.string "Ich will alles Mögliche haben… Aber\n"
	.string "ich habe mein ganzes Geld ausgegeben…\p"
	.string "Ach, ich fände es toll, wenn es einen\n"
	.string "Spruch gäbe, bei dem man nur mit dem\l"
	.string "Finger wackelt und schon hat man Geld.\p"
	.string "Wenn du möchtest, bringe ich einem\n"
	.string "deiner POKéMON METRONOM bei.\p"
	.string "Dadurch bekommst du kein Geld, aber\n"
	.string "dein POKéMON wackelt mit dem Finger.$"
	.endif
	.endif

MoveTutor_Text_MetronomeDeclined:
	.ifdef ENGLISH
	.string "Okay. I'll be here if you change\n"
	.string "your mind.$"
	.else
	.ifdef GERMAN
	.string "Okay. Solltest du es dir anders\n"
	.string "überlegen - du findest mich hier.$"
	.endif
	.endif

MoveTutor_Text_MetronomeWhichMon:
	.ifdef ENGLISH
	.string "Okay! I'll teach it!\n"
	.string "Which POKéMON should I teach?$"
	.else
	.ifdef GERMAN
	.string "Okay. Ich werde es ihm beibringen.\n"
	.string "Und welchem soll ich es beibringen?$"
	.endif
	.endif

MoveTutor_Text_MetronomeTaught:
	.ifdef ENGLISH
	.string "When a POKéMON waggles its finger\n"
	.string "like a METRONOME, all sorts of nice\l"
	.string "things happen.\p"
	.string "Wouldn't it be nice if we could\n"
	.string "use it, too?$"
	.else
	.ifdef GERMAN
	.string "Wackelt ein POKéMON mit seinem Finger\n"
	.string "wie ein METRONOM, passieren die\l"
	.string "schönsten Dinge.\p"
	.string "Wäre das toll, wenn wir das auch\n"
	.string "könnten. Meinst du nicht auch?$"
	.endif
	.endif

MoveTutor_Text_SleepTalkTeach:
	.ifdef ENGLISH
	.string "Humph! My wife relies on HIDDEN\n"
	.string "POWER to stay awake.\p"
	.string "She should just take a nap like I do,\n"
	.string "and SLEEP TALK.\p"
	.string "I can teach your POKéMON how to\n"
	.string "SLEEP TALK instead. Interested?$"
	.else
	.ifdef GERMAN
	.string "Hmpf! Meine Frau vertraut auf\n"
	.string "KRAFTRESERVE, um wach zu bleiben.\p"
	.string "Sie sollte lieber ein Nickerchen halten\n"
	.string "und eine SCHLAFREDE halten.\p"
	.string "Ich kann einem deiner POKéMON\n"
	.string "SCHLAFREDE beibringen. Interessiert?$"
	.endif
	.endif

MoveTutor_Text_SleepTalkDeclined:
	.ifdef ENGLISH
	.string "Oh, fine, fine. You want to stay awake\n"
	.string "with HIDDEN POWER, too…$"
	.else
	.ifdef GERMAN
	.string "Schon gut, schon gut. Dann bleib doch\n"
	.string "wach, dank KRAFTRESERVE.$"
	.endif
	.endif

MoveTutor_Text_SleepTalkWhichMon:
	.ifdef ENGLISH
	.string "Ah, an appreciative child!\n"
	.string "Which POKéMON should I teach?$"
	.else
	.ifdef GERMAN
	.string "Oh, was für ein verständiges Kind!\n"
	.string "Welchem POKéMON soll ich es beibringen?$"
	.endif
	.endif

MoveTutor_Text_SleepTalkTaught:
	.ifdef ENGLISH
	.string "I've never once gotten my wife's\n"
	.string "coin trick right.\p"
	.string "I would be happy if I got it right\n"
	.string "even as I SLEEP TALK…$"
	.else
	.ifdef GERMAN
	.string "Ich kann meine Frau einfach nicht\n"
	.string "überlisten…\p"
	.string "Stattdessen hört sie interessiert\n"
	.string "meiner SCHLAFREDE zu…$"
	.endif
	.endif

MoveTutor_Text_SubstituteTeach:
	.ifdef ENGLISH
	.string "When I see the wide world from up\n"
	.string "here on the roof…\p"
	.string "I think about how nice it would be\n"
	.string "if there were more than just one me\l"
	.string "so I could enjoy all sorts of lives.\p"
	.string "Of course it's not possible.\n"
	.string "Giggle…\p"
	.string "I know! Would you be interested in\n"
	.string "having a POKéMON learn SUBSTITUTE?$"
	.else
	.ifdef GERMAN
	.string "Wenn ich die weite Welt von hier oben\n"
	.string "aus betrachte…\p"
	.string "dann wünschte ich mir, es gäbe mich\n"
	.string "mehr als einmal, damit ich alle schönen\l"
	.string "Dinge des Lebens genießen kann.\p"
	.string "Aber das ist ja leider nicht möglich…\n"
	.string "Kicher…\p"
	.string "Ich weiß! Soll ich einem deiner POKéMON\n"
	.string "DELEGATOR beibringen?$"
	.endif
	.endif

MoveTutor_Text_SubstituteDeclined:
	.ifdef ENGLISH
	.string "Oh, no?\p"
	.string "A POKéMON can make a copy of\n"
	.string "itself using it, you know.$"
	.else
	.ifdef GERMAN
	.string "Oh? Nicht?\p"
	.string "Ein POKéMON könnte damit aber einen\n"
	.string "Doppelgänger von sich schaffen!$"
	.endif
	.endif

MoveTutor_Text_SubstituteWhichMon:
	.ifdef ENGLISH
	.string "Giggle…\n"
	.string "Which POKéMON do you want me to\l"
	.string "teach SUBSTITUTE?$"
	.else
	.ifdef GERMAN
	.string "Kicher…\n"
	.string "Welchem POKéMON soll ich es beibringen?$"
	.endif
	.endif

MoveTutor_Text_SubstituteTaught:
	.ifdef ENGLISH
	.string "We human beings should enjoy our\n"
	.string "own lives to the utmost!\p"
	.string "I hope you'll get that way, too!$"
	.else
	.ifdef GERMAN
	.string "Wir Menschen sollten unser Leben voll\n"
	.string "ausschöpfen und genießen!\p"
	.string "Ich hoffe, du tust das bereits!$"
	.endif
	.endif

MoveTutor_Text_DynamicPunchTeach:
	.ifdef ENGLISH
	.string "I can't do this anymore!\p"
	.string "It's utterly hopeless!\p"
	.string "I'm a FIGHTING-type TRAINER,\n"
	.string "so I can't win at the MOSSDEEP GYM\l"
	.string "no matter how hard I try!\p"
	.string "Argh! Punch! Punch! Punch!\n"
	.string "Punch! Punch! Punch!\p"
	.string "What, don't look at me that way!\n"
	.string "I'm only hitting the ground!\p"
	.string "Or do you want me to teach your\n"
	.string "POKéMON DYNAMICPUNCH?$"
	.else
	.ifdef GERMAN
	.string "Ich kann nicht mehr!\p"
	.string "Das ist doch absolut hoffnungslos!\p"
	.string "Ich bin ein KAMPF-TRAINER, daher kann\n"
	.string "ich in der ARENA von MOOSBACH einfach\p"
	.string "nicht gewinnen, egal, wie sehr ich mich\n"
	.string "auch anstrenge!\p"
	.string "Argh! Schlag! Wucht! Schlag!\n"
	.string "Schlag! Wucht! Schlag!\p"
	.string "Hey, was starrst du mich so an?!?\n"
	.string "Ich schlage doch nur auf den Boden ein!\p"
	.string "Oder möchtest du, dass ich einem deiner\n"
	.string "POKéMON WUCHTSCHLAG beibringe?!?$"
	.endif
	.endif

MoveTutor_Text_DynamicPunchDeclined:
	.ifdef ENGLISH
	.string "Darn! You're even making fun of me?\n"
	.string "Punch! Punch! Punch!$"
	.else
	.ifdef GERMAN
	.string "Mist! Du machst dich lustig über mich!!!\n"
	.string "Schlag! Wucht! Schlag!$"
	.endif
	.endif

MoveTutor_Text_DynamicPunchWhichMon:
	.ifdef ENGLISH
	.string "What? You do? You're a good person!\n"
	.string "Which POKéMON should I teach?$"
	.else
	.ifdef GERMAN
	.string "Das möchtest du? Das ist klug von dir!\n"
	.string "Welchem POKéMON soll ich es beibringen?$"
	.endif
	.endif

MoveTutor_Text_DynamicPunchTaught:
	.ifdef ENGLISH
	.string "I want you to win at the MOSSDEEP GYM\n"
	.string "using that DYNAMICPUNCH!$"
	.else
	.ifdef GERMAN
	.string "Ich möchte, dass du in der ARENA von\n"
	.string "MOOSBACH gewinnst, indem du\l"
	.string "WUCHTSCHLAG einsetzt.$"
	.endif
	.endif

MoveTutor_Text_DoubleEdgeTeach:
	.ifdef ENGLISH
	.string "Sigh…\p"
	.string "SOOTOPOLIS's GYM LEADER is really\n"
	.string "lovably admirable.\p"
	.string "But that also means I have many\n"
	.string "rivals for his attention.\p"
	.string "He's got appeal with a DOUBLE-EDGE.\n"
	.string "I couldn't even catch his eye.\p"
	.string "Please, let me teach your POKéMON\n"
	.string "the move DOUBLE-EDGE!$"
	.else
	.ifdef GERMAN
	.string "Seufz…\p"
	.string "Der ARENALEITER von XENEROVILLE ist\n"
	.string "einfach anbetungswürdig.\p"
	.string "Aber das heißt auch, dass ich viele\n"
	.string "Rivalinnen habe, die um seine Gunst\l"
	.string "kämpfen.\p"
	.string "Er wurde mit RISIKOTACKLE verzaubert.\n"
	.string "Unsere Augen trafen sich nicht.\p"
	.string "Darf ich einem deiner POKéMON\n"
	.string "RISIKOTACKLE beibringen?$"
	.endif
	.endif

MoveTutor_Text_DoubleEdgeDeclined:
	.ifdef ENGLISH
	.string "Oh…\n"
	.string "Even you rejected me…$"
	.else
	.ifdef GERMAN
	.string "Oh…\n"
	.string "Auch du lehnst mich also ab…$"
	.endif
	.endif

MoveTutor_Text_DoubleEdgeWhichMon:
	.ifdef ENGLISH
	.string "Okay, which POKéMON should I teach\n"
	.string "DOUBLE-EDGE?$"
	.else
	.ifdef GERMAN
	.string "Schön!!! Welchem POKéMON soll ich\n"
	.string "RISIKOTACKLE beibringen?$"
	.endif
	.endif

MoveTutor_Text_DoubleEdgeTaught:
	.ifdef ENGLISH
	.string "I won't live for love anymore!\n"
	.string "I'll become tough!$"
	.else
	.ifdef GERMAN
	.string "Ich werde nicht mehr für die Liebe\n"
	.string "leben! Ich werde stark werden!$"
	.endif
	.endif

MoveTutor_Text_ExplosionTeach:
	.ifdef ENGLISH
	.string "I don't intend to be going nowhere\n"
	.string "fast in the sticks like this forever.\p"
	.string "You watch me, I'll get out to the city\n"
	.string "and become a huge hit.\p"
	.string "Seriously, I'm going to cause\n"
	.string "a huge EXPLOSION of popularity!\p"
	.string "If you overheard that, I'll happily\n"
	.string "teach EXPLOSION to your POKéMON!$"
	.else
	.ifdef GERMAN
	.string "Ich habe nicht vor, lange hier in der\n"
	.string "Ödnis zu bleiben.\p"
	.string "Pass nur auf! Ich werde diesen Ort\n"
	.string "verlassen und ganz groß rauskommen!\p"
	.string "Ernsthaft! Mein Ruhm wird\n"
	.string "explosionsartig zum Vorschein kommen.\p"
	.string "Wenn du an mich glaubst, bringe ich\n"
	.string "einem deiner POKéMON EXPLOSION bei.$"
	.endif
	.endif

MoveTutor_Text_ExplosionDeclined:
	.ifdef ENGLISH
	.string "Gaah! You're turning me down because\n"
	.string "I live in the country?$"
	.else
	.ifdef GERMAN
	.string "Argh! Nur weil ich in der Pampa lebe,\n"
	.string "ignorierst du mein Angebot?!?$"
	.endif
	.endif

MoveTutor_Text_ExplosionWhichMon:
	.ifdef ENGLISH
	.string "Fine! An EXPLOSION it is!\n"
	.string "Which POKéMON wants to blow up?$"
	.else
	.ifdef GERMAN
	.string "Super! Das wird eine EXPLOSION!\n"
	.string "Welchem POKéMON soll ich es beibringen?$"
	.endif
	.endif

MoveTutor_Text_ExplosionTaught:
	.ifdef ENGLISH
	.string "For a long time, I've taught POKéMON\n"
	.string "how to use EXPLOSION, but I've yet\l"
	.string "to ignite my own EXPLOSION…\p"
	.string "Maybe it's because deep down,\n"
	.string "I would rather stay here…$"
	.else
	.ifdef GERMAN
	.string "Schon lange bringe ich POKéMON\n"
	.string "EXPLOSION bei. Jetzt wird es Zeit an\l"
	.string "meine eigene EXPLOSION zu denken…\p"
	.string "Vielleicht bin ich schon so lange hier,\n"
	.string "weil es mir hier doch gefällt?!?$"
	.endif
	.endif
