gText_ObtainedTheItem::
	.ifdef ENGLISH
	.string "Obtained the {STR_VAR_2}!$"
	.else
	.ifdef GERMAN
	.string "{STR_VAR_2} erhalten!$"
	.endif
	.endif

gText_TheBagIsFull::
	.ifdef ENGLISH
	.string "The BAG is full…$"
	.else
	.ifdef GERMAN
	.string "Der BEUTEL ist voll…$"
	.endif
	.endif

gText_PutItemInPocket::
	.ifdef ENGLISH
	.string "{PLAYER} put away the {STR_VAR_2}\n"
	.string "in the {STR_VAR_3} POCKET.$"
	.else
	.ifdef GERMAN
	.string "{PLAYER} packt {STR_VAR_2} in die\n"
	.string "{STR_VAR_3}-TASCHE.$"
	.endif
	.endif

gText_PlayerFoundOneItem::
	.ifdef ENGLISH
	.string "{PLAYER} found one {STR_VAR_2}!$"
	.else
	.ifdef GERMAN
	.string "{PLAYER} hat {STR_VAR_2} gefunden!$"
	.endif
	.endif

gText_TooBadBagIsFull::
	.ifdef ENGLISH
	.string "Too bad!\n"
	.string "The BAG is full…$"
	.else
	.ifdef GERMAN
	.string "Zu schade!\n"
	.string "Der BEUTEL ist voll…$"
	.endif
	.endif

gText_PlayerPutItemInBag::
	.ifdef ENGLISH
	.string "{PLAYER} put away the {STR_VAR_2}\n"
	.string "in the BAG.$"
	.else
	.ifdef GERMAN
	.string "{PLAYER} packt {STR_VAR_2} in den\n"
	.string "PYRABEUTEL.$"
	.endif
	.endif

gText_ObtainedTheDecor::
	.ifdef ENGLISH
	.string "Obtained the {STR_VAR_2}!$"
	.else
	.ifdef GERMAN
	.string "{STR_VAR_2} erhalten.$"
	.endif
	.endif

gText_NoRoomLeftForAnother::
	.ifdef ENGLISH
	.string "Too bad! There's no room left for\n"
	.string "another {STR_VAR_2}…$"
	.else
	.ifdef GERMAN
	.string "Zu schade! Es ist kein Platz für\n"
	.string "{STR_VAR_2}…$"
	.endif
	.endif

gText_TheDecorWasTransferredToThePC::
	.ifdef ENGLISH
	.string "The {STR_VAR_2} was transferred\n"
	.string "to the PC.$"
	.else
	.ifdef GERMAN
	.string "{STR_VAR_2} wurde auf den PC\n"
	.string "übertragen.$"
	.endif
	.endif
