gText_WouldYouLikeToRestYourPkmn::
	.ifdef ENGLISH
	.string "Hello, and welcome to\n"
	.string "the POKéMON CENTER.\p"
	.string "We restore your tired POKéMON\n"
	.string "to full health.\p"
	.string "Would you like to rest your POKéMON?$"
	.else
	.ifdef GERMAN
	.string "Willkommen im POKéMON-CENTER!\p"
	.string "Wir heilen deine POKéMON und\n"
	.string "machen sie wieder fit.\p"
	.string "O.K. Wir benötigen deine POKéMON.$"
	.endif
	.endif

gText_IllTakeYourPkmn::
	.ifdef ENGLISH
	.string "Okay, I'll take your POKéMON\n"
	.string "for a few seconds.$"
	.else
	.ifdef GERMAN
	.string "Okay, ich nehme deine POKéMON für einen\n"
	.string "Moment in meine Obhut.$"
	.endif
	.endif

gText_RestoredPkmnToFullHealth::
	.ifdef ENGLISH
	.string "Thank you for waiting.\p"
	.string "We've restored your POKéMON\n"
	.string "to full health.$"
	.else
	.ifdef GERMAN
	.string "Danke!\p"
	.string "Deine POKéMON sind wieder topfit!$"
	.endif
	.endif

gText_WeHopeToSeeYouAgain::
	.ifdef ENGLISH
	.string "We hope to see you again!$"
	.else
	.ifdef GERMAN
	.string "Komm jederzeit wieder vorbei!$"
	.endif
	.endif

gText_WelcomeCutShort::
	.ifdef ENGLISH
	.string "Hello, and welcome to\n"
	.string "the POKéMON CENTER.\p"
	.string "We restore your tired POKéMON\n"
	.string "to full health.\p"
	.string "Would you like to…$"
	.else
	.ifdef GERMAN
	.string "Willkommen im POKéMON-CENTER!\p"
	.string "Wir heilen deine POKéMON und\n"
	.string "machen sie wieder fit.\p"
	.string "O.K. Wir benötigen deine POKéMON.$"
	.endif
	.endif

gText_NoticesGoldCard::
	.ifdef ENGLISH
	.string "Th-that card…\n"
	.string "Could it be… The GOLD CARD?!\p"
	.string "Oh, the gold color is brilliant!\n"
	.string "The four stars seem to sparkle!\p"
	.string "I've seen several TRAINERS with\n"
	.string "a SILVER CARD before, but, {PLAYER},\l"
	.string "you're the first TRAINER I've ever\l"
	.string "seen with a GOLD CARD!\p"
	.string "Okay, {PLAYER}, please allow me\n"
	.string "the honor of resting your POKéMON!$"
	.else
	.ifdef GERMAN
	.string "Di-dieser Pass…\n"
	.string "Ist das der… GOLDPASS?!?\p"
	.string "Diese goldene Farbe ist brillant!\n"
	.string "Die vier Sterne funkeln richtig!\p"
	.string "Ich habe schon viele TRAINER mit einem\n"
	.string "SILBERPASS gesehen, aber, {PLAYER},\l"
	.string "du bist der erste TRAINER mit einem\l"
	.string "GOLDPASS!\p"
	.string "Okay, {PLAYER}, bitte gib mir die Ehre,\n"
	.string "mich um deine POKéMON kümmern\l"
	.string "zu dürfen!$"
	.endif
	.endif

gText_YouWantTheUsual::
	.ifdef ENGLISH
	.string "I'm delighted to see you, {PLAYER}!\n"
	.string "You want the usual, am I right?$"
	.else
	.ifdef GERMAN
	.string "Ich freue mich, dich zu sehen, {PLAYER}!\n"
	.string "Das Übliche, nicht wahr?$"
	.endif
	.endif

gText_IllTakeYourPkmn2::
	.ifdef ENGLISH
	.string "Okay, I'll take your POKéMON\n"
	.string "for a few seconds.$"
	.else
	.ifdef GERMAN
	.string "Okay, ich nehme deine POKéMON für einen\n"
	.string "Moment in meine Obhut.$"
	.endif
	.endif

gText_ThankYouForWaiting::
	.ifdef ENGLISH
	.string "Thank you for waiting.$"
	.else
	.ifdef GERMAN
	.string "Danke!$"
	.endif
	.endif

gText_WeHopeToSeeYouAgain2::
	.ifdef ENGLISH
	.string "We hope to see you again!$"
	.else
	.ifdef GERMAN
	.string "Komm bald wieder!$"
	.endif
	.endif
