gBirchDexRatingText_AreYouCurious::
	.ifdef ENGLISH
	.string "PROF. BIRCH: Ah, {PLAYER}{KUN}!\p"
	.string "Are you curious about how your\n"
	.string "POKéDEX is coming along?$"
	.else
	.ifdef GERMAN
	.string "PROF. BIRK: Ah, {PLAYER}{KUN}!\p"
	.string "Möchtest du mir deine Fortschritte\n"
	.string "mit dem POKéDEX zeigen?$"
	.endif
	.endif

gBirchDexRatingText_Cancel::
	.ifdef ENGLISH
	.string "Hm? Oh, you haven't caught enough\n"
	.string "POKéMON to make it worthwhile.$"
	.else
	.ifdef GERMAN
	.string "Ach? Du hast erst so wenige\n"
	.string "POKéMON gefangen, dass es sich\l"
	.string "nicht lohnt, ihn mir zu zeigen?$"
	.endif
	.endif

gBirchDexRatingText_SoYouveSeenAndCaught::
	.ifdef ENGLISH
	.string "Hmhm…\p"
	.string "So, you've seen {STR_VAR_1} POKéMON,\n"
	.string "and you've caught {STR_VAR_2} POKéMON…$"
	.else
	.ifdef GERMAN
	.string "Hmhm…\p"
	.string "Oh, du hast {STR_VAR_1} POKéMON gesehen\n"
	.string "und {STR_VAR_2} POKéMON gefangen…$"
	.endif
	.endif

gBirchDexRatingText_LessThan10::
	.ifdef ENGLISH
	.string "Go into grassy areas more and look\n"
	.string "for POKéMON more carefully.$"
	.else
	.ifdef GERMAN
	.string "Du solltest mehr ins hohe Gras\n"
	.string "gehen und mehr auf POKéMON\l"
	.string "achten.$"
	.endif
	.endif

gBirchDexRatingText_LessThan20::
	.ifdef ENGLISH
	.string "I guess you're getting the hang\n"
	.string "of it. But, it gets harder from here.$"
	.else
	.ifdef GERMAN
	.string "So langsam bekommst du den Bogen\n"
	.string "raus. Aber es wird immer schwieriger\l"
	.string "werden!$"
	.endif
	.endif

gBirchDexRatingText_LessThan30::
	.ifdef ENGLISH
	.string "Some POKéMON only appear in\n"
	.string "certain areas.\l"
	.string "You must be persistent.$"
	.else
	.ifdef GERMAN
	.string "Einige POKéMON tauchen nur in be-\n"
	.string "stimmten Regionen auf.\l"
	.string "Hab nur Geduld.$"
	.endif
	.endif

gBirchDexRatingText_LessThan40::
	.ifdef ENGLISH
	.string "Well, it could use more quantity,\n"
	.string "but this is looking more like\l"
	.string "a POKéDEX now.$"
	.else
	.ifdef GERMAN
	.string "Nun, er könnte mehr Einträge\n"
	.string "enthalten, aber es sieht schon\l"
	.string "eher nach einem POKéDEX aus.$"
	.endif
	.endif

gBirchDexRatingText_LessThan50::
	.ifdef ENGLISH
	.string "This is coming along pretty good.\n"
	.string "Keep up the effort.$"
	.else
	.ifdef GERMAN
	.string "Das läuft doch wunderbar.\n"
	.string "Mach weiter so.$"
	.endif
	.endif

gBirchDexRatingText_LessThan60::
	.ifdef ENGLISH
	.string "Are you using any RODS?\n"
	.string "There are many POKéMON in the sea.$"
	.else
	.ifdef GERMAN
	.string "Verwendest du irgendwelche\n"
	.string "ANGELn?\l"
	.string "Hier gibt es viele POKéMON im Meer.$"
	.endif
	.endif

gBirchDexRatingText_LessThan70::
	.ifdef ENGLISH
	.string "Instead of just catching POKéMON,\n"
	.string "how about making them evolve, too?$"
	.else
	.ifdef GERMAN
	.string "Statt die POKéMON nur zu fangen,\n"
	.string "wie wäre es, sie sich entwickeln zu\l"
	.string "lassen?$"
	.endif
	.endif

gBirchDexRatingText_LessThan80::
	.ifdef ENGLISH
	.string "This is going to be a fantastic\n"
	.string "POKéDEX.\l"
	.string "That's the feeling I'm getting.$"
	.else
	.ifdef GERMAN
	.string "Der POKéDEX wird einfach\n"
	.string "fantastisch.\l"
	.string "Das habe ich im Gefühl…$"
	.endif
	.endif

gBirchDexRatingText_LessThan90::
	.ifdef ENGLISH
	.string "You've collected this many…\n"
	.string "Your talent is remarkable!$"
	.else
	.ifdef GERMAN
	.string "Du hast so viele gefangen…\n"
	.string "Du hast ein außergewöhnliches\l"
	.string "Talent!$"
	.endif
	.endif

gBirchDexRatingText_LessThan100::
	.ifdef ENGLISH
	.string "Have you visited the SAFARI ZONE?\p"
	.string "I hear there are some POKéMON that\n"
	.string "can only be caught there.$"
	.else
	.ifdef GERMAN
	.string "Warst du schon mal in der\n"
	.string "SAFARI-ZONE?\p"
	.string "Ich habe gehört, es gibt POKéMON,\n"
	.string "die man nur dort finden kann.$"
	.endif
	.endif

gBirchDexRatingText_LessThan110::
	.ifdef ENGLISH
	.string "You've finally reached\n"
	.string "the 100-kind mark.\p"
	.string "This is an impressive POKéDEX!$"
	.else
	.ifdef GERMAN
	.string "Du hast die 100er-Marke\n"
	.string "überschritten!\p"
	.string "Das ist ein beeindruckender\n"
	.string "POKéDEX!$"
	.endif
	.endif

gBirchDexRatingText_LessThan120::
	.ifdef ENGLISH
	.string "There might be POKéMON that can be\n"
	.string "found using ROCK SMASH.$"
	.else
	.ifdef GERMAN
	.string "Es gibt auch POKéMON, die man\n"
	.string "durch den Einsatz von\l"
	.string "ZERTRÜMMERER findet.$"
	.endif
	.endif

gBirchDexRatingText_LessThan130::
	.ifdef ENGLISH
	.string "You should get some more POKéMON\n"
	.string "by trading with others.$"
	.else
	.ifdef GERMAN
	.string "Du solltest einige POKéMON fangen\n"
	.string "und sie mit anderen tauschen.$"
	.endif
	.endif

gBirchDexRatingText_LessThan140::
	.ifdef ENGLISH
	.string "I've heard of POKéMON that evolve\n"
	.string "when they come to fully love their\l"
	.string "TRAINERS.$"
	.else
	.ifdef GERMAN
	.string "Ich habe von POKéMON gehört, die\n"
	.string "sich entwickeln, wenn sie ihren\l"
	.string "TRAINER sehr lieben.$"
	.endif
	.endif

gBirchDexRatingText_LessThan150::
	.ifdef ENGLISH
	.string "I had no idea that there were so\n"
	.string "many POKéMON species in the HOENN\l"
	.string "region.$"
	.else
	.ifdef GERMAN
	.string "Ich hatte keine Ahnung, dass es in\n"
	.string "der HOENN-Region so viele\l"
	.string "verschiedene POKéMON-Arten gibt.$"
	.endif
	.endif

gBirchDexRatingText_LessThan160::
	.ifdef ENGLISH
	.string "On occasion, some POKéMON appear\n"
	.string "in large numbers like outbreaks.\p"
	.string "Don't miss opportunities like\n"
	.string "those.$"
	.else
	.ifdef GERMAN
	.string "Manchmal erscheinen einige\n"
	.string "POKéMON in großer Anzahl\p"
	.string "wie bei einem Ausbruch.\n"
	.string "Das solltest du nicht verpassen!$"
	.endif
	.endif

gBirchDexRatingText_LessThan170::
	.ifdef ENGLISH
	.string "One can get a very good idea about\n"
	.string "the POKéMON of the HOENN region\l"
	.string "by looking through your POKéDEX.$"
	.else
	.ifdef GERMAN
	.string "Dein POKéDEX liefert einen\n"
	.string "erstaunlich guten Einblick in die\l"
	.string "POKéMON der HOENN-Region!$"
	.endif
	.endif

gBirchDexRatingText_LessThan180::
	.ifdef ENGLISH
	.string "I would say you already qualify as\n"
	.string "a POKéMON PROFESSOR, and a good\l"
	.string "one, too!$"
	.else
	.ifdef GERMAN
	.string "Ich sage, du hast dich bereits als\n"
	.string "guter POKéMON-PROFESSOR\l"
	.string "qualifiziert.$"
	.endif
	.endif

gBirchDexRatingText_LessThan190::
	.ifdef ENGLISH
	.string "With a POKéDEX this complete,\n"
	.string "you're a real professional at this!$"
	.else
	.ifdef GERMAN
	.string "Mit diesem POKéDEX, der schon so\n"
	.string "weit gediehen ist, bist du ein\l"
	.string "echter Profi.$"
	.endif
	.endif

gBirchDexRatingText_LessThan200::
	.ifdef ENGLISH
	.string "You're very close to completing\n"
	.string "this POKéDEX.\l"
	.string "I can feel it in my bones!$"
	.else
	.ifdef GERMAN
	.string "Du bist sehr nahe dran, den\n"
	.string "POKéDEX zu vervollständigen.\l"
	.string "Das fühle ich einfach.$"
	.endif
	.endif

gBirchDexRatingText_DexCompleted::
	.ifdef ENGLISH
	.string "Congratulations!\n"
	.string "Your POKéDEX is complete!$"
	.else
	.ifdef GERMAN
	.string "Herzlichen Glückwunsch!\n"
	.string "Dein POKéDEX ist vollständig!$"
	.endif
	.endif

gBirchDexRatingText_OnANationwideBasis::
	.ifdef ENGLISH
	.string "Hmhm…\n"
	.string "On a nationwide basis…\p"
	.string "You've seen {STR_VAR_1} POKéMON,\n"
	.string "and you've caught {STR_VAR_2} POKéMON…$"
	.else
	.ifdef GERMAN
	.string "Hmhm…\n"
	.string "Auf nationaler Ebene…\p"
	.string "hast du {STR_VAR_1} POKéMON gesehen\n"
	.string "und {STR_VAR_2} POKéMON gefangen…$"
	.endif
	.endif
