
gPokeNewsTextSlateport_Upcoming::
	.ifdef ENGLISH
	.string "Greetings!\n"
	.string "It's time for POKéMON NEWS.\p"
	.string "SLATEPORT's most popular kind of guy,\n"
	.string "the ENERGY GURU, is in the news again!\p"
	.string "He promises to, “Stupendously go for\n"
	.string "it in just this many days: {STR_VAR_1}!”\p"
	.string "While he refused to elaborate on what\n"
	.string "he will stupendously go for, the\l"
	.string "ENERGY GURU advised, “Save up your\l"
	.string "money. That'll be good…”\p"
	.string "It sounds like a trip to SLATEPORT\n"
	.string "would be well worth your while that day.\p"
	.string "That's the news on POKéMON NEWS.$"
	.else
	.ifdef GERMAN
	.string "Guten Tag, meine Damen und Herren!\n"
	.string "Hier sind die POKéMON NACHRICHTEN.\p"
	.string "Heute berichten wir über GRAPHITPORT\n"
	.string "CITYs bekanntesten Typen, den\l"
	.string "STATUSWERTE GURU!\p"
	.string "Er versprach, dass er sich {STR_VAR_1} Tag(e)\n"
	.string "ins Zeug legen werde.\p"
	.string "Er wollte uns nicht verraten, wofür er\n"
	.string "sich ins Zeug legt. Stattdessen gab\p"
	.string "er uns den Rat: “Spart euer\n"
	.string "Geld. Das wäre gut…”\p"
	.string "GRAPHITPORT CITY ist eine Reise wert!\p"
	.string "Das waren die POKéMON NACHRICHTEN.$"
	.endif
	.endif

gPokeNewsTextSlateport_Ongoing::
	.ifdef ENGLISH
	.string "Greetings!\n"
	.string "It's time for POKéMON NEWS.\p"
	.string "This is the news you've all been\n"
	.string "waiting for!\p"
	.string "SLATEPORT'S ENERGY GURU is going\n"
	.string "for it stupendously in the MARKET!\p"
	.string "He promises unbeatable bargain\n"
	.string "prices on CALCIUM and PROTEIN!\p"
	.string "A trip to SLATEPORT CITY sounds\n"
	.string "worthwhile. Why not visit and shop\l"
	.string "to your heart's content?\p"
	.string "That's the news on POKéMON NEWS.$"
	.else
	.ifdef GERMAN
	.string "Guten Tag, meine Damen und Herren!\n"
	.string "Hier sind die POKéMON NACHRICHTEN.\p"
	.string "Auf diese Nachrichten haben Sie\n"
	.string "alle schon sehnsüchtig gewartet!\p"
	.string "GRAPHITPORT CITYs STATUSWERTE GURU\n"
	.string "legt sich im MARKT enorm ins Zeug!\p"
	.string "Er verspricht uns unschlagbare Preise\n"
	.string "zum Beispiel für KALZIUM und PROTEIN!\p"
	.string "GRAPHITPORT CITY ist eine Reise\n"
	.string "wert. Also: Schauen Sie vorbei und\l"
	.string "kaufen Sie, was das Herz begehrt.\p"
	.string "Das waren die POKéMON NACHRICHTEN.$"
	.endif
	.endif

gPokeNewsTextSlateport_Ending::
	.ifdef ENGLISH
	.string "Greetings!\n"
	.string "It's time for POKéMON NEWS.\p"
	.string "This is the news you've all been\n"
	.string "waiting for!\p"
	.string "SLATEPORT'S ENERGY GURU is going\n"
	.string "for it stupendously in the MARKET!\p"
	.string "He promises unbeatable bargain\n"
	.string "prices on CALCIUM and PROTEIN!\p"
	.string "According to the ENERGY GURU, he\n"
	.string "still has ample merchandise left.\p"
	.string "Why not visit SLATEPORT CITY for\n"
	.string "a most enjoyable shopping trip?\p"
	.string "That's the news on POKéMON NEWS.$"
	.else
	.ifdef GERMAN
	.string "Guten Tag, meine Damen und Herren!\n"
	.string "Hier sind die POKéMON NACHRICHTEN.\p"
	.string "Auf diese Nachrichten haben Sie\n"
	.string "alle schon sehnsüchtig gewartet!\p"
	.string "GRAPHITPORT CITYs STATUSWERTE GURU\n"
	.string "legt sich im MARKT enorm ins Zeug!\p"
	.string "Er verspricht uns unschlagbare Preise\n"
	.string "für KALZIUM und PROTEIN!\p"
	.string "Aber der STATUSWERTE GURU weist\n"
	.string "auch darauf hin, dass noch viele\l"
	.string "Packungen vorhanden sind.\p"
	.string "Also: Auf nach GRAPHITPORT CITY und\n"
	.string "genießen Sie den Einkauf!\p"
	.string "Das waren die POKéMON NACHRICHTEN.$"
	.endif
	.endif

gPokeNewsTextGameCorner_Upcoming::
	.ifdef ENGLISH
	.string "Greetings!\n"
	.string "It's time for POKéMON NEWS.\p"
	.string "It's approaching!\n"
	.string "It's finally coming!\p"
	.string "The GAME CORNER's service day will be\n"
	.string "here in just this many days: {STR_VAR_1}!\p"
	.string "Even those who are usually unlucky\n"
	.string "may be lucky on this particular day!\p"
	.string "That's the news on POKéMON NEWS.$"
	.else
	.ifdef GERMAN
	.string "Guten Tag meine Damen und Herren!\n"
	.string "Hier sind die POKéMON NACHRICHTEN.\p"
	.string "Bald ist es so weit!\n"
	.string "Bald ist der Tag gekommen!\p"
	.string "In {STR_VAR_1} Tag(en) erleben wir ihn, den\n"
	.string "Tag der SPIELHALLE!\p"
	.string "Selbst diejenigen, die nie Glück haben,\n"
	.string "werden ihr Glück nicht fassen können!\p"
	.string "Das waren die POKéMON NACHRICHTEN.$"
	.endif
	.endif

gPokeNewsTextGameCorner_Ongoing::
	.ifdef ENGLISH
	.string "Greetings!\n"
	.string "It's time for POKéMON NEWS.\p"
	.string "It's here!\n"
	.string "It's finally arrived!\p"
	.string "GAME CORNER's service day has finally\n"
	.string "arrived!\p"
	.string "Could you be lucky at the SLOTS \n"
	.string "and ROULETTE?\p"
	.string "The location is MAUVILLE CITY.\n"
	.string "This is the place!\p"
	.string "That's the news on POKéMON NEWS.$"
	.else
	.ifdef GERMAN
	.string "Guten Tag meine Damen und Herren!\n"
	.string "Hier sind die POKéMON NACHRICHTEN.\p"
	.string "Endlich ist es so weit!\n"
	.string "Endlich ist der Tag gekommen!\p"
	.string "Heute erleben wir ihn, den Tag der\n"
	.string "SPIELHALLE!\p"
	.string "Fordern Sie Ihr Glück beim ROULETTE\n"
	.string "oder den EINARMIGEN BANDITen heraus.\p"
	.string "Das Stichwort heißt: MALVENFROH CITY!\n"
	.string "Dort finden Sie Ihr Glück!\p"
	.string "Das waren die POKéMON NACHRICHTEN.$"
	.endif
	.endif

gPokeNewsTextGameCorner_Ending::
	.ifdef ENGLISH
	.string "Greetings!\n"
	.string "It's time for POKéMON NEWS.\p"
	.string "It's here!\n"
	.string "It's finally arrived!\p"
	.string "GAME CORNER's service day has finally\n"
	.string "arrived!\p"
	.string "Could you be lucky at the SLOTS\n"
	.string "and ROULETTE?\p"
	.string "Time is limited and has almost run out.\n"
	.string "The location is MAUVILLE CITY.\p"
	.string "That's the news on POKéMON NEWS.$"
	.else
	.ifdef GERMAN
	.string "Guten Tag, meine Damen und Herren!\n"
	.string "Hier sind die POKéMON NACHRICHTEN.\p"
	.string "Endlich ist es so weit!\n"
	.string "Endlich ist der Tag gekommen!\p"
	.string "Heute erleben wir ihn, den Tag der\n"
	.string "SPIELHALLE!\p"
	.string "Fordern Sie Ihr Glück beim ROULETTE\n"
	.string "oder den EINARMIGEN BANDITen heraus.\p"
	.string "Beeilen Sie sich, denn auch dieser Tag\n"
	.string "hat nur 24 Stunden. MALVENFROH CITY\l"
	.string "ruft!\p"
	.string "Das waren die POKéMON NACHRICHTEN.$"
	.endif
	.endif

gPokeNewsTextLilycove_Upcoming::
	.ifdef ENGLISH
	.string "Greetings!\n"
	.string "It's time for POKéMON NEWS.\p"
	.string "We've just received wonderful news\n"
	.string "from LILYCOVE DEPARTMENT STORE.\p"
	.string "The DEPARTMENT STORE's clear-out sale\n"
	.string "will be in just this many days: {STR_VAR_1}!\p"
	.string "That thingamajig or that doodad that\n"
	.string "you've always wanted could be yours!\p"
	.string "That's the news on POKéMON NEWS.$"
	.else
	.ifdef GERMAN
	.string "Guten Tag meine Damen und Herren!\n"
	.string "Hier sind die POKéMON NACHRICHTEN.\p"
	.string "Soeben erreichen uns wundervolle Nach-\n"
	.string "richten vom SEEGRASULB CITY\l"
	.string "EINKAUFSZENTRUM.\p"
	.string "In {STR_VAR_1} Tag(en) findet dort ein totaler\n"
	.string "Ausverkauf statt!\p"
	.string "Das Dingsbums und das Dingsda, welches\n"
	.string "Sie schon immer haben wollten, kann\l"
	.string "Ihnen gehören.\p"
	.string "Das waren die POKéMON NACHRICHTEN.$"
	.endif
	.endif

gPokeNewsTextLilycove_Ongoing::
	.ifdef ENGLISH
	.string "Greetings!\n"
	.string "It's time for POKéMON NEWS.\p"
	.string "This is the news you've all been\n"
	.string "waiting for!\p"
	.string "LILYCOVE DEPARTMENT STORE's clear-out\n"
	.string "sale has finally arrived!\p"
	.string "All the thingamajigs and doodads that\n"
	.string "you've always dreamt about…\p"
	.string "You may be in for fateful encounters\n"
	.string "with them all!\p"
	.string "That's the news on POKéMON NEWS.$"
	.else
	.ifdef GERMAN
	.string "Guten Tag meine Damen und Herren!\n"
	.string "Hier sind die POKéMON NACHRICHTEN.\p"
	.string "Auf diese Nachricht haben Sie schon\n"
	.string "sehnsüchtig gewartet!\p"
	.string "Im SEEGRASULB CITY EINKAUFSZENTRUM\n"
	.string "findet heute ein totaler Ausverkauf\l"
	.string "statt!\p"
	.string "Das Dingsbums und das Dingsda, welches\n"
	.string "Sie schon immer haben wollten…\p"
	.string "Sie können sie dort finden!\p"
	.string "Das waren die POKéMON NACHRICHTEN.$"
	.endif
	.endif

gPokeNewsTextLilycove_Ending::
	.ifdef ENGLISH
	.string "Greetings!\n"
	.string "It's time for POKéMON NEWS.\p"
	.string "This is the news you've all been\n"
	.string "waiting for!\p"
	.string "LILYCOVE DEPARTMENT STORE's clear-out\n"
	.string "sale has finally arrived!\p"
	.string "All the thingamajigs and doodads that\n"
	.string "you've always dreamt about…\p"
	.string "You may be in for fateful encounters\n"
	.string "with them all!\p"
	.string "That's the news on POKéMON NEWS.$"
	.else
	.ifdef GERMAN
	.string "Guten Tag meine Damen und Herren!\n"
	.string "Hier sind die POKéMON NACHRICHTEN.\p"
	.string "Auf diese Nachricht haben Sie schon\n"
	.string "sehnsüchtig gewartet!\p"
	.string "Im SEEGRASULB CITY EINKAUFSZENTRUM\n"
	.string "findet heute ein totaler Ausverkauf\l"
	.string "statt!\p"
	.string "Das Dingsbums und das Dingsda, welches\n"
	.string "Sie schon immer haben wollten…\p"
	.string "Sie können sie dort finden!\p"
	.string "Das waren die POKéMON NACHRICHTEN.$"
	.endif
	.endif

gPokeNewsTextBlendMaster_Upcoming::
	.ifdef ENGLISH
	.string "Greetings!\n"
	.string "It's time for POKéMON NEWS.\p"
	.string "We have big news for everyone\n"
	.string "involved in the making of {POKEBLOCK}S.\p"
	.string "The legendary BLEND MASTER will be\n"
	.string "appearing in LILYCOVE CITY with just\l"
	.string "a mere {STR_VAR_1}-day wait to go!\p"
	.string "The BLEND MASTER is said to be\n"
	.string "the best in all HOENN when it comes to\l"
	.string "spinning a BERRY BLENDER.\p"
	.string "Those people who want to make great\n"
	.string "{POKEBLOCK}S or see the MASTER in action\l"
	.string "are urged to save their BERRIES.\p"
	.string "That's the news on POKéMON NEWS.$"
	.else
	.ifdef GERMAN
	.string "Hallo und guten Tag!\n"
	.string "Hier sind die POKéMON NACHRICHTEN.\p"
	.string "Wir haben heute großartige Neuigkeiten\n"
	.string "für all die, die {POKEBLOCK} herstellen.\p"
	.string "Der legendäre MIXMEISTER wird in\n"
	.string "SEEGRASULB CITY sein Können zeigen.\l"
	.string "In nur {STR_VAR_1} Tag(en)!\p"
	.string "Der MIXMEISTER ist der Beste in ganz\n"
	.string "HOENN, wenn es um den BEERENMIXER\l"
	.string "geht.\p"
	.string "Die, die großartige {POKEBLOCK} herstellen\n"
	.string "oder den MEISTER in Aktion sehen\l"
	.string "wollen, sollten ab jetzt sparsam mit\p"
	.string "ihren BEEREn umgehen!\n"
	.string "Das war’s von uns! Bis zum nächsten Mal!$"
	.endif
	.endif

gPokeNewsTextBlendMaster_Ongoing::
	.ifdef ENGLISH
	.string "Greetings!\n"
	.string "It's time for POKéMON NEWS.\p"
	.string "We have big news for everyone\n"
	.string "involved in the making of {POKEBLOCK}S.\p"
	.string "The legendary BLEND MASTER has\n"
	.string "finally appeared!\p"
	.string "The BLEND MASTER is spinning\n"
	.string "the BERRY BLENDER at the LILYCOVE\l"
	.string "CONTEST HALL.\p"
	.string "Those people who want to make great\n"
	.string "{POKEBLOCK}S or see the MASTER in action\l"
	.string "should hurry to LILYCOVE.\p"
	.string "That's the news on POKéMON NEWS.$"
	.else
	.ifdef GERMAN
	.string "Hallo und guten Tag!\n"
	.string "Hier sind die POKéMON NACHRICHTEN.\p"
	.string "Wir haben heute großartige Neuigkeiten\n"
	.string "für all die, die {POKEBLOCK} herstellen.\p"
	.string "Der legendäre MIXMEISTER ist endlich\n"
	.string "hier!\p"
	.string "Der MIXMEISTER zeigt sein Können am\n"
	.string "BEERENMIXER in der WETTBEWERBS-\l"
	.string "HALLE von SEEGRASULB.\p"
	.string "Die, die großartige {POKEBLOCK} herstellen\n"
	.string "oder den MEISTER in Aktion sehen\l"
	.string "wollen, sollten schnell nach SEEGRASULB\p"
	.string "kommen!\n"
	.string "Das war’s von uns! Bis zum nächsten Mal!$"
	.endif
	.endif

gPokeNewsTextBlendMaster_Ending::
	.ifdef ENGLISH
	.string "Greetings!\n"
	.string "It's time for POKéMON NEWS.\p"
	.string "It's incredible!\n"
	.string "Too incredible, even!\p"
	.string "The BERRY BLENDER is spinning at\n"
	.string "a dizzying pace!\p"
	.string "The BLEND MASTER has lived up to\n"
	.string "his reputation!\p"
	.string "The BLEND MASTER will soon be\n"
	.string "leaving LILYCOVE.\p"
	.string "If you haven't seen the MASTER in\n"
	.string "action, don't waste this chance!\l"
	.string "Head to LILYCOVE right now!\p"
	.string "That's the news on POKéMON NEWS.$"
	.else
	.ifdef GERMAN
	.string "Hallo und guten Tag!\n"
	.string "Hier sind die POKéMON NACHRICHTEN.\p"
	.string "Es ist unglaublich!\n"
	.string "Einfach unbeschreiblich!\p"
	.string "Der BEERENMIXER dreht sich in\n"
	.string "Schwindel erregender Geschwindigkeit!\p"
	.string "Der MIXMEISTER macht seinem Titel\n"
	.string "alle Ehre!\p"
	.string "Bald wird er SEEGRASULB wieder\n"
	.string "verlassen.\p"
	.string "Wenn ihr den MIXMEISTER noch nicht\n"
	.string "in Aktion gesehen habt, dann beeilt\l"
	.string "euch und kommt schnell nach\p"
	.string "SEEGRASULB!\n"
	.string "Das war’s von uns! Bis zum nächsten Mal!$"
	.endif
	.endif
