Questionnaire_Text_FillOut::
	.ifdef ENGLISH
	.string "There is a questionnaire.\n"
	.string "Would you like to fill it out?$"
	.else
	.ifdef GERMAN
	.string "Dort liegt ein Fragebogen.\n"
	.string "Möchtest du ihn ausfüllen?$"
	.endif
	.endif

Questionnaire_Text_ThankYou::
	.ifdef ENGLISH
	.string "Thank you for taking the time to\n"
	.string "fill out our questionnaire.\p"
	.string "Your feedback will be used for\n"
	.string "future reference.$"
	.else
	.ifdef GERMAN
	.string "Danke, dass du dir die Zeit\n"
	.string "genommen hast, den\l"
	.string "Fragebogen auszufüllen.\l"
	.string "Deine Antworten werden ausgewertet\l"
	.string "und zukünftig berücksichtigt.$"
	.endif
	.endif

Questionnaire_Text_YouKnowThoseWordsGift::
	.ifdef ENGLISH
	.string "Oh, hello!\n"
	.string "You know those words?\p"
	.string "That means you must know about\n"
	.string "the MYSTERY GIFT.\p"
	.string "From now on, you should be\n"
	.string "receiving MYSTERY GIFTS!$"
	.else
	.ifdef GERMAN
	.string "Oh, hallo!\n"
	.string "Kennst du diese Worte?\p"
	.string "Das bedeutet, du weißt über die\n"
	.string "GEHEIMGESCHEHEN Bescheid.\p"
	.string "Von nun an kannst du\n"
	.string "GEHEIMGESCHEHEN empfangen.$"
	.endif
	.endif

Questionnaire_Text_YouCanAccessMysteryGift::
	.ifdef ENGLISH
	.string "Once you save your game, you can\n"
	.string "access the MYSTERY GIFT.$"
	.else
	.ifdef GERMAN
	.string "Sobald du dein Spiel gesichert\n"
	.string "hast, kannst du GEHEIMGESCHEHEN\l"
	.string "auswählen.$"
	.endif
	.endif

Questionnaire_Text_YouKnowThoseWordsEvent::
	.ifdef ENGLISH
	.string "Oh, hello!\n"
	.string "You know those words?\p"
	.string "That means you must know about\n"
	.string "the MYSTERY EVENT.$"
	.else
	.ifdef GERMAN
	.string "Oh, hallo!\n"
	.string "Kennst du diese Worte?\p"
	.string "Das bedeutet, du weißt über die\n"
	.string "GEHEIMGESCHEHEN Bescheid.$"
	.endif
	.endif

Questionnaire_Text_YouCanAccessMysteryEvent::
	.ifdef ENGLISH
	.string "Once you save your game, you can\n"
	.string "access the MYSTERY EVENT.$"
	.else
	.ifdef GERMAN
	.string "Sobald du dein Spiel gesichert\n"
	.string "hast, kannst du GEHEIMGESCHEHEN\l"
	.string "auswählen.$"
	.endif
	.endif

MysteryGift_Text_TheresATicketForYou::
	.ifdef ENGLISH
	.string "Thank you for using the MYSTERY\n"
	.string "EVENT System.\p"
	.string "You must be {PLAYER}.\n"
	.string "There is a ticket here for you.$"
	.else
	.ifdef GERMAN
	.string "Danke, dass du das GEHEIM-\n"
	.string "GESCHEHEN benutzt hast.\p"
	.string "Du musst {PLAYER} sein.\n"
	.string "Hier ist ein Ticket für dich!$"
	.endif
	.endif

MysteryGift_Text_TryUsingItAtLilycovePort::
	.ifdef ENGLISH
	.string "It appears to be for use at\n"
	.string "the LILYCOVE CITY port.\p"
	.string "Why not give it a try and see what\n"
	.string "it is about?$"
	.else
	.ifdef GERMAN
	.string "Du kannst es am Hafen von\n"
	.string "SEEGRASULB CITY einsetzen.\p"
	.string "Warum probierst du es nicht\n"
	.string "einfach aus?$"
	.endif
	.endif
