SecretBase_Text_Trainer0Intro:
	.ifdef ENGLISH
	.string "Have you made a SECRET BASE already?\p"
	.string "I went here, there, everywhere before\n"
	.string "choosing this place.\p"
	.string "Since you're already here, how would\n"
	.string "you like to battle?$"
	.else
	.ifdef GERMAN
	.string "Hast du dir schon eine GEHEIMBASIS\n"
	.string "eingerichtet?\p"
	.string "Ich bin hier und dort, überall hin-\n"
	.string "gelaufen, bevor ich mich für diesen\l"
	.string "Ort entschieden habe.\p"
	.string "Da du schon mal hier bist… Hast du\n"
	.string "Lust zu kämpfen?$"
	.endif
	.endif

SecretBase_Text_Trainer0AcceptBattle:
	.ifdef ENGLISH
	.string "Okay!\n"
	.string "Here we come!$"
	.else
	.ifdef GERMAN
	.string "Okay!\n"
	.string "Jetzt kommen wir!$"
	.endif
	.endif

SecretBase_Text_Trainer0DeclineBattle:
	.ifdef ENGLISH
	.string "Hunh?\n"
	.string "Oh, you can't now…$"
	.else
	.ifdef GERMAN
	.string "Wie? Was? Wo?\n"
	.string "Du kannst doch nicht…$"
	.endif
	.endif

SecretBase_Text_Trainer0Defeated::
	.ifdef ENGLISH
	.string "Waaargh! You're too strong!\n"
	.string "About me losing… Please keep it secret!$"
	.else
	.ifdef GERMAN
	.string "Ahaaargh! Du bist zu stark für mich! Ich\n"
	.string "habe verloren, aber verrate das nicht!$"
	.endif
	.endif

SecretBase_Text_Trainer0PostBattle:
	.ifdef ENGLISH
	.string "What do you think of my SECRET BASE?\n"
	.string "Come visit me again tomorrow.$"
	.else
	.ifdef GERMAN
	.string "Was hältst du von meiner GEHEIMBASIS?\n"
	.string "Komm mich doch morgen wieder besuchen!$"
	.endif
	.endif

SecretBase_Text_Trainer0PreChampion:
	.ifdef ENGLISH
	.string "Have you made a SECRET BASE already?\p"
	.string "I went here, there, everywhere before\n"
	.string "choosing this place.\p"
	.string "Feel free to hang out!$"
	.else
	.ifdef GERMAN
	.string "Hast du dir schon eine GEHEIMBASIS\n"
	.string "eingerichtet?\p"
	.string "Ich bin hier und dort, überall hin-\n"
	.string "gelaufen, bevor ich mich für diesen\l"
	.string "Ort entschieden habe.\p"
	.string "Schau dich ruhig in aller Ruhe um.$"
	.endif
	.endif

SecretBase_Text_Trainer5Intro:
	.ifdef ENGLISH
	.string "There're a lot of places where\n"
	.string "you can make a SECRET BASE.\p"
	.string "But I like this spot best.\n"
	.string "Don't you think it's nice?\p"
	.string "Oh, would you like to have a battle?$"
	.else
	.ifdef GERMAN
	.string "Es gibt eine Menge Orte, an denen man\n"
	.string "eine GEHEIMBASIS einrichten kann.\p"
	.string "Aber dieser hier gefällt mir am besten.\n"
	.string "Findest du es nicht auch nett hier?\p"
	.string "Oh, hast du Lust auf einen Kampf?$"
	.endif
	.endif

SecretBase_Text_Trainer5AcceptBattle:
	.ifdef ENGLISH
	.string "Okay, here goes!$"
	.else
	.ifdef GERMAN
	.string "Okay, los geht’s!$"
	.endif
	.endif

SecretBase_Text_Trainer5DeclineBattle:
	.ifdef ENGLISH
	.string "Oh…\n"
	.string "You can't now, okay.$"
	.else
	.ifdef GERMAN
	.string "Oh…\n"
	.string "Du hast gerade keine Zeit.$"
	.endif
	.endif

SecretBase_Text_Trainer5Defeated::
	.ifdef ENGLISH
	.string "Hmmm… It's our loss…\n"
	.string "But don't tell anyone!\l"
	.string "It's a confidential secret!$"
	.else
	.ifdef GERMAN
	.string "Hmm… Das ist unsere Niederlage…\n"
	.string "Aber erzähl das bloß nicht weiter!\l"
	.string "Das ist ein streng geheimes Geheimnis!$"
	.endif
	.endif

SecretBase_Text_Trainer5PostBattle:
	.ifdef ENGLISH
	.string "If you're in this area again,\n"
	.string "I hope you'll visit me.$"
	.else
	.ifdef GERMAN
	.string "Wenn du wieder mal in der Nähe bist,\n"
	.string "komm mich doch besuchen!$"
	.endif
	.endif

SecretBase_Text_Trainer5PreChampion:
	.ifdef ENGLISH
	.string "There're a lot of places where you can\n"
	.string "make a SECRET BASE.\p"
	.string "But I like this spot best.\n"
	.string "Don't you think it's nice?$"
	.else
	.ifdef GERMAN
	.string "Es gibt eine Menge Orte, an denen man\n"
	.string "eine GEHEIMBASIS einrichten kann.\p"
	.string "Aber dieser hier gefällt mir am besten.\n"
	.string "Findest du es nicht auch nett hier?$"
	.endif
	.endif

SecretBase_Text_Trainer1Intro:
	.ifdef ENGLISH
	.string "This is a popular spot.\n"
	.string "It's always taken.\p"
	.string "Oh! Were you thinking about\n"
	.string "taking this spot, too?\p"
	.string "I'll tell you what, you can have this\n"
	.string "spot if you can beat me.$"
	.else
	.ifdef GERMAN
	.string "Dies ist ein beliebter Platz.\n"
	.string "Er ist eigentlich immer besetzt.\p"
	.string "Ach, du wolltest dich hier auch\n"
	.string "häuslich niederlassen?\p"
	.string "Ich sag dir was: Du kannst den Platz\n"
	.string "haben, wenn du mich besiegen kannst.$"
	.endif
	.endif

SecretBase_Text_Trainer1AcceptBattle:
	.ifdef ENGLISH
	.string "Okay!\n"
	.string "I'm going to defend my SECRET BASE!$"
	.else
	.ifdef GERMAN
	.string "Okay! Ich werde meine\n"
	.string "GEHEIMBASIS verteidigen!$"
	.endif
	.endif

SecretBase_Text_Trainer1DeclineBattle:
	.ifdef ENGLISH
	.string "Hunh? Is that right?\n"
	.string "You're not interested in this spot?$"
	.else
	.ifdef GERMAN
	.string "Was? Stimmt das? Du hast gar\n"
	.string "kein Interesse an diesem Platz?!?$"
	.endif
	.endif

SecretBase_Text_Trainer1Defeated::
	.ifdef ENGLISH
	.string "I can't keep going!\n"
	.string "I surrender!$"
	.else
	.ifdef GERMAN
	.string "Ich kann nicht mehr!\n"
	.string "Ich gebe mich geschlagen!$"
	.endif
	.endif

SecretBase_Text_Trainer1PostBattle:
	.ifdef ENGLISH
	.string "Okay, when I move one day,\n"
	.string "this place will be yours!$"
	.else
	.ifdef GERMAN
	.string "Okay, wenn ich eines Tages von hier\n"
	.string "fortziehe, kannst du den Platz haben.$"
	.endif
	.endif

SecretBase_Text_Trainer1PreChampion:
	.ifdef ENGLISH
	.string "This is a popular spot.\n"
	.string "It's always taken.\p"
	.string "I waited a long time for it to open.\n"
	.string "I finally got to use it!$"
	.else
	.ifdef GERMAN
	.string "Dies ist ein beliebter Platz.\n"
	.string "Er ist eigentlich immer besetzt.\p"
	.string "Ich habe ewig gewartet, bis er wieder\n"
	.string "frei wurde. Endlich ist es soweit!$"
	.endif
	.endif

SecretBase_Text_Trainer6Intro:
	.ifdef ENGLISH
	.string "Welcome to my POKéMON LAB.\p"
	.string "I carry out research on battling in\n"
	.string "secrecy.\p"
	.string "Would you like to see how strong I am?$"
	.else
	.ifdef GERMAN
	.string "Willkommen in meinem POKéMON-LABOR.\p"
	.string "Ich forsche, indem ich im Geheimen\n"
	.string "kämpfe.\p"
	.string "Möchtest du sehen, wie stark ich bin?$"
	.endif
	.endif

SecretBase_Text_Trainer6AcceptBattle:
	.ifdef ENGLISH
	.string "I'm going to go all out!$"
	.else
	.ifdef GERMAN
	.string "Das war ja wohl nichts!$"
	.endif
	.endif

SecretBase_Text_Trainer6DeclineBattle:
	.ifdef ENGLISH
	.string "Oh.\n"
	.string "Some other time, then!$"
	.else
	.ifdef GERMAN
	.string "Oh.\n"
	.string "Ein anderes Mal vielleicht…$"
	.endif
	.endif

SecretBase_Text_Trainer6Defeated::
	.ifdef ENGLISH
	.string "Hmm… I've still got lots to learn.\n"
	.string "I have to study some more.$"
	.else
	.ifdef GERMAN
	.string "Hm… Ich muss noch viel lernen.\n"
	.string "Ich muss fleißiger studieren.$"
	.endif
	.endif

SecretBase_Text_Trainer6PostBattle:
	.ifdef ENGLISH
	.string "Thanks for battling with me.\n"
	.string "Please come back again tomorrow.$"
	.else
	.ifdef GERMAN
	.string "Danke, dass du mit mir gekämpft hast.\n"
	.string "Komm doch bitte morgen wieder.$"
	.endif
	.endif

SecretBase_Text_Trainer6PreChampion:
	.ifdef ENGLISH
	.string "Welcome to my POKéMON LAB.\p"
	.string "I carry out research on battling in\n"
	.string "secrecy.$"
	.else
	.ifdef GERMAN
	.string "Willkommen in meinem POKéMON-LABOR.\p"
	.string "Ich forsche, indem ich im Geheimen\n"
	.string "kämpfe.$"
	.endif
	.endif

SecretBase_Text_Trainer2Intro:
	.ifdef ENGLISH
	.string "A big mansion is nice, but I like this\n"
	.string "sort of place more.\p"
	.string "I like it because all kinds of people\n"
	.string "come visit me.\p"
	.string "So, how would you like a battle?$"
	.else
	.ifdef GERMAN
	.string "Ein großes Anwesen ist natürlich auch\n"
	.string "ganz nett, aber hier ist es schöner.\p"
	.string "Viele Leute kommen mich besuchen.\p"
	.string "So. Wie wäre es mit einem Kampf?$"
	.endif
	.endif

SecretBase_Text_Trainer2AcceptBattle:
	.ifdef ENGLISH
	.string "That's the way!$"
	.else
	.ifdef GERMAN
	.string "Genauso muss es laufen!$"
	.endif
	.endif

SecretBase_Text_Trainer2DeclineBattle:
	.ifdef ENGLISH
	.string "When you're ready, give me a shout!$"
	.else
	.ifdef GERMAN
	.string "Wenn du bereit bist, sag Bescheid.$"
	.endif
	.endif

SecretBase_Text_Trainer2Defeated::
	.ifdef ENGLISH
	.string "Aww! Done in!\n"
	.string "But it's still fun to battle!$"
	.else
	.ifdef GERMAN
	.string "Ooch! Ich hab’s vergeigt!\n"
	.string "Aber es hat sehr viel Spaß gemacht!$"
	.endif
	.endif

SecretBase_Text_Trainer2PostBattle:
	.ifdef ENGLISH
	.string "Well, anyway, I should go buy some\n"
	.string "decorations and furniture.\p"
	.string "I want my SECRET BASE to be a place\n"
	.string "other people can enjoy.$"
	.else
	.ifdef GERMAN
	.string "Egal. Ich sollte mir auf jeden Fall\n"
	.string "einige Dekorationen und Möbel zulegen.\p"
	.string "Ich möchte, dass sich auch andere in\n"
	.string "meiner GEHEIMBASIS wohl fühlen.$"
	.endif
	.endif

SecretBase_Text_Trainer2PreChampion:
	.ifdef ENGLISH
	.string "A big mansion is nice, but I like this\n"
	.string "sort of place more.\p"
	.string "I like it because all kinds of people\n"
	.string "come visit me.$"
	.else
	.ifdef GERMAN
	.string "Ein großes Anwesen ist natürlich auch\n"
	.string "ganz nett, aber hier ist es schöner.\p"
	.string "Viele Leute kommen mich besuchen.$"
	.endif
	.endif

SecretBase_Text_Trainer7Intro:
	.ifdef ENGLISH
	.string "I simply adore shopping for decorations\n"
	.string "and furniture.\p"
	.string "I also love raising POKéMON just\n"
	.string "as much.\p"
	.string "If you would be so kind, will you battle\n"
	.string "with my POKéMON?$"
	.else
	.ifdef GERMAN
	.string "Ich liebe es, Dekorationen und Möbel\n"
	.string "zu kaufen!!!\p"
	.string "Ich liebe es genauso, POKéMON aufzu-\n"
	.string "ziehen!\p"
	.string "Wärest du so nett, mit meinen\n"
	.string "POKéMON zu kämpfen?$"
	.endif
	.endif

SecretBase_Text_Trainer7AcceptBattle:
	.ifdef ENGLISH
	.string "Thank you.\n"
	.string "Shall we begin?$"
	.else
	.ifdef GERMAN
	.string "Danke schön.\n"
	.string "Bist du bereit?$"
	.endif
	.endif

SecretBase_Text_Trainer7DeclineBattle:
	.ifdef ENGLISH
	.string "Oh.\n"
	.string "How disappointing…$"
	.else
	.ifdef GERMAN
	.string "Oh.\n"
	.string "Was für eine Enttäuschung.$"
	.endif
	.endif

SecretBase_Text_Trainer7Defeated::
	.ifdef ENGLISH
	.string "I concede…$"
	.else
	.ifdef GERMAN
	.string "Ich ergebe mich!$"
	.endif
	.endif

SecretBase_Text_Trainer7PostBattle:
	.ifdef ENGLISH
	.string "That was all in good fun!\n"
	.string "I should go enjoy shopping now.$"
	.else
	.ifdef GERMAN
	.string "Das war vielleicht ein Spaß! Und nun\n"
	.string "sollte ich mich dem Einkaufen widmen.$"
	.endif
	.endif

SecretBase_Text_Trainer7PreChampion:
	.ifdef ENGLISH
	.string "I simply adore shopping for decorations\n"
	.string "and furniture.\p"
	.string "I also love raising POKéMON just\n"
	.string "as much.$"
	.else
	.ifdef GERMAN
	.string "Ich liebe es, Dekorationen und Möbel\n"
	.string "zu kaufen!!!\p"
	.string "Ich liebe es genauso, POKéMON aufzu-\n"
	.string "ziehen!$"
	.endif
	.endif

SecretBase_Text_Trainer3Intro:
	.ifdef ENGLISH
	.string "Some people make their SECRET BASES in\n"
	.string "hard-to-find places.\l"
	.string "Do they want to just lie low?\p"
	.string "But since you found me, how about we\n"
	.string "have a battle?$"
	.else
	.ifdef GERMAN
	.string "Einige Leute richten ihre GEHEIMBASIS\n"
	.string "an gut versteckten Orten ein. Wollen\l"
	.string "sie sich nicht mehr sehen lassen?\p"
	.string "Da du mich gefunden hast, lass uns\n"
	.string "doch gleich mal kämpfen.$"
	.endif
	.endif

SecretBase_Text_Trainer3AcceptBattle:
	.ifdef ENGLISH
	.string "I'm not going down easily!$"
	.else
	.ifdef GERMAN
	.string "Ich bin nicht einfach zu besiegen!$"
	.endif
	.endif

SecretBase_Text_Trainer3DeclineBattle:
	.ifdef ENGLISH
	.string "Oh… Are you maybe tired from searching\n"
	.string "for this place?$"
	.else
	.ifdef GERMAN
	.string "Oh. Sag bloß, du bist müde von der Suche\n"
	.string "nach diesem Platz?$"
	.endif
	.endif

SecretBase_Text_Trainer3Defeated::
	.ifdef ENGLISH
	.string "I went down…$"
	.else
	.ifdef GERMAN
	.string "Ich bin untergegangen…$"
	.endif
	.endif

SecretBase_Text_Trainer3PostBattle:
	.ifdef ENGLISH
	.string "Where's your SECRET BASE?\n"
	.string "I should go visit you there.$"
	.else
	.ifdef GERMAN
	.string "Wo ist deine GEHEIMBASIS?\n"
	.string "Ich sollte dich dort mal besuchen.$"
	.endif
	.endif

SecretBase_Text_Trainer3PreChampion:
	.ifdef ENGLISH
	.string "Some people make their SECRET BASES in\n"
	.string "hard-to-find places.\l"
	.string "Do they want to just lie low?$"
	.else
	.ifdef GERMAN
	.string "Einige Leute richten ihre GEHEIMBASIS\n"
	.string "an gut versteckten Orten ein. Wollen\l"
	.string "sie sich nicht mehr sehen lassen?$"
	.endif
	.endif

SecretBase_Text_Trainer8Intro:
	.ifdef ENGLISH
	.string "People have told me that you can get\n"
	.string "decorations in several ways.\p"
	.string "We should have a race to see who can\n"
	.string "get nicer decorations and furniture!\p"
	.string "In the meantime, want to battle?$"
	.else
	.ifdef GERMAN
	.string "Einige Leute haben mir erzählt, dass\n"
	.string "man auf verschiedene Arten an Deko-\l"
	.string "rationen kommen kann.\p"
	.string "Wir sollten einen Wettbewerb veran-\n"
	.string "stalten, wer die schönsten Dinge hat.\p"
	.string "Aber zuerst lass uns kämpfen.$"
	.endif
	.endif

SecretBase_Text_Trainer8AcceptBattle:
	.ifdef ENGLISH
	.string "This is my SECRET BASE.\n"
	.string "I can't lose!$"
	.else
	.ifdef GERMAN
	.string "Das ist meine GEHEIMBASIS.\n"
	.string "Ich kann hier gar nicht verlieren!$"
	.endif
	.endif

SecretBase_Text_Trainer8DeclineBattle:
	.ifdef ENGLISH
	.string "I'll battle with you anytime.$"
	.else
	.ifdef GERMAN
	.string "Ich kämpfe jederzeit mit dir.$"
	.endif
	.endif

SecretBase_Text_Trainer8Defeated::
	.ifdef ENGLISH
	.string "Huh?\n"
	.string "Did I just lose?$"
	.else
	.ifdef GERMAN
	.string "Wie?\n"
	.string "Ich habe doch verloren?$"
	.endif
	.endif

SecretBase_Text_Trainer8PostBattle:
	.ifdef ENGLISH
	.string "I won't lose at collecting decorations.\n"
	.string "Come visit again!$"
	.else
	.ifdef GERMAN
	.string "Ich werde den Wettbewerb um die\n"
	.string "schönsten Dekorationen nicht ver-\l"
	.string "lieren. Überzeuge dich selbst!$"
	.endif
	.endif

SecretBase_Text_Trainer8PreChampion:
	.ifdef ENGLISH
	.string "People have told me that you can get\n"
	.string "decorations in several ways.\p"
	.string "We should have a race to see who can\n"
	.string "get nicer decorations and furniture!$"
	.else
	.ifdef GERMAN
	.string "Einige Leute haben mir erzählt, dass\n"
	.string "man auf verschiedene Arten an Deko-\l"
	.string "rationen kommen kann.\p"
	.string "Wir sollten einen Wettbewerb veran-\n"
	.string "stalten, wer die schönsten Dinge hat.$"
	.endif
	.endif

SecretBase_Text_Trainer4Intro:
	.ifdef ENGLISH
	.string "I found a spot I liked, and I did it up\n"
	.string "with my favorite decorations.\p"
	.string "I raise my favorite POKéMON and grow\n"
	.string "stronger with it.\p"
	.string "That's what I do.\n"
	.string "Want to battle with me?$"
	.else
	.ifdef GERMAN
	.string "Ich habe einen Ort gefunden, der mir\n"
	.string "gefällt und den ich mit meinen Lieb-\l"
	.string "lingsdekorationen ausgestattet habe.\p"
	.string "Dort ziehe ich meine Lieblings-POKéMON\n"
	.string "auf und werde mit ihnen stärker.\p"
	.string "Genau das mache ich.\n"
	.string "Möchtest du mit mir kämpfen?$"
	.endif
	.endif

SecretBase_Text_Trainer4AcceptBattle:
	.ifdef ENGLISH
	.string "Show me what you're made of!$"
	.else
	.ifdef GERMAN
	.string "Zeig mir, aus welchem Holz du\n"
	.string "geschnitzt bist.$"
	.endif
	.endif

SecretBase_Text_Trainer4DeclineBattle:
	.ifdef ENGLISH
	.string "I guess there are times when you're not\n"
	.string "into it.$"
	.else
	.ifdef GERMAN
	.string "Ich glaube, es gibt immer wieder Zeiten,\n"
	.string "in denen man nicht so gut drauf ist.$"
	.endif
	.endif

SecretBase_Text_Trainer4Defeated::
	.ifdef ENGLISH
	.string "I know exactly what you're made of now.$"
	.else
	.ifdef GERMAN
	.string "Ich weiß jetzt genau, aus welchem Holz\n"
	.string "du geschnitzt bist.$"
	.endif
	.endif

SecretBase_Text_Trainer4PostBattle:
	.ifdef ENGLISH
	.string "We can both become stronger.\n"
	.string "Let's keep at it!$"
	.else
	.ifdef GERMAN
	.string "Wir können beide noch stärker werden!\n"
	.string "Das macht doch Mut!$"
	.endif
	.endif

SecretBase_Text_Trainer4PreChampion:
	.ifdef ENGLISH
	.string "I found a spot I liked, and I did it up\n"
	.string "with my favorite decorations.\p"
	.string "I raise my favorite POKéMON and grow\n"
	.string "stronger with it.\p"
	.string "Every day is a great day.$"
	.else
	.ifdef GERMAN
	.string "Ich habe einen Ort gefunden, der mir\n"
	.string "gefällt und den ich mit meinen Lieb-\l"
	.string "lingsdekorationen ausgestattet habe.\p"
	.string "Dort ziehe ich meine Lieblings-POKéMON\n"
	.string "auf und werde mit ihnen stärker.\p"
	.string "Jeder Tag ist mein Lieblingstag.$"
	.endif
	.endif

SecretBase_Text_Trainer9Intro:
	.ifdef ENGLISH
	.string "You can learn a lot about the taste\n"
	.string "and sense of people by the kinds of\l"
	.string "decorations they have, and how they\l"
	.string "display them.\p"
	.string "What do you think of my taste?\n"
	.string "Are you speechless?\p"
	.string "Want to see my taste in battling?$"
	.else
	.ifdef GERMAN
	.string "Man lernt viel über den Geschmack und\n"
	.string "den Stil von Menschen, wenn man sich\l"
	.string "ihre Dekorationen und den Platz, auf\l"
	.string "dem sie stehen, anschaut.\p"
	.string "Wie findest du meinen Geschmack?\n"
	.string "Bist du sprachlos? Hihihi…\p"
	.string "Willst du mal meinen Kampfstil sehen?$"
	.endif
	.endif

SecretBase_Text_Trainer9AcceptBattle:
	.ifdef ENGLISH
	.string "There's no holding back!$"
	.else
	.ifdef GERMAN
	.string "Es gibt kein Zurück mehr.$"
	.endif
	.endif

SecretBase_Text_Trainer9DeclineBattle:
	.ifdef ENGLISH
	.string "I'll be happy to demonstrate my style\n"
	.string "anytime.$"
	.else
	.ifdef GERMAN
	.string "Ich zeige dir gerne jederzeit wieder \n"
	.string "meinen erlesenen Kampfstil!$"
	.endif
	.endif

SecretBase_Text_Trainer9Defeated::
	.ifdef ENGLISH
	.string "You're supremely talented!\n"
	.string "Your power seems to be limitless…$"
	.else
	.ifdef GERMAN
	.string "Du bist hoch talentiert! Deine Stärke\n"
	.string "scheint grenzenlos zu sein.$"
	.endif
	.endif

SecretBase_Text_Trainer9PostBattle:
	.ifdef ENGLISH
	.string "What did you think of my style?\n"
	.string "I'll keep on polishing it!$"
	.else
	.ifdef GERMAN
	.string "Was hältst du von meinem Stil?\n"
	.string "Ich muss ihn noch mehr aufpolieren.$"
	.endif
	.endif

SecretBase_Text_Trainer9PreChampion:
	.ifdef ENGLISH
	.string "You can learn a lot about the taste\n"
	.string "and sense of people by the kinds of\l"
	.string "decorations they have, and how they\l"
	.string "display them.\p"
	.string "What do you think of my taste?\n"
	.string "Are you speechless?$"
	.else
	.ifdef GERMAN
	.string "Man lernt viel über den Geschmack und\n"
	.string "den Stil von Menschen, wenn man sich\l"
	.string "ihre Dekorationen und den Platz, auf\l"
	.string "dem sie stehen, anschaut.\p"
	.string "Wie findest du meinen Geschmack?\n"
	.string "Bist du sprachlos? Hihihi…$"
	.endif
	.endif
