ShoalCave_LowTideEntranceRoom_Text_AreYouPlanningOnGoingInThere:
	.ifdef ENGLISH
	.string "Are you planning on going deep\n"
	.string "in there?\p"
	.string "How about bringing me back some\n"
	.string "SHOAL SALT and SHOAL SHELLS?\p"
	.string "I can make you something good if\n"
	.string "you bring me the ingredients.$"
	.else
	.ifdef GERMAN
	.string "Hast du vor, tiefer hineinzugehen?\p"
	.string "Würdest du mir bitte KÜSTENSALZ\n"
	.string "und KÜSTENSCHALEn mitbringen?\p"
	.string "Ich kann dir daraus etwas Wunderbares\n"
	.string "anfertigen.$"
	.endif
	.endif

ShoalCave_LowTideEntranceRoom_Text_BringMe4ShoalSaltAndShells:
	.ifdef ENGLISH
	.string "If you bring me four each of the\n"
	.string "SHOAL SALT and SHOAL SHELLS,\l"
	.string "I can make you a SHELL BELL…\p"
	.string "You can get those ingredients\n"
	.string "every day.$"
	.else
	.ifdef GERMAN
	.string "Wenn du mir jeweils viermal KÜSTENSALZ\n"
	.string "und KÜSTENSCHALE mitbringst, fertige\l"
	.string "ich dir SEEGESANG daraus an.\p"
	.string "Jeder Tag ist ein guter Tag, die Zutaten\n"
	.string "dafür zu finden…$"
	.endif
	.endif

ShoalCave_LowTideEntranceRoom_Text_WouldYouLikeShellBell:
	.ifdef ENGLISH
	.string "Oh, hey! SHOAL SALT and SHOAL SHELLS!\n"
	.string "And enough of them, too!\p"
	.string "Would you like me to make you\n"
	.string "a SHELL BELL with them?$"
	.else
	.ifdef GERMAN
	.string "Oh, hey! KÜSTENSALZ und KÜSTENSCHALE!\n"
	.string "Und davon auch noch so viele!\p"
	.string "Soll ich dir daraus SEEGESANG\n"
	.string "anfertigen?$"
	.endif
	.endif

ShoalCave_LowTideEntranceRoom_Text_MakeShellBellRightAway:
	.ifdef ENGLISH
	.string "All righty, then! I'll make you\n"
	.string "a SHELL BELL right away.\p"
	.string "… … … … … … … …\n"
	.string "… … … … … … … …\p"
	.string "There! Done!$"
	.else
	.ifdef GERMAN
	.string "Sehr schön! Ich werde dir sofort\n"
	.string "SEEGESANG anfertigen.\p"
	.string "… … … … … … … …\n"
	.string "… … … … … … … …\p"
	.string "Fertig! Bitte schön!$"
	.endif
	.endif

ShoalCave_LowTideEntranceRoom_Text_ExplainShellBell:
	.ifdef ENGLISH
	.string "Have a POKéMON hold on to that.\n"
	.string "It'll love it, that's for certain.\p"
	.string "Why, the SHELL BELL's chime…\n"
	.string "It's simply sublime!\p"
	.string "You can get its ingredients every day,\n"
	.string "so I can make you more.$"
	.else
	.ifdef GERMAN
	.string "Gib das einem POKéMON zum Tragen.\n"
	.string "Es wird das lieben, das garantiere ich!\p"
	.string "Der Klang von SEEGESANG…\n"
	.string "Er ist einfach vollendet!\p"
	.string "Die Zutaten kannst du jeden Tag finden,\n"
	.string "daher kann ich dir mehrere machen.$"
	.endif
	.endif

ShoalCave_LowTideEntranceRoom_Text_WantedToMakeShellBell:
	.ifdef ENGLISH
	.string "Oh… Is that so…\n"
	.string "I wanted to make a SHELL BELL…$"
	.else
	.ifdef GERMAN
	.string "Oh… Wirklich?\n"
	.string "Ich wollte SEEGESANG anfertigen…$"
	.endif
	.endif

ShoalCave_LowTideEntranceRoom_Text_NoSpaceInYourBag:
	.ifdef ENGLISH
	.string "You don't have space in your BAG\n"
	.string "if I were to make it for you.\p"
	.string "You should make room and come back\n"
	.string "for a SHELL BELL.$"
	.else
	.ifdef GERMAN
	.string "In deinem BEUTEL ist nicht genügend\n"
	.string "Platz für das neue Item.\p"
	.string "Schaffe Platz und hole dir dann\n"
	.string "SEEGESANG bei mir ab.$"
	.endif
	.endif

ShoalCave_Text_WasShoalSaltNowNothing:
	.ifdef ENGLISH
	.string "There was some SHOAL SALT here.\n"
	.string "But, there's nothing here now.$"
	.else
	.ifdef GERMAN
	.string "Hier gab es mal KÜSTENSALZ.\n"
	.string "Aber jetzt ist nichts mehr davon da.$"
	.endif
	.endif

ShoalCave_Text_WasShoallShellNowNothing:
	.ifdef ENGLISH
	.string "There was a SHOAL SHELL here.\n"
	.string "But, there's nothing here now.$"
	.else
	.ifdef GERMAN
	.string "Hier gab es mal eine KÜSTENSCHALE.\n"
	.string "Aber jetzt gibt es keine mehr.$"
	.endif
	.endif
