gTrickHouse_Mechadoll_Oddish::
	.ifdef ENGLISH
	.string "ODDISH$"
	.else
	.ifdef GERMAN
	.string "MYRAPLA$"
	.endif
	.endif

gTrickHouse_Mechadoll_Poochyena::
	.ifdef ENGLISH
	.string "POOCHYENA$"
	.else
	.ifdef GERMAN
	.string "FIFFYEN$"
	.endif
	.endif

gTrickHouse_Mechadoll_Taillow::
	.ifdef ENGLISH
	.string "TAILLOW$"
	.else
	.ifdef GERMAN
	.string "SCHWALBINI$"
	.endif
	.endif

gTrickHouse_Mechadoll_Azurill::
	.ifdef ENGLISH
	.string "AZURILL$"
	.else
	.ifdef GERMAN
	.string "AZURILL$"
	.endif
	.endif

gTrickHouse_Mechadoll_Lotad::
	.ifdef ENGLISH
	.string "LOTAD$"
	.else
	.ifdef GERMAN
	.string "LOTURZEL$"
	.endif
	.endif

gTrickHouse_Mechadoll_Wingull::
	.ifdef ENGLISH
	.string "WINGULL$"
	.else
	.ifdef GERMAN
	.string "WINGULL$"
	.endif
	.endif

gTrickHouse_Mechadoll_Dustox::
	.ifdef ENGLISH
	.string "DUSTOX$"
	.else
	.ifdef GERMAN
	.string "PUDOX$"
	.endif
	.endif

gTrickHouse_Mechadoll_Zubat::
	.ifdef ENGLISH
	.string "ZUBAT$"
	.else
	.ifdef GERMAN
	.string "ZUBAT$"
	.endif
	.endif

gTrickHouse_Mechadoll_Nincada::
	.ifdef ENGLISH
	.string "NINCADA$"
	.else
	.ifdef GERMAN
	.string "NINCADA$"
	.endif
	.endif

gTrickHouse_Mechadoll_Ralts::
	.ifdef ENGLISH
	.string "RALTS$"
	.else
	.ifdef GERMAN
	.string "TRASLA$"
	.endif
	.endif

gTrickHouse_Mechadoll_Zigzagoon::
	.ifdef ENGLISH
	.string "ZIGZAGOON$"
	.else
	.ifdef GERMAN
	.string "ZIGZACHS$"
	.endif
	.endif

gTrickHouse_Mechadoll_Slakoth::
	.ifdef ENGLISH
	.string "SLAKOTH$"
	.else
	.ifdef GERMAN
	.string "BUMMELZ$"
	.endif
	.endif

gTrickHouse_Mechadoll_Poochyena2::
	.ifdef ENGLISH
	.string "POOCHYENA$"
	.else
	.ifdef GERMAN
	.string "FIFFYEN$"
	.endif
	.endif

gTrickHouse_Mechadoll_Shroomish::
	.ifdef ENGLISH
	.string "SHROOMISH$"
	.else
	.ifdef GERMAN
	.string "KNILZ$"
	.endif
	.endif

gTrickHouse_Mechadoll_Zigzagoon2::
	.ifdef ENGLISH
	.string "ZIGZAGOON$"
	.else
	.ifdef GERMAN
	.string "ZIGZACHS$"
	.endif
	.endif

gTrickHouse_Mechadoll_Poochyena3::
	.ifdef ENGLISH
	.string "POOCHYENA$"
	.else
	.ifdef GERMAN
	.string "FIFFYEN$"
	.endif
	.endif

gTrickHouse_Mechadoll_Zubat2::
	.ifdef ENGLISH
	.string "ZUBAT$"
	.else
	.ifdef GERMAN
	.string "ZUBAT$"
	.endif
	.endif

gTrickHouse_Mechadoll_Carvanha::
	.ifdef ENGLISH
	.string "CARVANHA$"
	.else
	.ifdef GERMAN
	.string "KANIVANHA$"
	.endif
	.endif

gTrickHouse_Mechadoll_BurnHeal::
	.ifdef ENGLISH
	.string "BURN HEAL$"
	.else
	.ifdef GERMAN
	.string "FEUERHEILER$"
	.endif
	.endif

gTrickHouse_Mechadoll_HarborMail::
	.ifdef ENGLISH
	.string "HARBOR MAIL$"
	.else
	.ifdef GERMAN
	.string "HAFENBRIEFe$"
	.endif
	.endif

gTrickHouse_Mechadoll_SamePrice::
	.ifdef ENGLISH
	.string "Same price$"
	.else
	.ifdef GERMAN
	.string "Gleicher Preis$"
	.endif
	.endif

gTrickHouse_Mechadoll_60Yen::
	.ifdef ENGLISH
	.string "¥60$"
	.else
	.ifdef GERMAN
	.string "¥60$"
	.endif
	.endif

gTrickHouse_Mechadoll_55Yen::
	.ifdef ENGLISH
	.string "¥55$"
	.else
	.ifdef GERMAN
	.string "¥55$"
	.endif
	.endif

gTrickHouse_Mechadoll_Nothing::
	.ifdef ENGLISH
	.string "Nothing$"
	.else
	.ifdef GERMAN
	.string "Nichts$"
	.endif
	.endif

gTrickHouse_Mechadoll_CostMore::
	.ifdef ENGLISH
	.string "They will cost more.$"
	.else
	.ifdef GERMAN
	.string "Sie kosten mehr.$"
	.endif
	.endif

gTrickHouse_Mechadoll_CostLess::
	.ifdef ENGLISH
	.string "They will cost less.$"
	.else
	.ifdef GERMAN
	.string "Sie kosten weniger.$"
	.endif
	.endif

gTrickHouse_Mechadoll_SamePrice2::
	.ifdef ENGLISH
	.string "Same price$"
	.else
	.ifdef GERMAN
	.string "Gleicher Preis$"
	.endif
	.endif

gTrickHouse_Mechadoll_Male::
	.ifdef ENGLISH
	.string "Male$"
	.else
	.ifdef GERMAN
	.string "Männer$"
	.endif
	.endif

gTrickHouse_Mechadoll_Female::
	.ifdef ENGLISH
	.string "Female$"
	.else
	.ifdef GERMAN
	.string "Frauen$"
	.endif
	.endif

gTrickHouse_Mechadoll_Neither::
	.ifdef ENGLISH
	.string "Neither$"
	.else
	.ifdef GERMAN
	.string "Weder noch$"
	.endif
	.endif

gTrickHouse_Mechadoll_ElderlyMen::
	.ifdef ENGLISH
	.string "Elderly men$"
	.else
	.ifdef GERMAN
	.string "Ältere Herren$"
	.endif
	.endif

gTrickHouse_Mechadoll_ElderlyLadies::
	.ifdef ENGLISH
	.string "Elderly ladies$"
	.else
	.ifdef GERMAN
	.string "Ältere Damen$"
	.endif
	.endif

gTrickHouse_Mechadoll_SameNumber::
	.ifdef ENGLISH
	.string "Same number$"
	.else
	.ifdef GERMAN
	.string "Gleich viele$"
	.endif
	.endif

gTrickHouse_Mechadoll_None::
	.ifdef ENGLISH
	.string "None$"
	.else
	.ifdef GERMAN
	.string "Keine$"
	.endif
	.endif

gTrickHouse_Mechadoll_One::
	.ifdef ENGLISH
	.string "1$"
	.else
	.ifdef GERMAN
	.string "1$"
	.endif
	.endif

gTrickHouse_Mechadoll_Two::
	.ifdef ENGLISH
	.string "2$"
	.else
	.ifdef GERMAN
	.string "2$"
	.endif
	.endif

gTrickHouse_Mechadoll_Two2::
	.ifdef ENGLISH
	.string "2$"
	.else
	.ifdef GERMAN
	.string "2$"
	.endif
	.endif

gTrickHouse_Mechadoll_Three::
	.ifdef ENGLISH
	.string "3$"
	.else
	.ifdef GERMAN
	.string "3$"
	.endif
	.endif

gTrickHouse_Mechadoll_Four::
	.ifdef ENGLISH
	.string "4$"
	.else
	.ifdef GERMAN
	.string "4$"
	.endif
	.endif

gTrickHouse_Mechadoll_Six::
	.ifdef ENGLISH
	.string "6$"
	.else
	.ifdef GERMAN
	.string "6$"
	.endif
	.endif

gTrickHouse_Mechadoll_Seven::
	.ifdef ENGLISH
	.string "7$"
	.else
	.ifdef GERMAN
	.string "7$"
	.endif
	.endif

gTrickHouse_Mechadoll_Eight::
	.ifdef ENGLISH
	.string "8$"
	.else
	.ifdef GERMAN
	.string "8$"
	.endif
	.endif

gTrickHouse_Mechadoll_Six2::
	.ifdef ENGLISH
	.string "6$"
	.else
	.ifdef GERMAN
	.string "6$"
	.endif
	.endif

gTrickHouse_Mechadoll_Seven2::
	.ifdef ENGLISH
	.string "7$"
	.else
	.ifdef GERMAN
	.string "7$"
	.endif
	.endif

gTrickHouse_Mechadoll_Eight2::
	.ifdef ENGLISH
	.string "8$"
	.else
	.ifdef GERMAN
	.string "8$"
	.endif
	.endif
